- .gitlab-ci.yml
The change in this PR ensures we start running the pipelines as soon as the branch is created.
> chore: create step to prepare deploy (#11)

- .gitlab-ci.yml
CRA will already set this when running `react-scripts build`, but our packages have just one build script no matter if the final apps are being watch-run during development or built for production, so we should make sure everything is built for production with any optimizations applied on CI.
> ci: build with NODE_ENV=production

- serverless.js
should remove the warnings from the CI deploy job
> build(sls): decrease timeout below AWS Lambda limit

- apps/orcid-user-profile-script/tsconfig.json
They are not needed as we give TSC the paths to all our subprojects,
and they are annoying to keep in sync with subproject dependencies.
> build(ts): clean up unnecessary projects references

- apps/hello-world/package.json
- apps/orcid-user-profile-script/package.json
- packages/auth/package.json
- packages/example-lib/package.json
This works for dev:
```
Error: Not implemented
at error (/home/seckinger/proj/yld/asap-hub/apps/hello-world/build/handler.js:21:9)
```
becomes
```
Error: Not implemented
at error (/home/seckinger/proj/yld/asap-hub/apps/hello-world/src/handler.ts:14:9)
```
If we want it for prod at some point, it'll need more effort - checking why serverless-plugin-ncc does not do it, or evaluating alternatives to it.
> build(backend): source maps

- apps/orcid-user-profile-script/tsconfig.json
- scripts/get-composite-ts-projects.js
Turns out not specifying them is not an option, even when we include all projects in the build anyway. They are still required for TypeScript to understand the dependency graph and build in the correct order. This was surfaced by https://github.com/yldio/asap-hub/pull/22.
So we do have to specify them all, but I extended our script to automatically check and enforce that they are present.
> build(ts): require project references to all dependencies

- scripts/get-composite-ts-projects.js
This makes the error message in case a project is missing a tsconfig
a lot less confusing
> build(ts): do not read root tsconfig for projects missing one

- LICENSE.txt
- README.md
- package.json
The ASAP Hub product concept document mentioned that the hub should be open source and MIT-licensed. So far, it was only open source, but not declared as free and open source, let alone specifically MIT licensed. This should clarify that.
> docs(license): add MIT license file

- apps/frontend/src/admin/__tests__/Admin.test.tsx
- apps/frontend/src/home/__tests__/Home.test.tsx
This is usually what you want (except in .not cases),
making sure that the element is not hidden.
> test: toBeInTheDocument => toBeVisible

- packages/react-components/src/atoms/TextField.tsx
- packages/react-components/src/atoms/__tests__/TextField.test.tsx
aka
fix(password-field): do not show valid indicator below show/hide button
> fix(text-field): avoid showing valid indicator below custom indicator

- apps/frontend/src/admin/__tests__/Admin.test.tsx
The 'an update to Admin was not wrapped in act()' warning appeared occasionally (flaky),
hopefully this was the cause.
> test(Admin): fix React act update warning

- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/entities/user.ts
- apps/asap-server/test/helpers/create-user.ts
- apps/frontend/src/users/Profile.tsx
- apps/storybook/src/ProfileHeader.stories.tsx
- dev/squidex/schemas/teams.json
- dev/squidex/schemas/users.json
- packages/model/src/user.ts
- packages/react-components/src/icons/docs.tsx
- packages/react-components/src/icons/index.ts
- packages/react-components/src/index.ts
- packages/react-components/src/templates/ProfileBiography.tsx
- packages/react-components/src/templates/index.ts
Change the schema to include biography for each user and show it on the profile page.
We need to revisit the design of the page when the header of the page and the other sections are included.
> feat: change schema to add biography

- packages/react-components/src/atoms/Link.tsx
- packages/react-components/src/atoms/__tests__/Link.test.tsx
Fixes https://trello.com/c/kgrugxNf/288-website-link-redirects-the-user-to-an-internal-page
First I thought I'd need to write a test that mocks the `location`, actually clicks the link, and then checks where it *really* redirected to (which would still be the safest way to test, but make the test even more complex), but this also catches such an error nicely:
> fix(link): identify external links even in a router context

- packages/react-components/src/atoms/Card.tsx
- packages/react-components/src/atoms/GlobalStyles.tsx
- packages/react-components/src/templates/WelcomePage.tsx
- packages/react-components/src/text.ts
The dark background is closer to the background image,
so the image loading top-to-bottom will be less visible.
> fix(welcome): use dark theme except on card

- .gitlab-ci.yml
- ci/.gitlab-ci.ses.yml
- ci/README.md
- ci/config-squidex-rules.sh
- ci/env-create.sh
- ci/env-setup.sh
- packages/auth/src/config.ts
- serverless.js
- Use `ASAP` prefix variables on CI
- Explicit `source ci/env-create.sh` when building and deploying feature branches
- Usage of auxiliary env vars prefixed with `SQUIDEX_TEST` for tests
- Rebuild for production not development or feature branches
> chore: create build dev by default

- packages/react-components/src/molecules/TeamCard.tsx
- packages/react-components/src/molecules/__tests__/TeamCard.test.tsx
This CSS is a bit ... _wild_, but I think it's a good solution for the issue we chatted about @kmaid.
Also don't forget the list of tags should be extracted into a `TagList` molecule that can take a prop for whether it should cut off. That molecule can then be used in `ProfileSkills` as well.
> refactor(team-card): use CSS to cut off skill tags overflow

- packages/react-components/src/__tests__/layout.test.ts
- packages/react-components/src/__tests__/pixels.test.ts
- packages/react-components/src/atoms/NavigationLink.tsx
- packages/react-components/src/layout.ts
- packages/react-components/src/organisms/MenuHeader.tsx
- packages/react-components/src/pixels.ts
- packages/react-components/src/templates/ContentPage.tsx
- packages/react-components/src/templates/Layout.tsx
- packages/react-components/src/templates/NetworkPage.tsx
- packages/react-components/src/templates/NetworkPageHeader.tsx
- packages/react-components/src/templates/ProfileAbout.tsx
- packages/react-components/src/templates/ProfileHeader.tsx
- packages/react-components/src/templates/ProfileResearch.tsx
- packages/react-components/src/templates/RecordOutputPage.tsx
- packages/react-components/src/templates/SigninPage.tsx
- packages/react-components/src/templates/TeamAbout.tsx
- packages/react-components/src/templates/TeamHeader.tsx
And move some out of `pixels` which has become quite large.
Useful prerequisite to make the upcoming PR for the user menu smaller.
> refactor(layout): extract some shared layout styling info

- .gitlab-ci.yml
The stop job requires the artifacts from the build step.
> chore: expire artifacts after 2 weeks

- dev/squidex/schemas/teams.json
* On `research-outputs` title needs to be the first property to show on the proposal selection drop-down
* The team proposal property references a `research-output`
> chore: use proposal reference

- ci/.gitlab-ci.squidex.yml
Due to our continuous deployment pipeline we can have a change to squidex schema to be superseded by a newer deployment.
To avoid it we should apply squidex changes on every production deploy.
> chore: apply squidex changes on every deploy

- apps/auth-frontend/src/auth0/__tests__/errors.test.ts
- apps/auth-frontend/src/auth0/errors.ts
Signalize verification success via icons instead.
This avoid confusion in the case of the message
'Must fulfill 3 of 4 criteria'
and only the 2 failed criteria instead of all 4 being shown.
> fix(auth-frontend): show all error items

- packages/react-components/src/organisms/PageControls.tsx
If there are two pages, and the current page is the first,
'1 ...' was shown on mobile, while on the second page '1 2' was shown
correctly. This fixes it so that both pages show '1 2' correctly.
Unfortunately, this cannot be tested yet, because JSDOM doesn't let us
check how things look on mobile. I may have something in the pipeline
for that...
> fix(page-controls): '1 ...' on mobile

- packages/react-components/src/atoms/Link.tsx
- packages/react-components/src/atoms/__tests__/Link.test.tsx
Previously, react-router links would treat "" like "/",
while normal anchors would treat ""
like the URL constructor (no URL change).
Now, we avoid react-router for empty hrefs so that
the behavior is always the latter.
> fix(link): consistent behavior with href=""

- apps/frontend/src/App.tsx
- apps/frontend/src/research-outputs/Routes.tsx
- apps/frontend/src/welcome/Routes.tsx
- apps/storybook/src/NotFoundPage.stories.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/templates/NotFoundPage.tsx
- packages/react-components/src/templates/__tests__/NotFoundPage.test.tsx
- packages/react-components/src/templates/index.ts
Taking care of 404 pages for missing ids in another PR where I also address handling other kinds of backend errors,
but this can already go in for now and be design reviewed.
> feat: 404 page for static routes

- apps/frontend/src/App.tsx
And prefetch sequentially. This means that on slower networks (where
prefetching matters most, and the bandwidth is so constrained that
fetching more bundles at once does not increase overall throughput), the
first sections will complete prefetching earlier because they do not
share bandwidth with other bundles being prefetched. The order should
reflect how likely we think users are to navigate to each section.
> perf(frontend): prefetch more sections

- apps/storybook/src/Avatar.stories.tsx
- packages/react-components/src/atoms/Avatar.tsx
- packages/react-components/src/atoms/__tests__/Avatar.test.tsx
- packages/react-components/src/molecules/UserMenuButton.tsx
- packages/react-components/src/organisms/MembersSection.tsx
- packages/react-components/src/organisms/PeopleCard.tsx
- packages/react-components/src/templates/TeamHeader.tsx
- packages/react-components/src/templates/TeamPage.tsx
I've changed the team page to have enough space available.
Avatars can now scale according to the available space.
I hadn't considered the difficulty scaling the initials,
but with a simple SVG it's reasonably easy,
and the autoscaling has e.g. the advantage of being able to
fill exactly one row with Avatars, as is done in the new team header.
I've also refactored the team header's extra users bubble
into the Avatar component to share styling with the real Avatar bubbles.
> fix: team header Avatar scaling

- apps/storybook/src/MembersSection.stories.tsx
- apps/storybook/src/TeamPage.stories.tsx
- packages/fixtures/src/teams.ts
- packages/react-components/src/atoms/Avatar.tsx
- packages/react-components/src/atoms/__tests__/Avatar.test.tsx
- packages/react-components/src/molecules/__tests__/UserMenuButton.test.tsx
- packages/react-components/src/templates/__tests__/TeamHeader.test.tsx
Background images are just so much easier to deal with,
and now images are pretty much guaranteed to
behave like the fallback initials, since it's the same element...
> fix(avatar): overflow on small avatars

- apps/frontend/src/App.tsx
This is a fix for Network not being highlighted. I spoke with James and their ideal would be network highlighted for all pages under network except team internal and user internal pages. This sounds like it needs specced out to understand how hilighting of navigation links will work on all pages post MVP so I will bring this up in standup on Monday
> Fix: Change link

- packages/react-components/src/templates/Layout.tsx
Works pretty nicely even when scrolling down in the side menu and then clicking the overlay to hide it. Can try it out in Storybook on mobile landscape.
> fix(layout): prevent side menu from causing scrollbar on low heights

- packages/react-components/src/organisms/Modal.tsx
and change absolute positioning to grid because why not
> fix(modal): scrollbar not in the middle of nowhere when overflowing Y

- apps/frontend/src/history/__tests__/index.test.tsx
- apps/frontend/src/history/index.ts
- apps/frontend/src/network/teams/Workspace.tsx
- apps/frontend/src/network/users/About.tsx
- apps/frontend/src/network/users/Editing.tsx
- apps/frontend/src/network/users/Research.tsx
We first tried actually aborting the save requests,
however that would almost 100% of the time not actually prevent the
change being made, meaning now we had to initiate another GET for the
changed value. This wastes resources and increased the code of each
useXById and their tests by a lot.
We decided to instead let the request complete (and update our state
with the change) and only ensure that the Promise resolution does not
trigger a navigation when the user might already be somewhere else
entirely.
There is technically another edge case now when you save-abort-reenter
the modal, but the incoming response closing the modal in that case
actually seems reasonable given that the modal contains stale data.
> fix(modals): prevent navigation when already elsewhere

- apps/frontend/src/App.tsx
- apps/frontend/src/GuardedApp.tsx
- apps/frontend/src/__tests__/GuardedApp.test.tsx
- apps/frontend/src/auth/index.ts
- apps/frontend/src/auth/react-auth0-spa.tsx
- apps/frontend/src/network/teams/state.ts
- apps/frontend/src/network/users/state.ts
- apps/frontend/src/routes.ts
- packages/react-components/src/auth-test-utils.tsx
- packages/react-components/src/index.ts
We only need it behind the auth guard.
Also it's nice to split up App at least a bit
> perf: kick recoil out of the React bundle

- apps/asap-server/src/utils/instrumented-framework.ts
Traces corresponding to faulty requests will be flagged as such, and list the error body in the event
> feat: add tracing errors

- apps/frontend/src/auth/react-auth0-spa.tsx
This is a bit of a weird one. 
See: https://github.com/auth0/auth0-spa-js/issues/449
I have been able to test this with my own expired refresh token and @fampinheiro's. If you have an expired refresh token you will be sent to the login page and signin as usual.
What i have been unable to test is when the access token has expired (after 24 hours) and the refresh token is still valid because it is signed.
I have saved my current session to test this tomorrow but I think this should go in as this will allow people who are currently locked out to access the hub.
> fix: infinite loading when session so old that refresh token expired

- apps/frontend/src/auth/react-auth0-spa.tsx
See: https://auth0.github.io/auth0-spa-js/classes/auth0client.html#checksession
Currently if an access token expires a user will be sent to the login page. This means unnecessary logins. This call will check if a session is valid and if not try and get a new access token using the refresh token. If this fails we proceed with normal signin process
> Fix: Use refresh token to get new access token after 24 hours

- apps/asap-server/src/controllers/groups.ts
- apps/asap-server/src/handlers/groups/fetch-by-team-id.ts
- apps/asap-server/test/handlers/groups/fetch-by-team-id.test.ts
- serverless.js
See: https://trello.com/c/pIP6RsXT/871-create-api-to-obtain-group-data-for-each-team-team-page-updates
> feat: add fetch-groups-by-team-id endpoint

- apps/asap-server/src/app.ts
- apps/asap-server/src/controllers/groups.ts
- apps/asap-server/src/routes/teams.route.ts
- apps/asap-server/test/mocks/group-controller.mock.ts
- apps/asap-server/test/routes/teams.test.ts
- serverless.js
see: https://trello.com/c/RZp9YZg5/893-update-express-router-to-reply-to-groups-resources-and-endpoints
> feat: Move groups-by-team-id handler to express

- Dockerfile
The image was not building (at least not on Ubuntu 17.04 with Docker 18.01) due to some dependency errors for mongodb-org. 
This PR changes the base image to Ubuntu (from Debian) and updates mongodb installation method.
> fix: squidex setup image

- packages/react-components/src/atoms/Anchor.tsx
- packages/react-components/src/atoms/Link.tsx
- packages/react-components/src/atoms/__tests__/Anchor.test.tsx
- packages/react-components/src/atoms/__tests__/Link.test.tsx
- packages/react-components/src/atoms/index.ts
- packages/react-components/src/molecules/ErrorCard.tsx
- packages/react-components/src/molecules/ExternalLink.tsx
- packages/react-components/src/molecules/MembersList.tsx
- packages/react-components/src/molecules/PageControls.tsx
- packages/react-components/src/organisms/GroupCard.tsx
- packages/react-components/src/organisms/NewsAndEventsCard.tsx
- packages/react-components/src/organisms/PeopleCard.tsx
- packages/react-components/src/organisms/SharedResearchCard.tsx
- packages/react-components/src/organisms/TeamCard.tsx
- packages/react-components/src/organisms/ToolCard.tsx
- packages/react-components/src/organisms/UserNavigation.tsx
- packages/react-components/src/organisms/UserProfileRecentWorks.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- packages/react-components/src/templates/WelcomePage.tsx
As discussed. I've tried extracting it into just a hook but returning an element type and props there is just stupid, so it's a component after all, but one that with its props interface and everything is kind of a transparent anchor and can be passed all anchor attributes.
> refactor(react-components): do not use Link where we really just want the HashLink/anchor behavior

- packages/squidex/schema/schemas/research-outputs.json
Create a tags property on research output for back office management.
> feat: research output tags

- apps/asap-server/src/handlers/webhooks/webhook-calendar-created.ts
- apps/asap-server/test/handlers/webhooks/webhook-calendar-created.test.ts
Fixes the issue whereby the hook, upon receiving a calendar entry with an empty calendar ID, attempts to subscribe and fails.
> fix: Calendar-created webhook notFound error

- apps/asap-server/src/config.ts
- apps/asap-server/src/handlers/webhooks/webhook-calendar-created.ts
- apps/asap-server/test/handlers/webhooks/webhook-calendar-created.test.ts
- packages/squidex/src/entities/calendar.ts
- serverless.js
see: https://trello.com/c/emZkLgNb/1016-add-authentication-to-event-webhook
this will enable us to authenticate requests coming from google api
Other changes:
* add the resourceId removal from the db once unsubscribed from the channel - this will prevent us from seeing errors about a failed unsubscribing attempt after the calendar ID was previously set to null
> feat: Add API token to google event subscription

- packages/squidex/schema/schemas/calendars.json
Makes the calendar ID required and applies a min length validation of 8 characters
> fix: Make Calendar ID required

- .gitlab-ci.yml
This PR speeds up the CI pipeline by switching from standard node image to node-alpine
> chore: Update to node-alpine in the CI

- apps/asap-server/src/controllers/events.ts
- apps/asap-server/src/utils/sync-google-event.ts
- apps/asap-server/test/controllers/events.test.ts
- apps/asap-server/test/fixtures/events.fixtures.ts
- apps/asap-server/test/utils/sync-google-event.test.ts
- packages/squidex/schema/schemas/events.json
- packages/squidex/src/entities/event.ts
Add a new 'hidden' flag to the event entity plus enables the filter inside event control so they are removed from the response by default.
see: https://trello.com/c/DSugpat0/1064-as-an-admin-i-want-to-be-able-to-hide-cms-events-from-fe-and-keep-them-hidden
> feat: event 'hidden' flag

- Dockerfile
Running different versions of the CLI on the CI or on our local computers means that the schema we `sync in` - through the CLI sync step - and the schemas we `sync out`  locally are always different. This should fix that.
> feat(squidex-setup): update cli to version 6.2

- README.md
- package.json
This PR does the following changes:
- updates the README with a "Setting up your development environment" section, with more details on how to get a new user running
- adds a script to run the frontend app from the project's root
> docs: Update readme with onboarding details

- apps/asap-server/src/entities/event.ts
This PR is an iteration on the requirements of this ticket: https://trello.com/c/aEpe05ua/1060-marking-meeting-materials-of-an-event-as-permanently-unavailable-tick-box.
- As stated in the comments. The tickbox takes precedence over contente (was already implemented)
- Content is considered permanently unavailable if empty and event is more than 14 days old
> feat: event content is stale after 14 days

- apps/storybook/src/GroupProfileAbout.stories.tsx
- packages/react-components/src/__tests__/mail.test.ts
- packages/react-components/src/mail.ts
- packages/react-components/src/templates/GroupProfileAbout.tsx
- packages/react-components/src/templates/__tests__/GroupProfileAbout.test.tsx
This PR introduces the following changes:
- adds a CtaCard to GroupProfileAbout template
- checks whether there's a Group as one or more leaders with the role "Project Manager", and if there's any show the Call to Action, providing the PM's email to the mailTo link
- changes the signature of the createMailTo function, allowing for a single email (string) or a list of emails to be passed
- extracts two functions from the above function, to create both a URL to a single email or a list of emails
> feat: add CTA (Contact PM) to group about template

- .gitlab-ci.yml
- ci/.gitlab-ci.squidex.yml
This puts the `squidex sync:dev` step before the dev deployment and adds a dependency on the sync itself thus making it required to run the entire pipeline.
> chore: Apply correct order to squidex sync in ci

- apps/frontend/src/network/groups/events/EventList.tsx
- apps/frontend/src/network/groups/events/__tests__/EventList.test.tsx
- apps/frontend/src/network/groups/events/__tests__/api.test.ts
- apps/frontend/src/network/groups/events/api.ts
- apps/frontend/src/network/groups/events/state.ts
- apps/frontend/src/network/teams/groups/GroupsCard.tsx
- apps/frontend/src/network/teams/groups/__tests__/GroupsCard.test.tsx
- apps/frontend/src/network/teams/groups/__tests__/api.test.ts
- apps/frontend/src/network/teams/groups/api.ts
- apps/frontend/src/network/teams/groups/state.ts
- apps/frontend/src/network/users/Research.tsx
- apps/frontend/src/network/users/groups/GroupsCard.tsx
- apps/frontend/src/network/users/groups/__tests__/GroupsCard.test.tsx
- apps/frontend/src/network/users/groups/__tests__/api.test.ts
- apps/frontend/src/network/users/groups/api.ts
- apps/frontend/src/network/users/groups/state.ts
We don't really use this new API client capability yet (all the consumers are components used in contexts where we expect the parent resource has to be present so that you are even able to get to that place in the frontend) and continue to throw (show error boundaries) if these 404s happen.
But still, we should model API clients to represent every expected error with a return value, and only unexpected errors by throwing — at some point somewhere we'll want custom handling for the 404 because we're fetching a sub resource without having tried to fetch the parent yet, and if only then we start modeling the API clients to cover all expected cases, we'll have inconsistencies.
> refactor(frontend): handle possible 404s on sub resources

- packages/react-components/src/messages/Welcome.tsx
- packages/react-components/src/messages/__tests__/Welcome.test.tsx
This PR introduces the following changes:
* new copy
* renames the test file to represent the test naming convention of the project
* tests check for CTA to Activate Account and mail to Support
> feat: change welcome email's copy

- apps/asap-server/src/utils/sync-google-calendar.ts
- apps/asap-server/test/utils/sync-google-calendar.test.ts
Fixes a bug whereby a deleted event remains confirm upon sync after being deleted from the calendar. 
See comments of: https://trello.com/c/1NRKvLxZ/1102-syncing-with-gcal-is-failing for more details
> fix: Changing event status to cancelled

- apps/asap-server/src/controllers/events.ts
- apps/asap-server/test/controllers/events.test.ts
Modifies the 'before' filter to use the end-date.
see: https://trello.com/c/5c8774jp/1138-current-event-showing-up-as-a-past-event
> fix: Current event showing up as a past event

- apps/frontend/src/GuardedApp.tsx
- apps/frontend/src/auth/Logout.tsx
- apps/frontend/src/dashboard/Dashboard.tsx
- apps/frontend/src/discover/Discover.tsx
- apps/frontend/src/news/Routes.tsx
- apps/frontend/src/shared-research/Routes.tsx
Frame title placement was inconsistent. This makes it more consistent
and fixes some titles being inside the relevant suspense boundaries,
such as for Dashboard and Discover.
It should be `<Frame title="SomeAreaOfTheHub"><SomeAreaOfTheHub /></Frame>`,
the Frame with the title should not be inside the `SomeAreaOfTheHub` component.
> fix(frontend): show page titles on suspended pages

- packages/squidex/schema/schemas/events.json
- packages/squidex/schema/schemas/research-outputs.json
Ticket: https://trello.com/c/8L0uIAHV/1158-validate-external-link-on-shared-output-schema-on-the-cms
Production data is conforming to the new restrictions (i.e. all start with `https`)
> feat(external-links): URL needs to start with http(s)

- apps/asap-cli/src/import/protocols/insert.ts
- apps/asap-cli/test/import/protocols.fixture.ts
- apps/asap-server/.eslintrc.js
- apps/asap-server/package.json
- apps/asap-server/scripts/create-migration.sh
- apps/asap-server/scripts/migration.template
- apps/asap-server/src/config.ts
- apps/asap-server/src/handlers/webhooks/webhook-run-migrations.ts
- apps/asap-server/src/migrations/1617196731-move-research-output-text-to-description.ts
- apps/asap-server/src/migrations/1617197205-test-migration.ts
- apps/asap-server/test/handlers/webhooks/webhook-run-migrations.test.ts
- apps/asap-server/test/mocks/squidex-client.mock.ts
- packages/squidex/schema/schemas/migrations.json
- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/src/entities/index.ts
- packages/squidex/src/entities/migration.ts
- packages/squidex/src/entities/research-output.ts
- serverless.js
Creates a tool for running schema migrations. Can be used with squidex or any other types of migrations.
Work required for: https://trello.com/c/K7U0AkBH/1157-rename-shared-output-schemas-text-field-to-description
> feat: Create schema migration runner

- apps/frontend/src/network/__tests__/Network.test.tsx
- apps/frontend/src/network/groups/GroupList.tsx
- apps/frontend/src/network/groups/__tests__/GroupList.test.tsx
- apps/frontend/src/network/groups/state.ts
- apps/frontend/src/network/teams/TeamList.tsx
- apps/frontend/src/network/teams/__tests__/TeamList.test.tsx
- apps/frontend/src/network/teams/state.ts
- apps/frontend/src/network/users/UserList.tsx
- apps/frontend/src/network/users/__tests__/UserList.test.tsx
- apps/frontend/src/network/users/state.ts
It looks like this is actually the only low-hanging fruit left after all.
Everything else is not good to prefetch at this point for one of two reasons:
* Links between user/team/group profiles are always 1-to-n, so we may be prefetching 10 things at once.
* It's an entity still fetched via use-http, in particular shared research has lots of prefetching opportunities once migrated over.
> perf(frontend): prefetch other network tabs

- apps/frontend/src/network/users/groups/__tests__/GroupsCard.test.tsx
- packages/react-components/src/organisms/UserProfileGroups.tsx
- packages/react-components/src/organisms/__tests__/UserProfileGroups.test.tsx
Fix a typo on the Title of Profile's Group Card.
Note:
- Are we testing this twice??
> Fix: group card's title

- apps/asap-server/scripts/create-migration.sh
- apps/asap-server/scripts/migration.template
- apps/asap-server/src/migrations/1617196731-move-research-output-text-to-description.ts
- apps/asap-server/src/migrations/1618488149-publish-date-to-added-date.ts
- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/src/entities/research-output.ts
Ticket: https://trello.com/c/ipMAHg9b/1160-migrate-research-output-original-publishing-date-to-added-date?menu=filter&filter=label:BE
> **this PR only addressed the first 2 requirements** 
- fix(migrations): fix date function & old migration
- makes the date command work on OSX and Linux
- use script relative paths 
- simplifies the template
- fixes pagination on old migraition script (should not run for old envs though)
- feat(migrations): add addedDate migration script
- successfully ran script agains temp environment
>  feat(migrations): migrate publishDate to addedDate

- apps/asap-server/src/migrations/1618575365-move-short-text-to-admin-notes.ts
- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/src/entities/research-output.ts
https://trello.com/c/YUtW7fLX/1159-rename-short-text-field-to-admin-notes
Creates a new field - `adminNotes`, and moves all the data from the `shortText` field. 
A follow up PR is expected to remove the `shortText` field
> feat: Rename short-text to admin-notes

- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/src/entities/research-output.ts
see: https://trello.com/c/YUtW7fLX/1159-rename-short-text-field-to-admin-notes
> feat: Remove short-text field from Research Outputs

- packages/squidex/schema/schemas/research-outputs.json
Fix as asked in the comments: https://trello.com/c/Zk49QfyC/1185-change-the-field-original-publish-date-on-the-cms
> chore(cms): change publish date hint

- apps/asap-server/src/controllers/events.ts
- apps/asap-server/src/controllers/groups.ts
- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/utils/squidex.ts
- apps/asap-server/test/controllers/events.test.ts
- apps/asap-server/test/controllers/groups.test.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/controllers/teams.test.ts
- apps/asap-server/test/controllers/users.test.ts
Sanitise search inputs by escaping to hex.
see: https://trello.com/c/7pUQV9hP/1242-%F0%9F%90%9B-searching-with-apostrophes-breaks-the-search
* The sanitisation should, imho, happen inside the client as its client specific. The reason I did not do it there is because the client currently only accepts a formatted query, and query generation happens at the controller level anyway. 
* Following up on the above - I think it would be much better to use `variables` part of the graphql queries rather than embed all the params in the query - a tech debt ticket can be found here: https://trello.com/c/Ahlq8rgV/1259-move-graphql-query-parameters-to-the-variables
* We use the, technically deprecated, built in `escape` function to escape these characters - so far i have not been able to find any better …
> fix: Quotation marks search bug

- apps/asap-server/src/controllers/groups.ts
- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/src/entities/research-output.ts
- apps/asap-server/src/entities/team.ts
- apps/asap-server/src/routes/research-outputs.route.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/controllers/teams.test.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- apps/asap-server/test/routes/research-outputs.route.test.ts
- packages/fixtures/src/research-outputs.ts
- packages/model/src/research-output.ts
- packages/squidex/src/entities/research-output.ts
This PR adds teams do research-output response. 
Previously only a single team was present. However - because the RO response itself is also being attached to other various responses (ie Group response or Team response), this PR attaches them only for teams, not for groups.
This means that a team->RO->teams traversal is possible, but group->team->RO->teams is not. In order to adhere to the same contract - for the Group response only the parent team is being copied across into the `teams` property.
https://trello.com/c/FarA5LEp/1130-as-an-admin-i-want-to-associate-an-output-to-more-than-one-team-to-correctly-address-authorship
> feat: Add teams to research-output response

- apps/asap-server/src/app.ts
- apps/asap-server/src/routes/user.route.ts
- apps/asap-server/test/controllers/users.test.ts
- apps/asap-server/test/routes/user.route.test.ts
see: https://trello.com/c/3NCCfjad/1006-i-can-go-through-registration-with-an-invalid-invitation-code
Enables a public endpoint for users to fetch their basic details (ID and display name) by the invitation code.
* If the code is invalid returns 403.
> feat: Add user-by-code endpoint to verify welcome code

- ci/.gitlab-ci.integration.yml
Since there is no PR number on the master build, the squidex app name is only `-$CI_JOB_ID`.
Which makes the create script fail.
This should fix it.
> fix(tests): squidex app name in master is misformated

- apps/asap-server/src/config.ts
The `APP_ORIGIN` variable is only used for auth purposes. 
We use is to select the user metadata on Auth0's id_token correct namespace.
We always run against our dev environment, hence I'm changing the default to point to that.
> chore(config): app origin default points to dev

- apps/asap-server/@types/express/index.d.ts
- apps/asap-server/src/app.ts
- apps/asap-server/src/middleware/error-handler.ts
- apps/asap-server/src/middleware/user-logger-handler.ts
- apps/asap-server/test/middleware/user-logger-handler.test.ts
https://trello.com/c/MXa8c7RB/1112-add-user-id-to-log-output
* this PR only adds `userId` property to the request related log lines and not to the custom logs from the `logger` instance
> feat: Add user-id to request info log

- apps/asap-server/src/app.ts
Adds pino-noir back in to hide the auth headers, accidentally removed in: https://github.com/yldio/asap-hub/pull/845
> fix: Hide bearer token from auth header

- apps/storybook/src/SharedResearchOutput.stories.tsx
- apps/storybook/src/TeamsList.stories.tsx
- packages/model/src/research-output.ts
- packages/react-components/src/molecules/TeamsList.tsx
- packages/react-components/src/molecules/__tests__/TeamsList.browser-test.tsx
- packages/react-components/src/molecules/__tests__/TeamsList.test.tsx
- packages/react-components/src/organisms/SharedResearchOutputHeaderCard.tsx
- packages/react-components/src/organisms/__tests__/SharedResearchOutputHeaderCard.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/SharedResearchOutput.tsx
- packages/react-components/src/templates/__tests__/SharedResearchOutput.test.tsx
Recommend looking at the two commits separately:
- refactor(shared-research-output): extract header card component
- feat(shared-research-output): teams in header
> feat(shared-research-output): teams in header

- packages/model/src/research-output.ts
- packages/squidex/schema/schemas/research-outputs.json
QA comments on the ticket: https://trello.com/c/gK3a6puv/1132-update-roms-schema
- `accessInstructions` is RTF
- `subType` 'Other' should be removed
> fix(ROMS): remove 'Other' subtype, accessInstructions RTF

- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/entities/research-output.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/research-output.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- apps/asap-server/test/routes/research-outputs.route.test.ts
- packages/fixtures/src/research-outputs.ts
- packages/model/src/research-output.ts
as per: https://trello.com/c/W40XJ3QT/1233-show-aditional-information-on-an-output-detail-page
Adds the following to research-output endpoint responses:
* usedInPublication
* asapFunded
* sharingStatus
* `usedInPublication` was used in the response, omitting the article `a` which is present in the DB
> feat: Show additional research-output information

- apps/asap-cli/src/import/users/insert.ts
- apps/asap-cli/test/import/protocols.fixture.ts
- apps/asap-cli/test/import/users.test.ts
- apps/asap-cli/test/invite.fixtures.ts
- apps/asap-server/src/entities/user.ts
- apps/asap-server/src/migrations/1622036244-add-default-onboarded-field-to-users.ts
- apps/asap-server/src/utils/__mocks__/validate-token.ts
- apps/asap-server/src/utils/migrations.ts
- apps/asap-server/test/controllers/teams.test.ts
- apps/asap-server/test/fixtures/discover.fixtures.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/orcid.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- apps/asap-server/test/fixtures/users.fixtures.ts
- apps/asap-server/test/handlers/webhooks/cronjob-sync-orcid.fixtures.ts
- apps/asap-server/test/handlers/webhooks/webhook-connect.test.ts
- apps/asap-server/test/handlers/webhooks/webhook-sync-orcid.fixtures.ts
- apps/asap-server/test/helpers/users.ts
- apps/asap-server/test/middleware/auth-handler.test.ts
- apps/asap-server/test/utils/migrations.test.ts
- apps/auth0-rules/src/__tests__/add-user-metadata.test.ts
- apps/auth0-rules/src/add-user-metadata.ts
- apps/frontend/src/auth/test-utils.tsx
- packages/auth/src/index.ts
- packages/fixtures/src/users.ts
- packages/model/src/user.ts
- packages/react-components/src/auth-test-utils.tsx
- packages/react-context/src/__tests__/auth.test.tsx
- packages/squidex/schema/schemas/users.json
- packages/squidex/src/entities/user.ts
First stage of https://trello.com/c/CyzhVfx5/1299-8-add-user-state-to-cms-and-block-api-calls
Adds the `onboarded` flag to the `User`. Once the migration is run and all the existing as well as new users have got the flag set to `true` we can then implement the auth rule to reject the ones with a `false` value
* adds a modification to auth0 rule which needs to be manually deployed
> feat: Add user onboarded state

- apps/asap-cli/src/invite/index.ts
- apps/asap-cli/test/invite.test.ts
Fixes the bug with team pagination - the number of teams for each user should be fixed - this PR sets it to maximum 20.
> fix: Team pagination bug

- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/entities/user.ts
- apps/asap-server/test/controllers/users.test.ts
Fixes the bug whereby even non-onboarded users are shown as onboarded. 
The fix adds the property to the graphql query and also adds proper boolean defaulting
Without proper integration testing the missing query parameter would be impossible to trace with our current unit tests
> fix: Onboarded always shown as 'true'

- apps/asap-server/.eslintrc.js
- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/entities/research-output.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/research-output.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- packages/squidex/schema/schemas/external-authors.json
- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/src/entities/common.ts
- packages/squidex/src/entities/external-author.ts
- packages/squidex/src/entities/research-output.ts
- packages/squidex/src/entities/user.ts
Creates a new external-authors entity and modifies the research-output author list to point to the new entity as well as existing user entity.
This then enables us to apply a custom order the author list being a mix of users and external authors
see: https://trello.com/c/60v7kM95/1334-list-of-ordered-authors-external-authors-users
> feat: Create external-authors/authors mixed relationship for ROs

- packages/react-components/src/templates/BiographyModal.tsx
- packages/react-components/src/templates/OpenQuestionsModal.tsx
- packages/react-components/src/templates/__tests__/OpenQuestionsModal.test.tsx
This PR introduces the following changes:
- The first and second questions on Open Questions Modal are now required
- Both have new custom error messages
- Add custom error message to Biography textArea on it's editing modal
> feat: update required fields on OpenQuestions and Biography modals

- packages/squidex/schema/schemas/events.json
- packages/squidex/schema/schemas/external-authors.json
- packages/squidex/schema/schemas/labs.json
- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/schema/schemas/teams.json
- packages/squidex/schema/schemas/users.json
- packages/squidex/src/entities/research-output.ts
Removes external-authors legacy field in favour of the joint `authors` field.
Also includes the following changes to the schema:
* Events - new fields in references: title, startDate; new fields in lists: startDate
* External Authors - new fields in references: name, orcid; new fields in lists: name, orcid
* Labs - new fields in references: name, new fields in lists: name
* Research Outputs - editor for labs changed from List to Tags
* Teams - new fields in lists: displayName
* Users - new fields in references: firstName, lastName, orcid, removed from references: email, new fields in lists: firstName, lastName, orcid, removed from lists: email, meta.id, editor for labs changed from List to Tags
> feat: Remove external authors legacy

- apps/storybook/src/LabeledTextField.stories.tsx
- packages/react-components/src/atoms/TextField.tsx
- packages/react-components/src/atoms/__tests__/TextField.test.tsx
- packages/react-components/src/molecules/LabeledPasswordField.tsx
- packages/react-components/src/molecules/SearchField.tsx
- packages/react-components/src/molecules/__tests__/SearchField.test.tsx
The following changes were introduced:
- As discussed with @kmaid, we used the custom indicator of the text field input, and made it work for both the right and left sides concurrently, which wasn't the case before.
- The loading and validity check icons were removed, as requested by product.
- The Password field had to be updated to reflect the changes and use the new interface for the Text Field input.
(Requirements: https://trello.com/c/P6AT7U22/1120-add-a-custom-icon-for-x-on-all-search-bars)
> Updating TextField to support both right and left indicators

- apps/asap-server/src/app.ts
- apps/asap-server/test/routes/user.route.test.ts
Extends a global API payload limit to 10MB as per API Gateway limitation: https://docs.aws.amazon.com/apigateway/latest/developerguide/limits.html
see: https://trello.com/c/U5vpkDJP/1264-i-am-not-able-to-upload-a-new-profile-picture
> fix: Profile picture upload bug

- .github/workflows/env-teardown.yml
Disables the dry-run so that the index actually gets deleted when the environment is removed
> fix: Enable algolia index deletion on teardown

- apps/asap-server/src/controllers/events.ts
- apps/asap-server/src/controllers/groups.ts
- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/utils/instrumented-client.ts
- apps/asap-server/src/utils/types.ts
- apps/asap-server/test/controllers/events.test.ts
- apps/asap-server/test/controllers/groups.test.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/controllers/teams.test.ts
- apps/asap-server/test/controllers/users.test.ts
- apps/asap-server/test/handlers/webhooks/webhook-fetch-by-code.test.ts
- apps/asap-server/test/utils/instrumentation.test.ts
- packages/squidex/src/graphql.ts
Moves all query parameters in the graphql queries to Squidex into the dedicated `variables` section of the request body.
See: https://trello.com/c/Ahlq8rgV/1259-move-graphql-query-parameters-to-the-variables
> chore: Add vars to graphql queries

- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/schema/schemas/users.json
fixes:
* https://trello.com/c/7iVw9yZb/1445-%F0%9F%90%9B-bug-not-all-labs-are-showing-on-user-profiles-cms
* https://trello.com/c/zANJCbn7/1465-default-value-for-onboarding-is-false
> fix: Onboarded default state and lab editor type

- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/src/entities/research-output.ts
https://trello.com/c/wJMIFi2p/1397-store-rrid-for-each-roms-output
no tests as there is not much point of writing any for just the CMS work - i expect integration tests to be added once the field is surfaced to the FE
> feat: Add RRID to research outputs

- packages/react-components/src/atoms/Anchor.tsx
- packages/react-components/src/atoms/Link.tsx
https://trello.com/c/gWaDbP7V/880-as-a-user-i-want-to-better-identify-links-states-hover-visited-clicked
- hover: dark green and underline
- active: light green
> fix: link styles

- packages/react-components/src/atoms/Link.tsx
Link underlines keeps on hover, and hides on active 
https://trello.com/c/gWaDbP7V/880-as-a-user-i-want-to-better-identify-links-states-hover-visited-clicked
> fix: revert link underline

- apps/asap-server/src/controllers/groups.ts
- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
After the team outputs have been removed from group response (see: https://github.com/yldio/asap-hub/pull/931) this PR removes the outputs from the request to the data store (squidex) as the data is no longer used.
> feat: Remove team outputs from group request

- ci/.gitlab-ci.integration.yml
So we don't exceed docker hub rate limits
> Revert docker build --no-cache --pull

- packages/react-components/src/templates/UserProfileResearch.tsx
https://trello.com/c/zwz0Rnto/1504-move-groups-section-down-on-profile-page
> Moving groups section down on profile page

- apps/asap-server/src/entities/team.ts
- apps/asap-server/test/controllers/teams.test.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
https://trello.com/c/gtCgc4QV/1548-stop-showing-private-team-tab-team-workspace
Hotfix to stop returning tools alltogether so nobody has a team workspace. Follow up to put in the logic to only return tools for your own teams and TESTS to follow.
> Hotfix: tools

- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/src/entities/team.ts
- apps/asap-server/src/routes/teams.route.ts
- apps/asap-server/test/controllers/teams.test.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- apps/asap-server/test/routes/teams.route.test.ts
see: https://trello.com/c/ehQe5myf/1547-private-team-tab-team-workspace-is-being-exposed-to-all-users
This PR moves the auth logic to the route layer keeping the controller libraries unaware of the logged-user state.
> fix: Hide tools and non-onboarded users

- apps/asap-server/src/utils/sync-google-event.ts
- apps/asap-server/test/utils/sync-google-event.test.ts
see: https://trello.com/c/u0fsA81Z/1383-new-cancelled-events-should-be-hidden-by-default
> feat: Mark new events as hidden when the status is: cancelled

- .gitlab-ci.yml
https://trello.com/c/8trOLvTW/1522-separate-squidex-import-from-the-sls-deploy-to-speed-up-the-pipeline
> fix: Separate the Squidex app creation and data import into a new job

- packages/squidex/schema/schemas/calendars.json
Re: https://trello.com/c/uTXT3Crm/1412-manage-events-that-belong-to-multiple-calendars
Should go before: https://github.com/yldio/asap-hub/pull/1034
> chore: Add google id column to calendar schema

- apps/asap-server/src/handlers/calendar/subscribe-handler.ts
- apps/asap-server/test/handlers/calendar/subscribe-handler.test.ts
Changes the subscription handler to return an error message and never throw - this is because we don't want the eventbridge to retry the subscription.
> feat: Do not throw on subscription failure

- serverless.ts
fixes https://trello.com/c/QjGxpJW1/1579-environment-teardown-does-not-work
Replace the `aws:region` and `aws:accountId` references which do not work in teardown command with an old syntax.
> fix: Teardown job

- apps/asap-server/src/config.ts
- apps/asap-server/src/gql/graphql.ts
- apps/asap-server/src/utils/send-email.ts
- apps/asap-server/test/utils/send-email.test.ts
- serverless.ts
see: https://trello.com/c/Oi7Y6kTL/1369-forward-invitation-email-bounce-must
Adds a `return-to` parameter to the send-email function call which, in case of an email bounce, is automatically used for forwarding the bounced email. 
Requires a manual step of activating e-mail feedback forwarding in both SES regions we use (done)
> feat: Forward invitation e-mail bounce

- serverless.ts
Last stage of user invitation automation - points prod handler to a regular SES box (not the sandbox).
see: https://trello.com/c/fE09MwLN/1481-2-automatically-send-invitation-after-user-creation-must
> feat: Automate user invitation - production ready

- apps/frontend/src/network/users/__tests__/UserProfile.test.tsx
- apps/storybook/src/LabeledDropdown.stories.tsx
- packages/react-components/src/atoms/Dropdown.tsx
- packages/react-components/src/atoms/__tests__/Dropdown.test.tsx
- packages/react-components/src/molecules/__tests__/LabeledDropdown.test.tsx
- packages/react-components/src/select.ts
- packages/react-components/src/templates/PersonalInfoModal.tsx
- packages/react-components/src/templates/__tests__/PersonalInfoModal.test.tsx
- packages/react-components/src/templates/__tests__/TeamMembershipModal.test.tsx
- packages/squidex/schema/rules/rule4.json
https://trello.com/c/27dUYTjL/1566-disable-custom-values-for-country-only-accept-allowed-values
- Updates Personal Info Modal, so the country selector only allow the selection of valid values
- Updates Dropdown component to support validation
> feat: extends dropdown component

- apps/asap-server/src/utils/squidex.ts
- apps/asap-server/test/controllers/users.test.ts
Replace the native escape function with a custom sanitisation function for odata support
see: https://trello.com/c/IHU7bWU2/1525-search-does-not-work-on-terms-with-odd-characters-such-as-%C3%A8
> fix: User search with special characters

- packages/react-components/src/organisms/SharedResearchListCard.tsx
https://trello.com/c/rOxG5SsX/1357-too-much-padding-on-list-view-shared-outputs
> Fix: Remove paddings and gap in list view

- apps/frontend/src/network/groups/GroupProfile.tsx
- apps/frontend/src/network/groups/events/__tests__/api.test.ts
- apps/frontend/src/network/groups/events/api.ts
https://trello.com/c/yV4Vgd1N/1744-past-events-are-sorted-in-reverse-order-in-group-pages
> Fix: group past events order

- apps/frontend/src/structure/ErrorBoundary.tsx
- apps/frontend/src/structure/Frame.tsx
- apps/frontend/src/structure/__tests__/ErrorBoundary.test.tsx
https://trello.com/c/DfezNKBy/1739-change-error-boundaries-to-report-into-sentry
See https://sentry.io/organizations/yld/issues/2848318280/?referrer=slack
https://sentry.io/organizations/yld/issues/2848318280/?project=5893160
> fix: set sentry error boundary as default

- .gitlab-ci.yml
- ci/.gitlab-ci.integration.yml
- ci/.gitlab-ci.ses.yml
In this PR we are speeding up the development and production pipeline. This has been done by having the schema sync occur at the same time as the sls deploy. 
We have also moved all build steps to the start of the build. We have done this by turning our PR deployment jobs into a template and extending these templates with the environment specific configuration.
We have removed the needs condition in favour of using the default gitlab behaviour of having all prior stages jobs successfully completed to try and simplify the configuration
> Feat: Speedup production pipeline

- .gitlab-ci.yml
Move Prod builds to later stage to avoid concurrent same enviroment builds occuring and avoid blocking the dev pipeline
> Fix: Move prod build jobs to new stage

- apps/asap-server/src/gql/graphql.ts
- apps/asap-server/src/schema/schema.graphql
- packages/squidex/schema/schemas/groups.json
https://trello.com/c/HhKZss3v/1781-admins-can-mark-groups-as-inactive-and-omit-them-from-calendars-page
Once its merged all groups should be marked as active or inactive as a way to migrate the missing data which is now going to be required.
> feat: Mark group as inactive

- ci/algolia-schema.json
https://trello.com/c/kALPxvWV/1850-sort-algolia-listings-when-no-search-has-been-performed
> When searches are equal relevance show newer outputs first

- .gitlab-ci.yml
- packages/flags/src/__tests__/index.test.ts
- packages/flags/src/index.ts
In 87312e7eeb54abe64e8c36d82fbdfc85c47d033a `yarn run build` was removed from the `deploy:sls:production` job. Running `yarn run build` would override the build artifact created in the `build:ts:prod` step.
This change adds NODE_ENV production to the `build:ts` step.
Note that the frontend would build in production by default because of react-scripts. It is important to run `yarn run build:babel` using `NODE_ENV=production`
> CRN-648 Feature flags not working as expected in production

- apps/crn-frontend/src/__fixtures__/algolia.ts
- apps/crn-frontend/src/network/teams/__tests__/TeamOutput.test.tsx
- apps/crn-frontend/src/network/teams/state.ts
- apps/crn-frontend/src/network/users/__mocks__/api.ts
- apps/crn-frontend/src/network/users/__tests__/api.test.ts
- apps/crn-frontend/src/network/users/api.ts
- apps/crn-frontend/src/shared-research/__tests__/api.test.ts
- apps/crn-frontend/src/shared-research/__tests__/export.test.ts
- apps/crn-frontend/src/shared-research/api.ts
- apps/crn-server/test/mocks/algolia-client.mock.ts
- packages/algolia/src/client.ts
- packages/algolia/test/client.test.ts
- packages/react-components/src/organisms/TeamCreateOutputContributorsCard.tsx
- on the Share an Output form, in the author selector, show items which can be either users or external authors 
- display  external authors differently from users:
- external authors 's names should be followed by “(Non CRN)”
- be able to select from at least 3 existing external authors 
- search what is typed on the author selector against these fields only:
- display name of  external authors 
- first name of  users 
- last name of users 
- when user clicks "Share", all users and external authors   selected must be added to the "Authors" field on the CMS
- the order of users and external authors must be remembered
- when user clicks "Share", this field must become disabled (as the page is saving)
- testing strategy: on the FE, it will be possible to find and select those  external …
> CRN-682 Search across users and external authors

- apps/crn-server/src/validation/research-output.validation.ts
- packages/model/src/research-output.ts
- packages/react-components/src/organisms/TeamCreateOutputExtraInformationCard.tsx
- packages/react-components/src/organisms/TeamCreateOutputForm.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputExtraInformationCard.test.tsx
As a user sharing an output that is hard to access
I want to explain to others how to access that output 
so that I comply with ASAP guidelines
- add a new input field on the Share an Output form, on the second section, after additional keywords and after identifiers (if already done)
- Label: Access instructions
- This field is optional
- This is a text input field similar to “Description”
- Save changes to accessInstructions on the CMS
- Please include a place holder as per the designs
- this is currently RTF on the CMS
- it would be nice to accept hyperlinks in the future
> CRN-693 Add access instructions

- apps/crn-server/src/validation/index.ts
- apps/crn-server/test/routes/user.route.test.ts
Fixes the bug whereby a single query string parameter for the array type filter is rejected by enabling coercion to an array.
> fix: CRN-768 Single team role filter

- apps/crn-frontend/src/network/teams/TeamOutput.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamOutput.test.tsx
- apps/crn-frontend/src/network/teams/state.ts
- apps/storybook/src/LabeledMultiSelect.stories.tsx
- apps/storybook/src/TeamCreateOutputExtraInformationCard.stories.tsx
- apps/storybook/src/TeamCreateOutputForm.stories.tsx
- apps/storybook/src/TeamCreateOutputPage.stories.tsx
- packages/react-components/src/atoms/MultiSelect.tsx
- packages/react-components/src/atoms/__tests__/MultiSelect.test.tsx
- packages/react-components/src/atoms/index.ts
- packages/react-components/src/molecules/LabeledMultiSelect.tsx
- packages/react-components/src/molecules/__tests__/LabeledMultiSelect.test.tsx
- packages/react-components/src/organisms/AuthorSelect.tsx
- packages/react-components/src/organisms/TeamCreateOutputContributorsCard.tsx
- packages/react-components/src/organisms/__tests__/AuthorSelect.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputContributorCard.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputContributorsCard.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputExtraInformationCard.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputForm.test.tsx
- packages/react-components/src/select.ts
- packages/react-components/src/templates/ExpertiseAndResourcesModal.tsx
As a Product Owner
I want to see the appropriate avatar displayed on author selector function of the shared outputs form
So that I am able to visually identify tag labels
- This behaviour should apply to the ‘Author’ selector on the Shared Outputs form; all other instances of this component should remain unchanged.
- The Avatar should be 24x24 px in a circle - it should be spaced 8px before the tag label 
- Update the component multi-select to display an avatar image with each option (including: those tags that are selected AND those tags that are to be selected)
- for each option on the results list of the user search (i.e. drop-down), show an avatar to the left:
- for each selected option (i.e. in the input text area), show the avatar inside the tag pill on the left
- The avatar should …
> CRN-767 Show Avatars in the user selector

- apps/crn-server/src/controllers/research-outputs.ts
- apps/crn-server/test/controllers/research-outputs.test.ts
- When the URL and Title is duplicate, I would like to see the error messages for URL and Title at the same time.
- On the backend we only want to check for uniqueness of the unique fields at the same time.
> CRN-803 URL/Title error to be display simultaneously

- apps/crn-server/src/autogenerated-gql/graphql.ts
- apps/crn-server/src/schema/autogenerated-schema.graphql
- packages/squidex/schema/schemas/events.json
- To add speakers to Events in the CMS (users will be able to add ‘user' and ‘team’ via popup (see 'Users > Teams' nested field in CMS, this will include team and user instead of ID and role)
- The CMS should be built in a way that allows the user/event creator to move the list of users/team in the specific order that they would like to display the output on the FE (User would like the ability to order speakers in the CMS, for display on the FE )
- Team is required, User is optional
- The role would be inferred based on the team/user (i.e. role will be as at the time of the event and cannot be changed)
> CRN-844 Add speaker to events in the CMS

- apps/crn-frontend/src/network/teams/__tests__/TeamOutput.test.tsx
- packages/model/src/research-output.ts
- packages/react-components/src/organisms/TeamCreateOutputForm.tsx
- packages/react-components/src/organisms/TeamCreateOutputIdentifier.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputForm.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputIdentifier.test.tsx
- packages/validation/src/research-output.ts
https://asaphub.atlassian.net/jira/software/c/projects/CRN/boards/8?modal=detail&selectedIssue=CRN-802
1/When I land on the RO form, and navigate to the identifier field I do not want to see a default option of ‘None’ populated in the field. This should have a place holder ‘Choose an identifier’.
2/If I select ‘ASAP Fund' and ‘Used in a publication ' (radio buttons), then I want to remove ‘None’ from the drop down options AND I do not want to populate the field with a default of 'DOI’. DOI and Accession number should be available as options in the list (NO DEFAULTS) pre-populated
image
> CRN-802 identifier field defaults

- packages/react-components/src/organisms/__tests__/TeamCreateOutputForm.test.tsx
Due to known bug in the test we have decided to increase the timeout to 60s
> Increase timeout to 60s in TeamCreateOutputForm test

- apps/crn-frontend/src/dashboard/__tests__/Dashboard.test.tsx
- apps/crn-server/src/controllers/news.ts
- apps/crn-server/src/migrations/1662632124-move-trainings-to-tutorial.ts
- apps/crn-server/test/controllers/news.test.ts
- apps/crn-server/test/fixtures/dashboard.fixtures.ts
- apps/crn-server/test/fixtures/news.fixtures.ts
- apps/gp2-frontend/src/dashboard/__tests__/Dashboard.test.tsx
- apps/gp2-server/test/fixtures/dashboard.fixtures.ts
- apps/storybook/src/DashboardPageBody.stories.tsx
- apps/storybook/src/NewsCard.stories.tsx
- packages/fixtures/src/dashboard.ts
- packages/gp2-components/src/templates/__tests__/DashboardPageBody.test.tsx
- packages/model/src/news.ts
- packages/react-components/src/organisms/NewsCard.tsx
- packages/react-components/src/templates/__tests__/DashboardPageBody.test.tsx
- packages/squidex/schema/crn/schemas/news.json
- packages/squidex/src/entities/crn/news.ts
* Removes the Event news type (requires manual data removal)
* Adds a migration to map Training news type into a Tutorial news type
> feat: Remove redundant references in News

- apps/crn-server/src/data-providers/news.data-provider.ts
- apps/crn-server/test/data-providers/news.data-provider.test.ts
Since we moved all news of type `Tutorial` from `News` to `Tutorials` in squidex, we don't need to filter the news that have type `Tutorial` from news anymore. This PR removes this condition.
> CRN-1124 Remove tutorials from news query condition

- packages/squidex/schema/crn/schemas/news-and-events.json
This PR removes `Tutorial` from allowed values for type in News in squidex
Before          |  After
> CRN-1124 Removing Tutorials from allowed type values  in News

- packages/squidex/schema/crn/schemas/tutorials.json
Important note: the field editing type still needs to be manually updated through the UI
> fix: Tutorial text field

- packages/react-components/src/templates/WorkingGroupHeader.tsx
- packages/react-components/src/templates/__tests__/WorkingGroupHeader.test.tsx
After making the `About` tab as default https://github.com/yldio/asap-hub/pull/2317, the scroll to members section when the user clicks +n button stopped working. This PR fixes it.
> CRN-1226 Fix scroll to members section in Working Groups Header

- packages/react-components/src/organisms/WorkingGroupMembers.tsx
- packages/react-components/src/organisms/__tests__/WorkingGroupMembers.test.tsx
- packages/react-components/src/templates/WorkingGroupAbout.tsx
- packages/react-components/src/templates/__tests__/WorkingGroupAbout.test.tsx
Where a WG is in Complete status:
- the Past Leaders tab should be displayed as default 
- The Active Leaders tab should be inactive with a total of zero #0 leaders 
- All users of the WG should be displayed in the past tab, for both leaders and members
- Any Alumni users should be displayed with the correct badge
- Any Inactive teams should be displayed with the correct badge (if implemented) **[which is not]**
> [CRN-1147] handle complete working groups in members tabs

- .github/actions/setup-environment/action.yml
- .github/environment/Base
- .github/environment/Development
- .github/scripts/contentful/teardown.sh
- .github/workflows/on-remove.yml
- Introduces the PR number check same as Squidex & other teardowns;
- Doesn't run the whole suite of checks, just checks if env exists.
- Create a contentful environment called `crn-5000` in Contentful UI;
- Run the workflow from Actions > Remove Environment;
- Pick this branch and put PR number to destroy as 5000;
- Observe that the Contentful environment is destroyed.
- [Environment exists & is deleted](https://github.com/yldio/asap-hub/actions/runs/3767140161/jobs/6404384767)
- [No environment exists, nothing to delete](https://github.com/yldio/asap-hub/actions/runs/3767153273/jobs/6404412444)
Ignore failures on removing SLS, I am targeting a PR that doesn't exist and the remove SLS step errors when removing PR that doesn't exist.
> CRN-1215 | Decommission Contentful Environment Correctly on Teardown

- packages/flags/src/index.ts
- packages/react-components/src/templates/NetworkPageHeader.tsx
- packages/react-components/src/templates/__tests__/NetworkPageHeader.test.tsx
This PR undoes the changes made in https://github.com/yldio/asap-hub/pull/2334
> CRN-1223 Removing Working Groups feature flag in Networks

- apps/crn-server/src/migrations/1673349371-remove-working-groups-from-news.ts
This PR introduces a migration that deletes the News that have type `Working Groups`.
I've ran the script in the PR env:
And I could verify that there isn't any News with type `Working Groups` now:
> CRN-1246 Migration to delete working groups from news

- apps/crn-server/src/migrations/1673349371-remove-working-groups-from-news.ts
After this commit [CRN-1247 Adjust news entity to remove working groups references](https://github.com/yldio/asap-hub/commit/a77fc415e59d171c94bb1fc9654f177fa3ba269b) the remove working groups from news migration is giving the error below
We could either delete this migration because it will never be run again, but another option is to ignore this TS check in this specific line so we can run `yarn build:typecheck` without problems.
> Fix: TS issue in remove working groups from news migration

- packages/squidex/schema/crn/schemas/news-and-events.json
The field `type` was removed from `fields` but not from `fieldsInLists` in `packages/squidex/schema/crn/schemas/news-and-events.json` in https://github.com/yldio/asap-hub/pull/2442.
So the schema was being created with `type` and this gives a schema error when running `yarn schema:update:crn`
> Fix: remove type from News

- packages/squidex/schema/crn/schemas/research-outputs.json
In [CRN-995 Add New Type to Protocol shared output form](https://github.com/yldio/asap-hub/pull/2454) I forgot to add `Sequencing` in the `Type` allowed values. 
This is causing a validation error when we try to publish a shared output with this type.
So in this PR I am adding `Sequencing` to the allowed values in the file that creates the new env in squidex.
> CRN-1276 Fix: Validation error when choosing Sequency type in Research Output

- @types/contentful-html-rich-text-converter/index.d.ts
- packages/cms-data-sync/src/utils/assets.ts
- packages/cms-data-sync/src/utils/rich-text.ts
- packages/cms-data-sync/test/utils/assets.test.ts
It's possible to remove the function `getAssetId` without having duplication problem because the payload from `parseAssets` comes with the `id` so we can check in contentful if that id already exists and in the fork the generated id is always the same given the asset url.
> fix(cms-migration): asset with id null

- packages/react-components/src/organisms/RichText.tsx
- packages/react-components/src/organisms/__tests__/RichText.test.tsx
RichText component would display an error like the one below when we have tags `i` or `b` inside `a`.
This PR makes it possible to render the variations below:
---
This also fixes the color of `<b>` tag
> CRN-1313 Display <a> with nested <i>/<b> & Fix color of <b>

- packages/react-components/src/__tests__/text.test.ts
- packages/react-components/src/organisms/__tests__/RichText.test.tsx
- packages/react-components/src/text.ts
RichText did not support nested `<b>` inside headings 1,2,3 the way it comes from contentful
---
After the fix
> CRN-1333 Fix Heading style errors

- packages/react-components/src/organisms/RichText.tsx
- packages/react-components/src/organisms/__tests__/RichText.test.tsx
> CRN-1337 RichText component renders underline

- apps/crn-server/src/app.ts
- apps/crn-server/src/utils/should-handle-error.ts
- apps/crn-server/test/middleware/sentry-error-handler.test.ts
- apps/crn-server/test/utils/should-handle-error.test.ts
- packages/server-common/src/middleware/auth-handler.ts
- packages/server-common/test/middleware/auth-handler.test.ts
Override Sentry's default `shouldHandleError` function as `got` and our own Errors class do not match what Sentry is expecting so error are not being reported.
1. Login to  https://2656.hub.asap.science
2. Change lambda env var  `SQUIDEX_BASE_URL=http://httpstat.us/500
3. Navigate to any page on the site e.g https://2656.hub.asap.science/network/working-groups/1d87a6f5-94e6-4ae6-89dc-c12d2e591dec/about
4. Check sentry for report error
> fix(crn-server): sending errors to sentry

- packages/contentful/migrations/pages/20230307163242-text-enabled-node-types.js
In the last squidex-contentful migration run (https://github.com/yldio/asap-hub/actions/runs/4354930475/jobs/7612848718#step:6:777)
The page with id `77ac91b8-6919-4157-b461-aa404e44a3c3` could not be published. Taking a look at Contentful
I could see that the text was there but there was a validation problem. Looking at the Page schema in `Production` I saw that embeds were not allowed, that was causing the validation problem.
So this PR adds a migration to add 
```
'embedded-entry-block',
'embedded-entry-inline',
'embedded-asset-block',
```
to `enabledNodeTypes`.
> fix: Contentful Pages text field validation

- packages/react-components/src/organisms/Form.tsx
- packages/react-components/src/organisms/__tests__/Form.test.tsx
- packages/react-components/src/templates/ResearchOutputForm.tsx
Making `onSaveDraft` optional as `packages/gp2-components/src/templates/OutputForm.tsx` does not require this props.
github error: https://github.com/yldio/asap-hub/actions/runs/4363587990/jobs/7629920136#step:6:109
> fix: Save Draft type errors

- .github/actions/setup-environment/action.yml
This needs to be a defined output from the step or the downstream steps won't have it available.
> BUGFIX: Define output for contentful backup bucket in setup job

- apps/crn-frontend/src/network/users/__tests__/UserProfile.test.tsx
- apps/crn-frontend/src/shared-research/__tests__/Routes.test.tsx
- apps/crn-server/test/integration/research-outputs.integration-test.ts
- apps/crn-server/test/integration/teams.integration-test.ts
- apps/crn-server/test/integration/users.integration-test.ts
* Add wait/retry to all integration tests. There is a race condition with Squidex in the integration tests that is resolved with a wait/retry in the reminders tests, and should have been applied to the remaining tests as well.
* Extend timeout for UserProfile setup. This is failing sporadically with loading elements still appearing. Increase the default timeout from 1000ms to 5000ms to try to reduce failures.
> Address unstable tests

- apps/crn-frontend/extend-timeouts.js
- apps/crn-frontend/jest.config.js
- apps/crn-frontend/src/network/users/__tests__/UserProfile.test.tsx
- apps/crn-frontend/src/shared-research/__tests__/Routes.test.tsx
The previous changes were to add longer timeouts for tests which had recently failed, but setting a global point of config should make all tests more reliable and avoid the need to add inline overrides when particular tests fail.
> Remove inline timeout configuration for global config

- apps/crn-server/test/integration/reminders.integration-test.ts
This test was occasionally failing because the first fetch wasn't always returning results immediately. Move it inside the retry loop so that it can take a few seconds to resolve.
> Improvement: move fetch in events integration test inside retry loop

- .github/workflows/on-push-master.yml
It's giving an error because it does not have the value of environment id
which is passed as input in the on-demand sync action
> fix: algolia sync pipeline env var

- .github/workflows/on-push-master.yml
This var was renamed here https://github.com/yldio/asap-hub/blame/0d224391c6f0bb59b6ce110af8c79842d2e0c16c/.github/workflows/reusable-algolia-sync.yml#L20
so this `crn-contentful-env` is not needed
> fix(pipeline): algolia sync env var

- apps/crn-frontend/src/network/ProfileSwitch.tsx
- apps/crn-frontend/src/network/teams/TeamProfile.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- apps/crn-frontend/src/network/working-groups/WorkingGroupProfile.tsx
Thank you @gabiayako for the help you provided.
This bug would have also applied to working group once we enabled the outputs search bar there.
I initially tried keeping the functionality of ProfileSwitch as unchanged as possible, tried wrapping the OutputsComponent in a useCallback hook but this resulted in code coverage issues since team and working group could be undefined yet it's not allowed to have them undefined in the Outputs component. @kmaid I tried passing the team to the hook but it would still re-render that way.
Then I tried pulling them out of the Profile switch and just having the routs outside that component but it would mean having to control the Redirect.
> Crn 1359 team outputs search bar is not accepting words

- apps/asap-cli/package.json
- apps/crn-frontend/src/events/EventList.tsx
- apps/crn-frontend/src/events/__tests__/EventList.test.tsx
- apps/crn-frontend/src/events/api.ts
- apps/crn-frontend/src/events/state.ts
- apps/crn-frontend/src/hooks/__tests__/algolia.test.tsx
- apps/crn-frontend/src/hooks/algolia.ts
- apps/crn-frontend/src/network/teams/Outputs.tsx
- apps/crn-frontend/src/network/users/UserList.tsx
- apps/crn-frontend/src/network/users/__tests__/UserList.test.tsx
- apps/crn-frontend/src/network/users/api.ts
- apps/crn-frontend/src/network/users/state.ts
- apps/crn-frontend/src/network/working-groups/Outputs.tsx
- apps/crn-frontend/src/shared-research/ResearchOutputList.tsx
- apps/crn-frontend/src/shared-research/__tests__/ResearchOutputList.test.tsx
- apps/crn-frontend/src/shared-research/state.ts
- package.json
- packages/algolia/src/client.ts
- packages/algolia/src/index.ts
- packages/model/src/common.ts
- packages/react-components/src/atoms/AlgoliaHit.tsx
- packages/react-components/src/organisms/ResultList.tsx
- packages/react-components/src/organisms/SharedResearchListCard.tsx
- packages/react-components/src/organisms/__tests__/ResultList.test.tsx
- packages/react-components/src/templates/EventsList.tsx
- packages/react-components/src/templates/NetworkPeople.tsx
- packages/react-components/src/templates/ProfileOutputs.tsx
- packages/react-components/src/templates/SharedResearchList.tsx
This PR is to implement the website side of https://www.algolia.com/doc/guides/sending-events/connectors/google-tag-manager/
Algolia Client and GTM are both tagged with UserId so queries can be related to a user.
Result lists rendered from algolia data should be tagged with the index they were run on
- Events
- Users
- Research Outputs
Hits should be tagged with QueryId, Position and Object ID which is the same as our ID's 
I have written very high level unit tests to ensure tags are present on the relevant result lists to prevent regressions.
I have also refactored the algolia scripts to be within the algolia package.
> Improve Algolia search ranking & results

- apps/crn-server/src/data-providers/contentful/users.data-provider.ts
- apps/crn-server/test/data-providers/contentful/users.data-provider.test.ts
- packages/contentful/src/utils.ts
To prevent a race condition where the CDN cache in front of the graphql endpoint is not reloaded and so subsequent fetch responds with stale data.
> Add poll for version match in Contentful user update

- .github/workflows/reusable-test.yml
It's currently possible to push failing tests for app extensions which don't get detected until they hit master.
> Add testing of app extensions to main PR pipeline

- apps/crn-server/serverless.ts
- apps/crn-server/src/data-providers/contentful/users.data-provider.ts
- apps/crn-server/src/handlers/event/index-user-events-handler.ts
- apps/crn-server/src/handlers/user/index-handler.ts
- apps/crn-server/src/handlers/user/invite-handler.ts
- apps/crn-server/src/handlers/webhooks/fetch-by-code/handler.ts
- apps/crn-server/src/handlers/webhooks/webhook-connect-by-code.ts
- apps/crn-server/test/data-providers/contentful/users.data-provider.test.ts
- apps/crn-server/test/fixtures/users.fixtures.ts
- apps/gp2-server/src/handlers/user/invite-handler.ts
- packages/contentful/src/crn/types/webhook.ts
- packages/server-common/src/handlers/event-bus.ts
- packages/server-common/src/handlers/user/invite.handler.ts
- packages/server-common/test/fixtures/users.fixtures.ts
- packages/server-common/test/handlers/user/invite.handler.test.ts
* Updates invite handler factory function to use a data provider instance in place of the Squidex client to allow data provider agnostic invitation pipelines.
* Updates webhook handlers to use `resourceId` for accessing entity IDs
* Updates CRN user data provider to support setting connection codes
* Updates invite handler to never send invitation if there is any connection code attached to the profile to prevent repeat invitations being sent to users when publishing profile updates
> Add support for Contentful invitation/onboarding journey

- .github/workflows/on-push-app-extensions.yml
Currently the contentful apps are only deployed if the source code for the app changes, but if the deployment workflows are changed thn they also need to re-deploy.
> Re-deploy contentful apps if deployment script/config changes

- .github/actions/setup-environment/action.yml
This was missed in the previous refactor of Contentful App deployments.
> Add Github Actions setup output for user teams app

- .github/actions/setup-environment/action.yml
- .github/environment/Base
- .github/workflows/on-push-app-extensions.yml
- apps/crn-server/serverless.ts
- apps/crn-server/src/handlers/event-bus.ts
- apps/crn-server/src/handlers/user/sync-orcid-handler.ts
- apps/crn-server/src/handlers/webhooks/cronjob-sync-orcid.ts
- apps/crn-server/test/fixtures/users.fixtures.ts
- apps/crn-server/test/handlers/user/sync-orcid-handler.test.ts
- packages/contentful-app-extensions/README.md
- packages/contentful-app-extensions/clear-on-change/package.json
- packages/contentful-app-extensions/clear-on-change/public/index.html
- packages/contentful-app-extensions/clear-on-change/src/App.tsx
- packages/contentful-app-extensions/clear-on-change/src/index.tsx
- packages/contentful-app-extensions/clear-on-change/src/locations/Field.tsx
- packages/contentful-app-extensions/clear-on-change/src/react-app-env.d.ts
- packages/contentful-app-extensions/clear-on-change/src/test/locations/Field.test.tsx
- packages/contentful-app-extensions/clear-on-change/tsconfig.json
- packages/squidex/schema/crn/schemas/users.json
- yarn.lock
- refactor sync orcid handler
- add contentful handler to serverless
- adds a clear-on-change Contentful app which resets a field based on a change to another field. 
--> In our case we reset the orcidLastSyncDate when the orcid field is modified, which is how we tell our webhook to sync it.
What is missing here is the migration to alter the orcidLastSyncDate to use the extension but that will be done through a follow-up PR, it's testable within this PR though as it can be manually cleared to trigger the sync
> feat: CT-38 Enable ORCID sync for Contentful

- .github/actions/contentful-create-environment/action.yml
To debug some odd failures where it reports using more environments than we seem to actually be using.
> Output the currently used environments in Contentful

- packages/contentful/migrations/crn/events/20230511122400-event-speaker-controls.js
- packages/contentful/migrations/crn/users/20230511122800-user-team-control.js
- packages/contentful/src/crn/autogenerated-gql/graphql.ts
- packages/contentful/src/crn/schema/autogenerated-schema.graphql
Modifies the field controls on the events->speakers and users->teams fields to use the newly created app extensions for showing second-order linked entities.
> Contentful: Add migration to events and users to use new app extensions

- apps/gp2-server/src/data-providers/contentful/user.data-provider.ts
- apps/gp2-server/test/data-providers/contentful/user.data-provider.test.ts
- FIxes error when fetching user related to an orphaned working group
Steps to reproduce:
- Associate user to working group
- Delete working group
- Try to load the user details
> fixes user orphaned working groups

- packages/cms-data-sync/test/events/events.data-migration.test.ts
In this test `createEntry` will be called 2 times with the speakers from this fixture https://github.com/yldio/asap-hub/blob/master/packages/cms-data-sync/test/events/events.data-migration.test.ts#L70:L93
```
speakers: [
{
team: [
{
id: 'team-1',
},
],
user: [
{
__typename: 'Users',
id: 'user-1',
},
],
},
{
team: null,
user: [
{
__typename: 'ExternalAuthors',
id: 'external-user-1',
},
],
},
],
```
But I believe we can't guarantee the order that these two will come and I couldn't find a way to test using some variation of `toHaveBeenCalledWith` without pointing the order. So I'm removing theses expects.
> fix: remove event-migration expects that can vary the order

- apps/crn-server/test/data-providers/working-groups.data-provider.test.ts
- packages/model/src/working-group.ts
The update method on Working Group Data Provider was added here https://github.com/yldio/asap-hub/pull/2703/files. The idea was to update `deliverables` and this is the only use case for update so far.
Since we are implementing Contentful's data providers now, I think it would be better to enforce the properties that can be updated in the data provider. If we update other things like calendar, leaders or members it would be necessary to check if this calendar/user exists and create a link to update the entry, it's not a "plain" payload like passing ids. So since there isn't a use case where these properties are updated, I believe we could remove then from `WorkingGroupUpdateDataObject`.
> refactor: working group update type

- apps/crn-server/serverless.ts
- apps/crn-server/src/dependencies/working-groups.dependencies.ts
- apps/crn-server/src/handlers/event-bus.ts
- apps/crn-server/src/handlers/working-group/update-deliverables-handler.ts
- apps/crn-server/test/dependencies/working-groups.dependencies.test.ts
- apps/crn-server/test/fixtures/working-groups.fixtures.ts
- apps/crn-server/test/handlers/working-group/update-deliverables-handler.test.ts
- packages/contentful/src/crn/types/webhook.ts
This PR updates the handler `update-deliverables-handler` so it is able to process events from squidex and contentful and update the deliverables from working groups.
Testing:
- Create a working group in Contentful with 
- complete equals false
- a deliverable with status `Pending`
- a deliverable with status `In progress`
- Publish this working group entry
- Change the complete to true and publish the entry again
- Check that the deliverables are now with status `Not started` and `Incomplete` respectively
> CT-17 Working Groups webhook

- packages/cms-data-sync/src/index.ts
- packages/cms-data-sync/src/run-migrations.ts
- packages/cms-data-sync/test/run-migrations.test.ts
Most of the time when working on a migration you are only interested in migrating the one entity type that you're working on. This provides a quick way to selectively migrate only one model type without having to comment out lots of code.
Omitting any flags defaults to migrating everything.
Example:
```
yarn workspace @asap-hub/cms-data-sync migrate --teams
```
```
yarn workspace @asap-hub/cms-data-sync migrate --teams --users
```
> Add flags to make migrations optional

- .github/workflows/on-demand-calendar-sync.yml
- apps/crn-server/src/handlers/calendar/resubscribe-handler.ts
- apps/crn-server/src/handlers/calendar/subscribe-handler.ts
- apps/crn-server/src/utils/get-calendar-subscription-id.ts
- apps/crn-server/test/utils/get-calendar-subscription-id.test.ts
- packages/cms-data-sync/src/calendars/sync-all.ts
- packages/cms-data-sync/test/calendars/sync-all.test.ts
- packages/server-common/src/handlers/calendar/calendar-handler-factory.contentful.ts
- packages/server-common/test/handlers/calendar/calendar-handler-factory.contentful.test.ts
- packages/server-common/test/handlers/calendar/resubscribe-calendars.test.ts
This PR includes
- refactor calendar subscription id to include contentful environment name. This is to prevent getting 'not unique id error' when subscribing to events.
- fix action environment to have contentful enabled so the script to uses contentful calendar data provider
- refactor sync-all action to update `googlemetadata.associatedGoogleCalendarId` and retain previous data to trigger calendar change handler
> refactor: sync all calendar github action

- packages/contentful/src/crn/autogenerated-gql/graphql.ts
- packages/contentful/src/crn/schema/autogenerated-schema.graphql
- packages/contentful/src/gp2/autogenerated-gql/graphql.ts
- packages/contentful/src/gp2/schema/autogenerated-schema.graphql
I believe the schema has changed without any intervention from us due to this [GraphQL Content API improvement](https://www.contentful.com/developers/changelog/?utm_source=rss&utm_medium=link&utm_campaign=documentation-discovery#graphql-content-api-improvement). So I'm just updating it for CRN and GP2.
> fix: contentful crn+gp2 schemas

- packages/contentful-app-extensions/clear-on-change/tsconfig.json
- packages/contentful-app-extensions/disabled-fields/tsconfig.json
- packages/contentful-app-extensions/event-additional-materials/tsconfig.json
- packages/contentful-app-extensions/event-speakers-title/tsconfig.json
- packages/contentful-app-extensions/field-as-updated-at/tsconfig.json
- packages/contentful-app-extensions/user-positions/tsconfig.json
- packages/contentful-app-extensions/user-team-memberships/tsconfig.json
- scripts/get-composite-ts-projects.js
Contentful apps are now listed in the workspaces to be type checked in the [Definitions](https://github.com/yldio/asap-hub/actions/runs/5289058234/jobs/9571560053) build step.
> Include Contentful apps in typescript build list

- apps/crn-server/src/data-providers/contentful/teams.data-provider.ts
- apps/crn-server/test/data-providers/contentful/teams.data-provider.test.ts
The purpose of this ticket initially was to clear tools that were unlinked to Teams, but I've noticed that there was a bug in the team data provider update method: when we add a new tool and the field is populated already we shouldn't unlink the existing ones, we should add it to the list of tools linked to the Team, at least this is what happens in squidex.
So in the end, we don't need to clear the unlined tools because there shouldn't be tools unlinked. So this PR only fixes the behavior of adding the new tool to the existing tools link array.
> CT-50 Team tool update

- packages/contentful-app-extensions/field-as-updated-at/src/locations/Field.tsx
- packages/contentful-app-extensions/field-as-updated-at/src/test/locations/Field.test.tsx
Without the `sdk.field.setValue` the value does not get saved in the entry. It only gets displayed in Contentful but it does not come in the entry response when we fetch it.
> fix: field-as-updated-at contentful app extension

- apps/crn-server/src/validation/research-output.validation.ts
- apps/crn-server/test/routes/research-outputs.route.test.ts
Currently if the `published` property is not passed to the server when creating a research output then the research output is created as published irrespective of whether the user actually has permissions or not.
This is because the [validation of permissions](https://github.com/yldio/asap-hub/blob/master/packages/validation/src/permissions/research-output.ts#L61) only checks for a falsy value, so when `published` is  `undefined` it assumes at that point it is creating a draft, but then the data provider defaults the value to `true`, so the draft-like submission is created as published.
Fix by:
* adding `published` to the validation schema to ensure it is passed by the client and cannot be `undefined`
* ~default to `false` in the data provider~
> Require published flag on research output payload

- .github/workflows/on-remove.yml
The script was moved into a package.json script for consistency with the environment creation, but this instance was not changed.
Update to use the correct command.
> Fix Contentful teardown

- jest.config.js
We occasionally get test timeouts in React component tests with the default 5000ms timeout, to which the "solution" is generally to simply brute force the test by restarting.
Increase timeout to 10000ms to allow these to run reliably.
> Increase default test timeout

- packages/react-components/src/organisms/ResearchOutputFormSharingCard.tsx
The round and square brackets were the wrong way round in the markdown instructions.
> Fix markdown link instructions

- .github/workflows/reusable-test.yml
- apps/crn-server/test/integration/common/reminders.integration-test.ts
- apps/crn-server/test/integration/fixtures/contentful.ts
- apps/crn-server/test/integration/fixtures/squidex.ts
* Add a concurrency group to contentful tests to limit to a single run in progress
* Don't bother tearing down data created in the test run in CI where the environment is deleted anyway
* Don't mock `clearTimeout` because we don't rely on it in tests, but it _might_ interfere with the working of `async-retry`
* Reduce absurdly long timeout to only be _very_ long
> Optimise integration tests in CI to avoid rate limiting

- apps/crn-server/src/data-providers/contentful/research-output.data-provider.ts
- apps/crn-server/test/integration/common/research-outputs.integration-test.ts
Refactor the integration tests for setting created and updated timestamps to set the expectation as the date before the request is made. This means that if there are long waits for the request to resolve (due to contentful rate limiting) then the expected timestamp should still be within the expected bounds.
> Take expected timestamp before request

- apps/crn-frontend/src/dashboard/api.ts
Without this when we add ASAP_CONTENTFUL=true cookie it still fetches data from squidex
> fix: send contentful header for reminders based on cookie

- apps/crn-frontend/src/dashboard/api.ts
- apps/crn-frontend/src/guides/api.ts
- apps/crn-frontend/src/network/teams/api.ts
- apps/crn-frontend/src/network/teams/groups/api.ts
- apps/crn-frontend/src/network/users/api.ts
- apps/crn-frontend/src/network/working-groups/api.ts
- apps/crn-frontend/src/shared-research/api.ts
Add the feature flag cookies to all API calls where it wasn't previously there, so all data can be written to and loaded from Contentful.
> Add feature flag headers to remaining api calls

- apps/crn-server/src/data-providers/contentful/research-output.data-provider.ts
- apps/crn-server/test/data-providers/contentful/research-output.data-provider.test.ts
The timestamp was being updated on all edits, but the date should represent the first time it was published.
> Don't reset addedDate on previously added research outputs

- packages/contentful/src/client.ts
- packages/contentful/test/client.test.ts
Rather than creating a new client for every request that uses the Contentful Management API, maintain an in-memory cache of environment instances per accesskey/space/env tuple so that the same client instance is re-used across multiple requests within the same process.
This will reduce the number of requests made to Contentful by 2 per POST/PUT, and so should reduce the risk of hitting API rate limits.
> Add in-memory cache for Contentful API client

- .github/workflows/reusable-test.yml
This ensures that jest exists once tests are complete when repeated rate limit errors cause tests to time out and otherwise keep an open async operation.
Also add a 20 minute timeout to integration test runs as a fallback.
> Add `--forceExit` flag to integration tests

- .github/actions/setup-environment/action.yml
- .github/environment/Base
- .github/workflows/on-push-app-extensions.yml
- packages/contentful-app-extensions/working-group-deliverables/package.json
- packages/contentful-app-extensions/working-group-deliverables/public/index.html
- packages/contentful-app-extensions/working-group-deliverables/src/App.tsx
- packages/contentful-app-extensions/working-group-deliverables/src/index.tsx
- packages/contentful-app-extensions/working-group-deliverables/src/locations/Field.tsx
- packages/contentful-app-extensions/working-group-deliverables/src/react-app-env.d.ts
- packages/contentful-app-extensions/working-group-deliverables/src/test/locations/Field.test.tsx
- packages/contentful-app-extensions/working-group-deliverables/tsconfig.json
- packages/contentful/migrations/crn/workingGroups/20230724161118-change-wg-deliverables-editor.js
- yarn.lock
This PR adds an app extension to show the working group deliverable in a nicer way displaying its status and adds a migration to change the editor type of the `deliverables` field in working groups content type to this new extension.
> CT-59 Working Group Deliverables app extension

- .github/workflows/reusable-test.yml
Preventing integration test runs on master is preventing coverage from being reported on master builds because the coverage report step depends on integration tests, and so is also skipped when they are skipped.
> Allow integration tests to run on master branch

- .github/workflows/reusable-test.yml
These can't run on master for reasons, so collecting coverage is preventing master from successfully reporting coverage.
Only run contentful integraiton tests on master so coverage can be collected successfully on all builds.
> Remove coverage collection from squidex integration tests

- .github/actions/setup-environment/action.yml
- .github/environment/Base
- .github/workflows/on-push-app-extensions.yml
- packages/contentful-app-extensions/event-custom-validation/package.json
- packages/contentful-app-extensions/event-custom-validation/public/index.html
- packages/contentful-app-extensions/event-custom-validation/src/App.tsx
- packages/contentful-app-extensions/event-custom-validation/src/index.tsx
- packages/contentful-app-extensions/event-custom-validation/src/locations/Field.tsx
- packages/contentful-app-extensions/event-custom-validation/src/react-app-env.d.ts
- packages/contentful-app-extensions/event-custom-validation/src/test/locations/Field.test.tsx
- packages/contentful-app-extensions/event-custom-validation/src/utils.ts
- packages/contentful-app-extensions/event-custom-validation/tsconfig.json
- packages/contentful/migrations/crn/events/20230728134529-add-validation-field.js
- yarn.lock
This PR adds an extension to add custom validation to `events` following this model https://github.com/contentful/apps/tree/master/examples/custom-validation as suggested by contentful support (read this thread https://contentful-community.slack.com/archives/CBR24P3T4/p1688145410897879?thread_ts=1687960592.599549&cid=CBR24P3T4).
The validations are listed here in this ticket https://asaphub.atlassian.net/browse/CT-33 similar of what we have in squidex, only 3 of them (requirements 1, 2, 4 of the ticket) make the entry unpublishable. Below there is the code of the script we use to do these validations in Squidex:
This requirement
> When a CMS user updates an event and they create a speaker and select a team and a user that is not part of that team then that user should not be displayed. …
> CT-33 Event custom validation

- packages/cms-data-sync/src/utils/rich-text.ts
- packages/cms-data-sync/test/utils/rich-text.test.ts
Some description fields on research outputs in Squidex return content as plain text strings rather than rich text html. This causes them to migrate as empty because the parser removes top-level `text` nodes.
When a rich text field contains no html tags then wrap the text with a single `<p/>` before parsing so that the top level node is a `paragraph` as expected.
> Add wrapping `<p/>` around rich text fields populated with plain text

- packages/cms-data-sync/src/utils/rich-text.ts
- packages/cms-data-sync/test/research-outputs/research-outputs.data-migration.test.ts
- packages/react-components/src/utils/__tests__/parsing.test.ts
- packages/react-components/src/utils/parsing.tsx
Ticket: https://asaphub.atlassian.net/browse/CT-85
It seems that `remarkStringify` adds a new line at the end of the string. I'm removing it so the `usageNotes` look the same after the research output migration. I'm also removing this new line from the `richTextToMarkdown` used in the front end to show the descriptions in md.
> CT-85 Remove extra new line at the end of usage notes

- .github/workflows/on-demand-cms-sync.yml
- packages/cms-data-sync/src/run-migrations.ts
- packages/cms-data-sync/test/run-migrations.test.ts
This PR makes it possible to select a single entity to run the migration in `on-demand-cms-sync` action
Example of a run where only external authors have been migrated https://github.com/yldio/asap-hub/actions/runs/5796062135/job/15708866982#step:6:431
> Enable run migration for single entity in on-demand-cms-sync

- packages/cms-data-sync/src/utils/migration.ts
- packages/cms-data-sync/test/utils/migration.test.ts
There are some entries that are not present in Contentful Production, like the one that has a table `f354ec08-c7e2-48bd-9fd8-816b44ac5bc0`. So if we throw an error when we try to create an entry if it's not found in the first place, the script stops and all the other entries are not updated. So I'm wrapping the create in a try catch block.
> fix(migration): does not throw in the fallback create

- .github/environment/Base
- .github/workflows/on-push-app-extensions.yml
- packages/contentful-app-extensions/partial-last-updated/package.json
- packages/contentful-app-extensions/partial-last-updated/public/index.html
- packages/contentful-app-extensions/partial-last-updated/src/App.tsx
- packages/contentful-app-extensions/partial-last-updated/src/index.tsx
- packages/contentful-app-extensions/partial-last-updated/src/locations/Field.tsx
- packages/contentful-app-extensions/partial-last-updated/src/react-app-env.d.ts
- packages/contentful-app-extensions/partial-last-updated/src/test/locations/Field.test.tsx
- packages/contentful-app-extensions/partial-last-updated/tsconfig.json
- packages/contentful/migrations/crn/researchOutputs/20230810144400-partial-last-updated.js
- yarn.lock
This sets a date field to the current timestamp if any other field in the model changes, except an optional list of excluded fields.
Includes a migration to add the extension to the `lastUpdatedPartial` in research outputs.
> Add Contentful extension for setting a "partial" last updated date

- .github/actions/setup-environment/action.yml
This was missing before and caused build failures.
> Add contentful app id to setup outputs

- packages/contentful/migrations/crn/users/20230814130100-email-validation.js
There are users in prod squidex who cannot currently be migrated on account of their email addresses containing an apostrophe. Make sure this is allowed in Contentful.
> Allow apostrophes in email addresses

- packages/cms-data-sync/src/utils/rich-text.ts
- packages/cms-data-sync/test/utils/rich-text.test.ts
This PR fixes two issues with missing description or part of description:
1. When there's a closing </p> but not opening
Example
```
"description": "Alpha synuclein preformed fibrils (PFF) can spread in prion-like manner both in in vitro neuronal cultures as well as in vivo when injected into the mouse brain and gut, forming pSer129-a-syn-posiitive LB-like inclusions. We developed a method where PFF are injected into the muscularis layer of the pylorus and duodenum, mimicking the spread of pathologic a-syn observed in PD.</p>",
```
found in `100f57e3-6846-464c-8b77-01c0080a35ac` (https://cloud.squidex.io/app/asap-hub/content/research-outputs/100f57e3-6846-464c-8b77-01c0080a35ac?tab=inspect)
2. When there's text not wrapped by <p>
Example
```
<p>SNCAflox delta neo mouse line; first coding …
```
> CT-89 Fix issues with RO description migration

- packages/cms-data-sync/src/index.ts
This enables upsert mode when running locally, but is prevented by the flg validation. Allow it.
> Allow `--upsert` flag to be passed into migration script

- packages/cms-data-sync/src/utils/rich-text.ts
- packages/cms-data-sync/test/utils/rich-text.test.ts
the migration was removing all text nodes that were at the top level of the rich text structure, irrespective of whether they contained text. This resulted in the loss of text data from the description fields of research outputs.
Instead, where there are top-level text nodes that contain text, wrap them into a paragraph node and preserve the content.
> Don't strip non-empty top-level text nodes

- packages/cms-data-sync/src/utils/rich-text.ts
- packages/cms-data-sync/test/utils/rich-text.test.ts
* If an unordered list is nested directly inside another list, without an intermediate list item then `parseHtml` drops the inner list as it is technically invalid html.
* Add a step to the migration to find any unordered list elements that are direct descendants of another list, and wrap them inside the previous list item if it exists, or wrap in their own list item if no previous item exists.
* Add `li` to th list of ignored tags for wrapping in `<p>` tags so that list items containing other tags - such as `<sup>` do not get incorrectly split into multiple paragraphs.
* Add a step to remove any empty text nodes as these were removed as a side-effect of the paragraph wrapping, so were causing tests to fail.
> Fix migration of nested lists in rich text

- packages/cms-data-sync/src/utils/rich-text.ts
- packages/cms-data-sync/test/utils/rich-text.test.ts
These are not supported in the parser, and so cause an error. Remove empty ones to prevent the error.
Note: the only section tags that currently exist in prod data are empty, so the non-empty case does not currently need to be considered.
> Remove empty `section` tags from rich text at migration

- apps/crn-frontend/src/__tests__/shared-research.test.ts
- apps/crn-frontend/src/network/teams/TeamOutput.tsx
- apps/crn-frontend/src/network/working-groups/WorkingGroupOutput.tsx
- apps/crn-frontend/src/shared-research.ts
When editing a research output, don't suggest the output that is being edited as an option for related research.
> Remove the current output from suggestions for related research

- apps/crn-server/src/data-providers/contentful/team.data-provider.ts
- apps/crn-server/src/data-providers/transformers/team.ts
- apps/crn-server/test/data-providers/contentful/teams.data-provider.test.ts
Ensure that team members who hold the same role are ordered consistently by adding a secondary sort on last name.
> Add secondary sort on last name for team members

- apps/crn-server/src/handlers/webhooks/webhook-contentful.ts
- apps/crn-server/test/handlers/webhooks/webhook-contentful.test.ts
- apps/gp2-server/src/handlers/webhooks/contentful.ts
- apps/gp2-server/test/handlers/webhooks/contentful.test.ts
- packages/server-common/src/handlers/webhooks/contentful.handler.ts
- packages/server-common/test/handlers/webhooks/contentful.handler.test.ts
The caching rules for the Content Delivery API and Content Preview API are different, so a record returning as being up to date against the CPA does not guarantee that a subsequent GraphQL request will return fresh data.
Using the Content Delivery API, which seems to use the same caching rules as GraphQL, ensures that the record is up to date before emitting to EventBridge.
This was tested/validated using the following method:
* Run serverless locally, with the contentful webhook pointed at it via ngrok
* Run a script to update a value in a contentful record to the current ISO8601 date string every second. It was not possible to reproduce with relatively low frequency manual updates.
* Add a graphql query to the webhook handler to fetch that record _after_ the polling is complete, and log …
> Use Content Delivery API for polling Contentful

- packages/cms-data-sync/src/index.ts
This was missed, so throws an error when you try to migrate all models.
> Allow `--all` flag on migrations

- apps/crn-server/src/data-providers/contentful/event.data-provider.ts
- apps/crn-server/test/data-providers/contentful/event.data-provider.test.ts
The code was previously written to assume null entries in event speakers was an impossible scenario, but it is not and so the case needs to be handled.
Filter null entries from the speakers array and remove the type coercion to the non-nullable type.
> Handle null entries in event speakers collection

- apps/crn-server/serverless.ts
This was missed when the 30 second sleep was added to the handler, and so with a default timeout of 16 seconds always times out.
Increase the timeout to match the squidex invitation handler.
> Increase timeout for contentful user invitation handler

- packages/contentful/migrations/crn/events/20230821125117-change-rich-text-validation-numbers.js
Some events can't be published in Contentful because they have more presentations/images than we current allow. So this PR changes the rich text fields validations to support 15 embedded entries/assets in each field. Also, it adds a filter to let the user select only entries from content-type `media` in the embedded entries.
> CT-99 fix number of allowed embedded media in events

- apps/crn-server/test/fixtures/events.fixtures.ts
- apps/gp2-server/test/fixtures/event.fixtures.ts
- packages/contentful/src/utils/parse-rich-text.ts
- packages/contentful/test/utils/parse-rich-text.test.ts
- packages/react-components/src/organisms/__tests__/RichText.test.tsx
The problem with more than one `iframe` not appearing in the frontend is that the way the iframe was being generated given the contentful document was wrong. It shouldn't have a self closing tag so it should always have `</iframe>` at the end.
> CT-101 Fix rich text displaying only one iframe

- apps/crn-server/src/handlers/event/algolia-index-event-handler.ts
- apps/crn-server/src/handlers/event/algolia-index-external-author-events-handler.ts
- apps/crn-server/src/handlers/event/algolia-index-group-events-handler.ts
- apps/crn-server/src/handlers/event/algolia-index-team-events-handler.ts
- apps/crn-server/src/handlers/event/algolia-index-user-events-handler.ts
- apps/crn-server/test/handlers/event/algolia-index-event-handler.test.ts
- apps/crn-server/test/handlers/event/algolia-index-external-author-events-handler.test.ts
- apps/crn-server/test/handlers/event/algolia-index-group-events-handler.test.ts
- apps/crn-server/test/handlers/event/algolia-index-team-events-handler.test.ts
- apps/crn-server/test/handlers/event/algolia-index-user-events-handler.test.ts
If an event is hidden then it needs to not be indexed into Algolia, so filter out events with `hidden: true` when indexing events based on related entities.
Also remove any events which have the `hidden` property set to `true` from the Algolia index.
> Don't index events with `hidden: true` into algolia

- apps/crn-server/src/controllers/interest-group.controller.ts
- apps/crn-server/test/controllers/interest-group.controller.test.ts
- apps/crn-server/test/data-providers/interest-group.data-provider.test.ts
- packages/model/src/interest-group.ts
In prod (right side of screenshot) 
when the user does not belong to any team, the API was still returning all interest groups in this call
```
this.interestGroupDataProvider.fetch({ filter: {  teamId: teamIds } })
```
because the Squidex data provider was getting called with an empty filter here (https://github.com/yldio/asap-hub/blob/master/apps/crn-server/src/data-providers/interest-group.data-provider.ts#L63-L89) and since it was not filtering anything it returned all the interest groups which is wrong.
I've changed the controller so it does not even make a call to the data provider if the user does not belong to any team.
Although it should not happen, it seems there are 8 Grantees without teams in Prod. I've ran the following query in Squidex Prod:
``` …
```
> CT-104 Interest groups not appearing in User page

- apps/crn-server/src/handlers/research-output/algolia-index-research-output-handler.ts
- apps/crn-server/test/handlers/research-output/algolia-index-research-output-handler.test.ts
The code previously assumed that if a research output was unpublished then fetching the output would result in a "Not Found" error, but since the concept of draft outputs was introduced this is no longer the case, and the unpublish case needs to be handled separately from the deleted/not found case.
If a research output is not published then remove it from the algolia index.
> Don't add draft research outputs to algolia

- packages/cms-data-sync/src/events/events.data-migration.ts
- packages/cms-data-sync/test/events/events.data-migration.test.ts
I forgot to add `lastUpdated` to the migration when it is updating an existing event, now it only fills `lastUpdated` if it is creating an event. So this PR fixes it.
> fix: add last updated to event when it already exists

- packages/cms-data-sync/src/utils/rich-text.ts
- packages/cms-data-sync/test/utils/rich-text.test.ts
The previous fix only applied to unordered lists nested inside one another. Include ordered lists as well.
> Generalise nested list fix to ordered lists as well

- .github/workflows/reusable-crn-algolia-sync.yml
Removing the settings from the scope of the partial algolia sync was causing the settings on the index to be completely removed when the temporary index was restored (because the temporary index was created with empty settings).
When creating the temporary index for partial indexing runs, do not limit the scope to only synonyms, and allow all data to be copied, and the settings therefore to be preserved when restoring back to the main index.
> Copy settings when running partial algolia sync

- apps/crn-server/test/integration/fixtures/contentful.ts
Doing these in parallel results in 429 errors when running against an environment with a large volume of events. Do thm in series so that it doesn't fail with a 429.
> Delete events in series in integration test setup

- packages/cms-data-sync/src/events/events.data-migration.ts
- packages/cms-data-sync/test/events/events.data-migration.test.ts
This event with id `c7e6413e-ece9-4d08-92a5-a04f95b6bfb1` could not be published during the migration
because the `eventLink` is an empty string and it gives a validation error on Contentful's side
so this PR transforms `eventLink` that are empty strings to `null`.
> fix(migration): convert eventLink to null when it is an empty string

- apps/crn-server/src/data-providers/contentful/calendar.data-provider.ts
- apps/gp2-server/src/data-providers/calendar.data-provider.ts
- packages/model/src/calendar-common.ts
- packages/server-common/src/handlers/calendar/calendar-handler-factory.contentful.ts
- packages/server-common/src/handlers/calendar/resubscribe-handler.ts
- packages/server-common/src/handlers/webhooks/events-updated.handler.ts
- packages/server-common/test/handlers/calendar/calendar-handler-factory.contentful.test.ts
- packages/server-common/test/handlers/calendar/resubscribe-calendars.test.ts
- packages/server-common/test/handlers/calendar/utils.ts
- packages/server-common/test/handlers/webhooks/events-updated.handler.test.ts
It is not possible to create multiple subscriptions with the same channel id, but the resource id returned when creating a subscription is required to unsubscribe.
This means that if the resource id is removed from the record in the CMS, then a new subscription cannot be created because the channel id is non unique, but the previous subscription cannot be removed.
Ensure that new subscriptions can always be created by adding a timestamp onto the channel id to ensure uniqueness. Also store the generated channel id when subscribing so that it can be used if needed to unsubscribe in future.
> Ensure uniqueness of channel ids when subscribing to google calendars

- apps/crn-server/src/data-providers/contentful/user.data-provider.ts
- apps/crn-server/test/data-providers/contentful/users.data-provider.test.ts
Passing an empty string for a non-required field with pattern or "allowed values" validators throws an error. In particular when onboarding a new user, the "Degree" field is marked as optional on the frontend, but not selecting a value causes an error because `""` is not one of the allowed values in Contentful.
Map any empty string values to `null` in the data provider to prevent the validator throwing an error.
> Map empty string values in user profile to null

- packages/contentful/migrations/crn/events/20230905123502-add-help-text.js
- packages/contentful/migrations/crn/externalAuthors/20230905124643-add-help-text.js
- packages/contentful/migrations/crn/interestGroups/20230905125029-add-help-text.js
- packages/contentful/migrations/crn/researchOutputs/20230905135647-add-help-text.js
- packages/contentful/migrations/crn/users/20230905115618-add-help-text.js
This PR adds all missing "hints" from Squidex to Contentful.
Some of these hints were inside the section which we don't have in Contentful, so I've added some section hints directly to the field helpText.
> CT-116 Adding missing help texts to Contentful

- apps/gp2-server/test/data-providers/dashboard.data-provider.test.ts
The parsing for dashboard announcements removes announcements with deadlines in the past, so the test with a hard-coded deadline started failing as soon as the hard-coded date was in the past.
Replace the hard-coded date with a calculated future date, and add coverage for the case where the deadline is in the past.
> Fix unit tests for dashboard announcement deadlines

- .github/workflows/reusable-crn-algolia-sync.yml
- .github/workflows/reusable-gp2-algolia-sync.yml
This should hopefully prevent simultaneous index runs from interfering with one another.
> Scope temporary algolia index to github run id

- apps/crn-frontend/src/network/working-groups/WorkingGroupOutput.tsx
- apps/storybook/src/ResearchOutputRelatedEventsCard.stories.tsx
- packages/react-components/src/organisms/ResearchOutputRelatedEventsCard.tsx
- packages/react-components/src/organisms/__tests__/ResearchOutputRelatedEventsCard.test.tsx
- packages/react-components/src/templates/ResearchOutputForm.tsx
- packages/react-components/src/templates/__tests__/ResearchOutputForm.test.tsx
This PR fixes this bug: There isn’t any event suggestion when we try to add a related event in a Working Group research output, so we can’t add a related event.
In order to fix it, it was added `getRelatedEventSuggestions` to `WorkingGroupOutput` so events appear on the search and can be added as related events.
I've also changed some types so it would give a Typescript error if we don't pass `getRelatedEventSuggestions` to `WorkingGroupOutput`.
> CRN-1489 Fix related events not appearing in WG research outputs

- apps/crn-server/serverless.ts
* leave squidex backup s3 bucket in place in case there is a need to access historical data
* leave `IS_CONTENTFUL_ENABLED` environment variables while the code remains dependendent on them
> Remove Squidex handlers and config from serverless deployment

- apps/gp2-frontend/src/projects/__tests__/api.test.tsx
- apps/gp2-frontend/src/projects/api.ts
Filter is now constructing the algolia query properly when traineeProject is selected.
https://github.com/yldio/asap-hub/assets/4627980/05064760-15e2-4fa0-aec3-8386d48641b2
> Fix traineeProject filter

- apps/crn-server/test/integration/common/reminders.integration-test.ts
These tests do a large amount of setup work, deleting all pre-existing events, so the first test in the suite often causes a timeout.
Increase the timeout to allow more time for setup when Contentful is rate limited.
> Increase timeout for reminders tests

- apps/crn-server/src/data-providers/contentful/reminder.data-provider.ts
- apps/crn-server/test/data-providers/contentful/reminder.data-provider.test.ts
Stop showing a new RO published reminder when there is a new RO version reminder
JIRA: https://asaphub.atlassian.net/browse/CRN-1496
> [CRN-1496] fix: remove published reminders related to version reminders

- packages/server-common/src/utils/sync-google-event.ts
- packages/server-common/src/utils/type-narrowing.ts
- packages/server-common/test/utils/sync-google-event.test.ts
An error was happening during sync google events due to a field that is present in CRN events but not present in GP2 events.
Log in AWS: https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/%2Faws%2Flambda%2Fgp2-hub-3690-eventsUpdated/log-events/2023%2F09%2F13%2F[%24LATEST]f7949a7fcf76436ba97bf7cac4b356f6?start=PT72H
Somehow typescript didn't catch this. So I'm using type narrowing now to ensure tags won't be sent to GP2 events. 
--- 
After the changes in this PR, I've manually added a calendar to both CRN and GP2 and checked that the events are syncing properly
CRN: [https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/%2Faws%2Flambda%2Fasap-hub-3697-gcalEventsUpdatedContentful/log-events/202 …
> GP2HUB-92 bugfix: Events not being created when calendar is added

- apps/crn-server/src/data-providers/contentful/user.data-provider.ts
- apps/crn-server/src/handlers/webhooks/cronjob-sync-orcid.ts
- apps/crn-server/test/data-providers/contentful/users.data-provider.test.ts
- apps/crn-server/test/integration/events.integration-test.ts
- apps/crn-server/test/integration/orcid.integration-test.ts
- apps/crn-server/test/integration/reminders.integration-test.ts
- apps/crn-server/test/integration/research-outputs.integration-test.ts
- apps/crn-server/test/integration/research-tags.integration-test.ts
- apps/crn-server/test/integration/teams.integration-test.ts
- apps/crn-server/test/integration/users.integration-test.ts
- jest-integration.config.js
* Moves integration tests out of 'common' into root dir
* Fixes the issue with query complexity in cronjob-sync-orcid handler
* Moves away from Promise.all for processing users in cronjob-sync-orcid handler
* Adds an integration test to prevent regression
> fix: Sync ORCID handler query complexity error

- apps/gp2-server/src/data-providers/news.data-provider.ts
- apps/gp2-server/test/fixtures/news.fixtures.ts
- packages/contentful/migrations/gp2/news/20230925091407-add-thumbnail-field.js
- packages/contentful/src/gp2/autogenerated-gql/gql.ts
- packages/contentful/src/gp2/autogenerated-gql/graphql.ts
- packages/contentful/src/gp2/queries/news.queries.ts
- packages/contentful/src/gp2/schema/autogenerated-schema.graphql
- packages/gp2-components/src/molecules/NewsItem.tsx
- packages/gp2-components/src/molecules/__tests__/NewsItem.test.tsx
- packages/model/src/gp2/news.ts
This PR
- Adds a migration to add thumbnail field
- Adds thumbnail to gp2 query and updates news data provider
- Updates NewsItem so it displays the thumbnail properly on the FE
---
Contentful with thumbnail field 
Thumbnail in the FE
> GP2HUB-96 Add thumbnail to news

- apps/crn-server/src/controllers/user.controller.ts
- apps/crn-server/src/utils/fetch-orcid.ts
- apps/crn-server/test/controllers/user.controller.test.ts
Fixes the issue with null last-modified-date:
With this change we will support null and in such case we will simply update the sync date in the CMS without making any changes to orcid fields (same way we do for 500s coming from ORCID API)
> fix: Support null ORCID last modified date

- apps/gp2-server/test/routes/output.route.test.ts
- packages/contentful/migrations/gp2/outputs/20230927125340-make-gp2supported-not-required.js
- packages/gp2-components/src/templates/OutputForm.tsx
- packages/gp2-components/src/templates/__tests__/OutputForm.test.tsx
This PR makes the field `gp2Supported` to be not required since for document types Training Materials and Procedural Form this field does not even appear in the form in the hub. It also makes the default value to be "Don't Know" when it doesn't have a previous value in the form.
> GP2HUB-109 gp2Supported as not required

- apps/crn-frontend/src/events/Events.tsx
- apps/crn-frontend/src/shared-research/__tests__/api.test.ts
- apps/crn-frontend/src/shared-research/api.ts
- packages/algolia/src/client.ts
- packages/algolia/test/client.test.ts
https://github.com/yldio/asap-hub/assets/1936253/ec3eba4a-a4d5-4064-aef4-ce1173f3c93d
I identified an infinite loop issue caused by nonstandard Algolia errors. To address this, I converted these errors into standard ones, ensuring compatibility with our 'instance of' functionality. The fix has been applied universally in the Algolia client and removed from research outputs.
> Convert Algolia error into normal error

- packages/gp2-components/src/templates/OutputDetailPage.tsx
This PR fixes the issue with the scrollbar appearing when not needed in output detail page
> fix: hide scrollbar in output detail page

- apps/crn-server/test/utils/sentry-wrapper.test.ts
- apps/gp2-server/test/utils/sentry-wrapper.test.ts
- packages/server-common/src/utils/sentry-wrapper.ts
- packages/server-common/test/utils/sentry-wrapper.test.ts
This will allow us to ignore all the Sentry errors so that in the event of exceeding the quotas the handlers will continue to work as normal
> fix: Ignore Sentry errors

- apps/gp2-server/src/handlers/webhooks/events-updated.ts
- packages/contentful/package.json
- packages/contentful/src/client.ts
- packages/contentful/test/client.test.ts
- packages/server-common/src/utils/sync-google-event.ts
- yarn.lock
Jira ticket: https://asaphub.atlassian.net/browse/GP2HUB-140
This PR moves the RateLimiter from `apps/gp2-server/src/handlers/webhooks/events-updated.ts` to `packages/contentful/src/client.ts` so every time we call `getGraphQLClient` or `getRestClient` it will be already created with rate limit and it adds more information in the log of `'Invalid organiser'` error.
---
About the specific event mentioned in the ticket `“Microbiome Working group 5th meeting” from the Microbiome WG calendar` (https://app.contentful.com/spaces/5v6w5j61tndm/environments/Production/entries/7ISTd1fUckDb7WGk2OIMSv) I couldn't find any log in cloudwatch
And I could check for other events that had 429 errors that they appear using the same query but changing the id
So it seems there wasn't a 429 error for this …
> GP2HUB-140 Add rate limits to contentful clients

- apps/crn-frontend/src/dashboard/__tests__/api.test.tsx
- apps/crn-frontend/src/dashboard/api.ts
https://asaphub.atlassian.net/browse/CRN-1533
Intl.DateTimeFormat().resolvedOptions().timeZone is possibly undefined when using various browsers. This can happen when the user has not set a timezone in their browser.
fallback to getting timezone offset and sending `UTC-{hours}` or `UTC+{hours}` to backend as these are valid timezone for luxon date package we use
> [CRN-1533] fix(reminders): add fallback timezone detector

- apps/crn-frontend/src/dashboard/Body.tsx
- apps/crn-frontend/src/events/EventList.tsx
- apps/crn-frontend/src/network/EventsEmbedList.tsx
- apps/crn-frontend/src/shared-research/state.ts
- apps/crn-frontend/src/tags/Routes.tsx
- apps/crn-frontend/src/tags/TagsList.tsx
- apps/crn-frontend/src/tags/__tests__/Routes.test.tsx
- apps/crn-frontend/src/tags/__tests__/TagsList.test.tsx
- apps/crn-frontend/src/tags/__tests__/api.test.ts
- apps/crn-frontend/src/tags/api.ts
- apps/crn-frontend/src/tags/state.ts
- apps/crn-server/scripts/export-entity.ts
- apps/crn-server/src/handlers/lab/algolia-index-lab-users-handler.ts
- apps/crn-server/src/handlers/user/algolia-index-user-handler.ts
- apps/crn-server/test/handlers/lab/algolia-index-lab-users-handler.test.ts
- apps/crn-server/test/handlers/user/algolia-index-user-handler.test.ts
- packages/algolia/src/client.ts
- packages/model/src/index.ts
- packages/model/src/tag.ts
- packages/react-components/package.json
- packages/react-components/src/event-mapper.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/templates/TagsPageBody.tsx
- packages/react-components/src/templates/__tests__/TagsPageBody.test.tsx
- packages/react-components/tsconfig.json
- yarn.lock
This PR:
- adds `_tags` to user data in algolia handlers
- adds `tags/state` and `tags/api` files to query more than one entity ("research-output" | "user" | "external-author" | "event") in algolia using tags. So for the next entities we'll just need to update the data we sent to algolia (using `_tags`), update `entities` in [here](https://github.com/yldio/asap-hub/blob/CRN-1545-populate-user-tags-field/apps/crn-frontend/src/tags/Routes.tsx#L15) and add the card to `TagsPageBody`.
> CRN-1545 Add users to tag search

- apps/storybook/src/UserProfileResearch.stories.tsx
- packages/react-components/src/organisms/ProfileCardList.tsx
This is a second attempt to fix "padding" in the user profile list. The problem was that if a user hasn't filled out their whole profile you would get empty spaces for the missing cards. I tried to filter these out in the profile list card but its quite difficult to differentiate null from a component. Ive taken the approach of reverting the padding back to how it was as it didn't work with other peoples profiles and or your own with edit buttons. I have used CSS to hide the empty containers which works well enough
> Hide empty cards

- .github/actions/setup-environment/action.yml
- .github/actions/sls-deployment/action.yml
- .github/actions/sls-package/action.yml
- .github/environment/Base
- .github/environment/Branch
- .github/environment/Development
- .github/environment/Production
- .github/workflows/reusable-test.yml
- apps/crn-frontend/src/about/api.ts
- apps/crn-frontend/src/dashboard/api.ts
- apps/crn-frontend/src/discover/tutorials/api.ts
- apps/crn-frontend/src/events/api.ts
- apps/crn-frontend/src/events/calendar/api.ts
- apps/crn-frontend/src/guides/api.ts
- apps/crn-frontend/src/network/interest-groups/api.ts
- apps/crn-frontend/src/network/teams/api.ts
- apps/crn-frontend/src/network/teams/interest-groups/api.ts
- apps/crn-frontend/src/network/users/__tests__/api.test.ts
- apps/crn-frontend/src/network/users/api.ts
- apps/crn-frontend/src/network/users/interest-groups/api.ts
- apps/crn-frontend/src/network/working-groups/api.ts
- apps/crn-frontend/src/shared-research/api.ts
- apps/crn-server/serverless.ts
- apps/crn-server/src/config.ts
- apps/crn-server/src/handlers/calendar/gcal-resubscribe-handler.ts
- apps/crn-server/test/integration/reminders.integration-test.ts
- apps/gp2-server/serverless.ts
- packages/frontend-utils/src/api-util/__test__/api-util.test.tsx
- packages/frontend-utils/src/api-util/api-util.ts
There's an unused `IS_CONTENTFUL_ENABLED` and `X-Contentful-Enabled` header left on the codebase. This PR removes both of them.
> Remove is contentful enabled references

- apps/crn-server/test/integration/reminders.integration-test.ts
Temporarily disable the integration test that is causing is the most headaches with false negatives. This should be later addressed through [ASAP-70](https://asaphub.atlassian.net/browse/ASAP-70)
[ASAP-70]: https://asaphub.atlassian.net/browse/ASAP-70?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> fix: Skip failing reminder integration test

- packages/contentful/migrations/crn/workingGroups/20231113103854-add-tags-field.js
This PR adds the `tags` field to working groups (ticket: [[CRN] Add tags to Working Groups](https://asaphub.atlassian.net/browse/ASAP-44)). This is a blocker for the ticket on the current sprint: [[CRN] Add Working Groups to Algolia and Tag search](https://asaphub.atlassian.net/browse/ASAP-45). But this [[CRN] Add tags to Working Groups](https://asaphub.atlassian.net/browse/ASAP-44) only mentions adding tags to the CMS and I couldn’t find a ticket for CRN mentioning to add the tags component to the working group page or the figma designs related to it. But I believe it should be in another ticket. So this PR simply adds `tags` to working groups.
> ASAP-44 Add tags to working groups

- .github/actions/contentful-checks/action.yml
- .github/actions/setup-environment/action.yml
- .github/workflows/on-push-branch.yml
- .github/workflows/on-remove.yml
- .github/workflows/reusable-create-environment.yml
PR adds back setting up api and index based on `crn-create-environment` or `gp2-create-environment` label. That was added in https://github.com/yldio/asap-hub/pull/3862 and reverted
Also fixes the following issue
PR that did not have dedicated environment were deleting `asap-hub_dev` and `gp2-hub_dev` indexes during PR clean up workflow
only run the delete index step if the index is not dev or prod
only remove webhook if it is PR environment
only copy index if it is a PR environment
> fix: PR indexes & api setup and teardown

- .github/workflows/on-demand-crn-algolia-sync.yml
- .github/workflows/on-demand-gp2-algolia-sync.yml
- .github/workflows/reusable-crn-algolia-sync.yml
- .github/workflows/reusable-gp2-algolia-sync.yml
When we trigger [on-demand-crn-algolia-sync.yml](https://github.com/yldio/asap-hub/blob/master/.github/workflows/on-demand-crn-algolia-sync.yml) or [on-demand-gp2-algolia-sync.yml](https://github.com/yldio/asap-hub/blob/master/.github/workflows/on-demand-gp2-algolia-sync.yml) it syncs using `asap-hub_dev` index even when we select environment `Branch` and pass a contentful environment other than `Development`.
So in order to change this, if the person selects `Branch`, crn-create-env | gp2-create-env will be set to true so we can have an algolia index linked to the PR number. Check this code to understand the change: https://github.com/yldio/asap-hub/blob/master/.github/actions/setup-environment/action.yml#L281:L312.
> (fix): on-demand-algolia-sync

- apps/crn-auth-frontend/vite.config.ts
- apps/gp2-auth-frontend/vite.config.ts
Changes the settings for vite bundle in such a way that it produces the bundle with the same name each time, which is how it was done previously.
> fix: Invalid bundle URL bug

- apps/crn-server/src/config.ts
Should fix the issue whereby a subscription to google calendar happens with a localhost url
> fix: Missing API URL

- apps/crn-frontend/src/dashboard/Dashboard.tsx
This reverts commit 49da63c4804cd1f19d884862e01e1cb87101e6f1.
> fix: Revert skeleton loading state for Dashboard

- apps/auth0/package.json
- apps/auth0/tenant.yaml
It seems auth0 only supports node 12, 16 and 18 in its actions
So I'm reverting the change in the action runtime back to what it was before.
We didn't catch the problem in the first PR because since it didn't have the label `use-pr-auth0-tenant`, it didn't try to deploy these actions. Now with the label we can see that the deployment works.
> fix: node 20 auth0 deploy

- packages/gp2-components/src/organisms/EmailSection.tsx
- packages/react-components/src/atoms/Tooltip.tsx
Before - **wrong** width **without** arrow down            |  After - correct width **wtih** arrow down
---
Before - **wrong** button width in GP2           |  After - **correct** button width in GP2
> ASAP-272 Fix tooltip width

- apps/crn-frontend/src/network/teams/__tests__/Outputs.test.tsx
- apps/crn-frontend/src/network/users/__tests__/Outputs.test.tsx
- apps/crn-frontend/src/network/working-groups/__tests__/Outputs.test.tsx
- apps/crn-frontend/src/shared-research/__tests__/ResearchOutputList.test.tsx
- apps/gp2-frontend/src/outputs/OutputList.tsx
- apps/gp2-frontend/src/tags/ResultList.tsx
- packages/react-components/src/molecules/ListControls.tsx
- packages/react-components/src/molecules/__tests__/ListControls.test.tsx
- packages/react-components/src/organisms/ResultList.tsx
- packages/react-components/src/organisms/__tests__/ResultList.test.tsx
- packages/react-components/src/templates/__tests__/SharedResearchList.test.tsx
ref: https://asaphub.atlassian.net/jira/software/c/projects/ASAP/boards/13?selectedIssue=ASAP-262
The isAdministrator prop was being used in the ResultList component to display different UIs for the 'Export as CSV' section. This is no longer needed and so has been removed. It also caused a bug in gp2 where the 'Export as CSV' section was rendered differently depending on whether the user was an admin or not.
> Asap 262 update view export buttons

- packages/algolia/schema/gp2/algolia-reverse-timestamp-schema.json
- packages/algolia/schema/gp2/algolia-schema.json
The workingGroup.title & project.title attributes are used for events while workingGroups.title & projects.title are for people.
events:
people:
> add projects and working groups filter to people page

- apps/gp2-frontend/src/events/Event.tsx
- turbo.json
* makes the typecheck job depend on related dependency jobs (so that the packages are built first)
* fixes the bug introduced because of the missing dependency in turbo
> fix: Turbo typecheck depedency issue

- .github/actions/cache-build/action.yml
The issue with the build not being uploaded with the right algolia index is that we have the `Cache build output` step in `reusable-build` that was restoring an old build although we had a new build in the previous step.
The reason is that we use as key:
```
key: ${{ inputs.cache-prefix }}-${{ inputs.environment-name }}-${{ github.sha }}
```
that looks like
```
frontend-output-Branch-6bb10f742f8b2b087441b7943ab7d7b14fea4901
```
and this `github.sha` doesn't change when we just add a label like `crn-create-environment` or `gp2-create-environment` but don't push a new commit. So in this case, we restore an old build.
---
What was happening in the actions:
1. Pushed a commit without labels -> New sha -> Cache not restored
2. Added a label without pushing a new commit -> triggered the …
> ASAP-346 Fix algolia index in dedicated environment PR

- apps/crn-server/src/controllers/user.controller.ts
- apps/crn-server/src/data-providers/contentful/user.data-provider.ts
- apps/crn-server/src/data-providers/types/users.data-provider.types.ts
- apps/crn-server/test/controllers/user.controller.test.ts
- apps/crn-server/test/data-providers/contentful/users.data-provider.test.ts
- apps/crn-server/test/handlers/user/cronjob-sync-orcid.test.ts
- apps/crn-server/test/handlers/webhooks/webhook-connect-by-code.test.ts
- packages/server-common/src/handlers/user/sync-active-campaign-contact-factory.ts
- packages/server-common/test/handlers/user/sync-active-campaign-contact-factory.test.ts
This PR adds an option `polling` to user data provider update method. We don't always need to fetch the last version of the entry, only when we're displaying data in the frontend. So we can pass this flag as `false` to webhooks, for example.
> ASAP-353 Poll user data conditionally

- packages/react-components/src/templates/SharedResearchOutput.tsx
- packages/react-components/src/templates/__tests__/SharedResearchOutput.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-295
---
This PR updates the share output footer
> ASAP-295 Update shared research footer

- apps/crn-frontend/src/network/working-groups/About.tsx
- apps/crn-frontend/src/network/working-groups/WorkingGroupProfile.tsx
- apps/crn-frontend/src/network/working-groups/__tests__/WorkingGroupProfile.test.tsx
- apps/storybook/src/WorkingGroupPage.stories.tsx
- packages/react-components/src/templates/WorkingGroupAbout.tsx
- packages/react-components/src/templates/WorkingGroupPageHeader.tsx
- packages/react-components/src/templates/__tests__/WorkingGroupAbout.test.tsx
- packages/react-components/src/templates/__tests__/WorkingGroupPageHeader.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-294
---
This PR
- Adds the contact button + copy email to the header of internal working groups as per requirement
- Removes the footer for completed working groups
> ASAP-294 Update working group header/footer

- packages/react-components/src/organisms/HelpSection.tsx
- packages/react-components/src/templates/TutorialDetailsPage.tsx
This PR hides this text
in Tutorials page as requested here https://asaphub.atlassian.net/browse/ASAP-298?focusedCommentId=11597
> Hide tech support text in Tutorials page

- packages/contentful/src/utils/poll-content.ts
- packages/contentful/test/utils/poll-content.test.ts
From https://www.contentful.com/faq/webhooks/#if-i-received-a-publish-event-why-do-i-get-an-old-version-in-the-cda
The `retry` had `maxRetryTime` as 8s. So we would try to fetch fresh data during only 8 seconds. More about parameters here https://github.com/vercel/async-retry?tab=readme-ov-file#api.
Running it locally, it would give us most of times 5 trials
which might be not enough if the cache is taking a long time to be purged. 
This is not happening so frequently, though. From Sentry it seems that we had a peak over March 6th ~ 8th but it is not happening so often now
Link to sentry: https://yld.sentry.io/issues/5038500144/?referrer=slack&notification_uuid=9aa914de-ff4c-414b-a453-a4b8c950514c&environment=production&alert_rule_id=14694571&alert_type=issue
The `maxRetryTime` was …
> ASAP-361 Adjust parameters to reduce revision errors

- apps/crn-server/src/data-providers/contentful/analytics.data-provider.ts
- apps/crn-server/test/data-providers/contentful/analytics.data-provider.test.ts
1. If a team has a user and that user is a leader of a working group and the team is inactive then that should count towards Previously in a leadership role in the WG tab and the Currently in a leadership metric should be 0
2. If a team has a user and that user is a member of an working group and the team is inactive then that should count towards Previously in a membership role in the WG tab  and the Currently in a membership metric should be 0
3. If a team has a user and that user is a leader of an interest group and the team is inactive then that should count towards Previously in a leadership role in the IG tab and the Currently in a leadership metric should be 0
> feat: ASAP-397 Inactive team Working Group and Interest Group participation

- apps/gp2-server/src/handlers/news/algolia-index-handler.ts
- apps/gp2-server/test/handlers/news/algolia-index-handler.test.ts
This is a fix for https://github.com/yldio/asap-hub/pull/4218
---
The issue is that we were not sending `_tags` to algolia in the handler, only on the on-demand action.
I've tested adding tags to news in `gp2-4231` contentful environment and checking that they appear on https://4231.gp2.asap.science/tags?entityType=news
> fix: finding news by tags

- packages/fixtures/src/gp2/users.ts
- packages/gp2-components/src/organisms/KeyInformationModal.tsx
- packages/gp2-components/src/organisms/__tests__/KeyInformationModal.test.tsx
This bug was introduced in this PR https://github.com/yldio/asap-hub/pull/4160. 
The issue was that before the bug was introduced we were not sending `orcid` if its value is not truthy. 
After the bug was introduced, we were always sending `orcid` and when it doesn't have a value, it's initialized as `''` so it was giving a 400 error in the BE.
BE error in gp2.dev
So this PR makes the `orcid` field to be sent only when it's value is truthy as it was before the bug was introduced.
> ASAP-400 (GP2) Make it possible to save user without orcid

- .github/workflows/on-push-branch.yml
Changes the order of jobs by removing some dependencies so that the deployment can happen without tests passing which should speed it up
> feat: Rearrange PR CI job order to speed up deployment

- .github/workflows/on-push-branch.yml
This PR will enable us to use merge queues in github. The changes include:
* adding merge-group trigger for the existing on-push-branch workflow so that it gets triggered when the PR reaches the queue
* adding a fix to concurrency group since head_ref is missing when triggered by merge-group
> feat: ASAP-210 Prepare workflow for merge queue

- .github/workflows/reusable-deployment.yml
- apps/asap-cli/package.json
- apps/asap-cli/src/cli.ts
- apps/asap-cli/src/scripts/algolia/index.ts
- apps/asap-cli/src/scripts/algolia/set-analytics-settings.ts
- apps/asap-cli/src/scripts/algolia/set-settings.ts
- package.json
- packages/algolia/schema/crn-analytics/ig_current_leadership_asc-schema.json
- packages/algolia/schema/crn-analytics/ig_current_leadership_desc-schema.json
- packages/algolia/schema/crn-analytics/ig_current_membership_asc-schema.json
- packages/algolia/schema/crn-analytics/ig_current_membership_desc-schema.json
- packages/algolia/schema/crn-analytics/ig_previous_leadership_asc-schema.json
- packages/algolia/schema/crn-analytics/ig_previous_leadership_desc-schema.json
- packages/algolia/schema/crn-analytics/ig_previous_membership_asc-schema.json
- packages/algolia/schema/crn-analytics/ig_previous_membership_desc-schema.json
- packages/algolia/schema/crn-analytics/team_desc-schema.json
- packages/algolia/schema/crn-analytics/wg_current_leadership_asc-schema.json
- packages/algolia/schema/crn-analytics/wg_current_leadership_desc-schema.json
- packages/algolia/schema/crn-analytics/wg_current_membership_asc-schema.json
- packages/algolia/schema/crn-analytics/wg_current_membership_desc-schema.json
- packages/algolia/schema/crn-analytics/wg_previous_leadership_asc-schema.json
- packages/algolia/schema/crn-analytics/wg_previous_leadership_desc-schema.json
- packages/algolia/schema/crn-analytics/wg_previous_membership_asc-schema.json
- packages/algolia/schema/crn-analytics/wg_previous_membership_desc-schema.json
- yarn.lock
This PR changes the algolia `set-settings` to create all the replica indexes necessary to sort the Leadership & Membership data.
> ASAP-447 Create L&M replica indexes

- packages/gp2-components/src/templates/__tests__/OutputForm.test.tsx
Time to run `packages/gp2-components/src/templates/__tests__/OutputForm.test.tsx`
Before   (124 secs)        |  After (56 secs)  
---
Using the sort script found in this response https://stackoverflow.com/questions/69198091/get-jest-tests-sorted-by-duration
I've found that the two tests that took most time to run were 
- publishes with type and subtype (18 secs)
- can submit published date (12 secs)
and both of them had a lot of `user.click` and `user.type` which made the test to be slow. Since these clicks and types were also tested in `publish the form for entity workingGroup |  project` I've removed most of them and I've added initial props so the clicks and types were not necessary.
Apart from that, I've removed `renders all the …
> ASAP-366 Refactor Outputform test

- apps/gp2-server/src/data-providers/working-group.data-provider.ts
- apps/gp2-server/src/publicApp.ts
- apps/gp2-server/src/routes/public/working-group.route.ts
- apps/gp2-server/test/fixtures/working-group.fixtures.ts
- apps/gp2-server/test/routes/public/working-group.route.test.ts
- packages/fixtures/src/gp2/working-groups.ts
- packages/model/src/gp2/working-group.ts
- **add new public endpoints**
- **add publish date and version to the responses**
* we dont need pagination here really as the amount of working groups is so insignificant it was never implemented in our endpoints either - I think we can send it to GMMB as is but let me know what you think
> feat: ASAP-415 Add Working-Group Public API endpoint

- .github/actions/algolia-import-entity/action.yml
- .github/actions/algolia-import-metric/action.yml
- .github/workflows/reusable-crn-algolia-sync.yml
- .github/workflows/reusable-crn-analytics-algolia-sync.yml
- .github/workflows/reusable-gp2-algolia-sync.yml
The aim of this pr is to modify the `sync_index` jobs for analytics and entities so that we don't repeat code as the import steps are basically the same except the metric/entity-type inputs.
- modify `algolia-import-entity` and `algolia-import-metric` actions to import into algolia all metrics/entity-types when the input is 'all' otherwise import for the specific metric/entity-type provided
- update the corresponding reusable workflows
Tests
CRN Algolia Entity Sync  
For All entities
For Team Entity
GP2 Algolia Entity Sync
For All Entities
For Project Entity
We don't use the data-store input so I've taken that out as well
CRN Algolia Metrics Sync
For All Metrics
For Team Productivity Metric
> update analytics sync action & workflow

- apps/gp2-server/serverless.ts
Adds CloudFormation throttling settings to Stage resource that affect the specific /public/ route of the API Gateway
> feat: ASAP-416 Add throttling configuration to public API

- apps/crn-frontend/src/analytics/__tests__/Routes.test.tsx
- apps/crn-frontend/src/analytics/productivity/Productivity.tsx
- apps/crn-frontend/src/analytics/productivity/TeamProductivity.tsx
- apps/crn-frontend/src/analytics/productivity/UserProductivity.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/Productivity.test.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/TeamProductivity.test.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/UserProductivity.test.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/api.test.tsx
- apps/crn-frontend/src/analytics/productivity/api.ts
- apps/crn-frontend/src/analytics/productivity/state.ts
- packages/algolia/src/analytics/types.ts
- packages/algolia/src/client.ts
- packages/fixtures/src/analytics.ts
- packages/fixtures/src/index.ts
- packages/model/src/analytics.ts
- packages/react-components/src/molecules/AnalyticsControls.tsx
- packages/react-components/src/molecules/CaptionItem.tsx
- packages/react-components/src/molecules/__tests__/CaptionItem.test.tsx
- packages/react-components/src/organisms/TeamProductivityTable.tsx
- packages/react-components/src/organisms/UserProductivityTable.tsx
- packages/react-components/src/organisms/__tests__/TeamProductivityTable.test.tsx
- packages/react-components/src/organisms/__tests__/UserProductivityTable.test.tsx
- packages/react-components/src/templates/AnalyticsProductivityPageBody.tsx
- packages/react-components/src/templates/__tests__/AnalyticsProductivityPageBody.test.tsx
- packages/react-components/src/utils/analytics.ts
- packages/react-components/src/utils/index.ts
This PR connects the frontend with Algolia to display the performance in the User and Team Productivity pages.
---
JIRA ticket: https://asaphub.atlassian.net/browse/ASAP-376
For more context:
Front PR: [ASAP-376 Analytics Below/Average/Above icons and components](https://github.com/yldio/asap-hub/commit/935e42317ea9e0527dc302eca0ffcca1c9371fae)
Algolia PR: [ASAP-376 Process Productivity Metrics](https://github.com/yldio/asap-hub/commit/e4d5d2bbfc7025cccf155e0bbcaa23bc4db86a7d)
---
> ASAP-376 Connecting Frontend with Algolia Data

- apps/crn-frontend/src/analytics/leadership/Leadership.tsx
- apps/crn-frontend/src/analytics/leadership/__tests__/Leadership.test.tsx
- apps/crn-frontend/src/analytics/productivity/Productivity.tsx
- apps/crn-frontend/src/analytics/productivity/TeamProductivity.tsx
- apps/crn-frontend/src/analytics/productivity/UserProductivity.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/Productivity.test.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/TeamProductivity.test.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/UserProductivity.test.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/api.test.tsx
- apps/crn-frontend/src/analytics/productivity/api.ts
- apps/crn-frontend/src/hooks/algolia.ts
- apps/crn-server/scripts/export-analytics.ts
- packages/react-components/src/molecules/AnalyticsControls.tsx
- packages/react-components/src/molecules/__tests__/AnalyticsControls.test.tsx
- packages/react-components/src/templates/AnalyticsCollaborationPageBody.tsx
- packages/react-components/src/templates/AnalyticsLeadershipPageBody.tsx
- packages/react-components/src/templates/AnalyticsProductivityPageBody.tsx
- packages/react-components/src/templates/__tests__/AnalyticsCollaborationPageBody.test.tsx
- packages/react-components/src/templates/__tests__/AnalyticsProductivityPageBody.test.tsx
ref: https://asaphub.atlassian.net/jira/software/c/projects/ASAP/boards/13?selectedIssue=ASAP-373  (points 5 & 6: searching on the User & Team Productivity pages)
- Adds tags to the user & team productivity types in algolia
- Updates  frontend with search functionality
- Since all the Analytics pages have similar controls & labels (search, export etc), I've combined them into one component. The arrangement was different from what we have in the designs so I updated those as well (the view & export buttons are below the page title, description & search bar)
Design
> [ASAP-373] - productivity search

- apps/gp2-server/src/handlers/event/algolia-index-handler.ts
- apps/gp2-server/test/handlers/event/algolia-index-handler.test.ts
This PR adds the same condition to the GP2 event index handler as we have in CRN (https://github.com/yldio/asap-hub/blob/master/apps/crn-server/src/handlers/event/algolia-index-event-handler.ts#L28) to remove hidden events from algolia, this way we won't have multiple cancelled events in the frontend.
> ASAP-552 Remove hidden events from algolia in GP2

- .github/workflows/on-demand-crn-analytics-algolia-sync.yml
- .github/workflows/on-demand-gp2-algolia-sync.yml
- .github/workflows/on-demand-rollback-contentful-migration.yml
There are still some actions with the wrong reference to the slack webhook.
I'm taking as a reference this on-remove action (https://github.com/yldio/asap-hub/blob/master/.github/workflows/on-remove.yml#L293) that I know for sure it triggers an alert and it sets
```
webhook: ${{ secrets.SLACK_WEBHOOK }}
```
> fix slack webhook reference actions

- apps/crn-frontend/src/analytics/leadership/Leadership.tsx
- apps/crn-frontend/src/analytics/leadership/__tests__/export.test.ts
- apps/crn-frontend/src/analytics/leadership/export.ts
- apps/crn-server/src/utils/analytics/leadership.ts
- packages/model/src/analytics.ts
- packages/react-components/src/organisms/LeadershipMembershipTable.tsx
- packages/react-components/src/organisms/__tests__/LeadershipMembershipTable.test.tsx
- packages/react-components/src/templates/AnalyticsLeadershipPageBody.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-521
---
This PR:
- Retrieves team inactive date and displays badge in the frontend if team is inactive
- Adds the column Team Status and Inactive Since in the CSV with the correct data
- Renames the columns so we would have Currently in a leadership role instead of currentlyInALeadershipRole
> ASAP-521 Display Inactive team badge on the FE and fix CSV

- packages/contentful/migrations/crn/manuscripts/20240723115126-fix-manuscript-file-validation.js
The validation type was wrong in the migration that created the manuscript file field. So when the user tries to create a manuscript we get this error
And the content model is like this in Production (without PDF document selected)
The fix is to add a migration editing the validation of the manuscript file field.
The mimetype is actually called `pdfdocument` instead of `application/pdf`
https://github.com/contentful/contentful-migration/blob/860fa6aa064772e4ae534f0da04d73beb0ca8e34/index.d.ts#L128
> fix: manuscript file validation

- apps/crn-frontend/src/network/working-groups/__tests__/WorkingGroupOutput.test.tsx
I'm increasing the timeout on the `WorkingGroupOutput.test` file based on the error received on this run https://github.com/yldio/asap-hub/actions/runs/10140260920/job/28035140289.
> increase timeout

- packages/algolia/schema/crn-analytics/algolia-schema.json
JIRA ticket: https://asaphub.atlassian.net/browse/ASAP-606
---
The issue is that `paginationLimitedTo` was set to 1000 but in Prod we have more than 1700 users. And with this `paginationLimitedTo` it was showing only the first 1000 users. Reference: https://www.algolia.com/doc/api-reference/api-parameters/paginationLimitedTo/?utm_medium=page_link&utm_source=dashboard&client=javascript
---
After the fix:
> ASAP-606 Fix analytics empty pages

- apps/crn-server/src/controllers/user.controller.ts
The `/users` and `/users/{id}` in the public api use different parsers. In the [#4408](https://github.com/yldio/asap-hub/commit/043f2367efc4253884b5cd4a93565cbaf63832bc) I've added only the role to `/users/{id}` so this PR adds the role for `/users` as well.
---
Link to test it: https://api-4410.hub.asap.science/public/users
> (fix): add role to interest groups in the public api users route

- packages/contentful/src/gp2/queries/user.queries.ts
GP2 Production Values:
- The Working Group with the largest number of members has 40 members.
- The Project with the largest number of members has 16 members.
- The user connected to most working groups is linked to 5 working groups.
- The user connected to most projects is linked to 25 projects.
---
---
Dev: https://dev.gp2.asap.science/users/1I89P3TMz5YPL7aCn58Pjq/overview
PR Hub: https://4418.gp2.asap.science/users/1I89P3TMz5YPL7aCn58Pjq/overview
> ASAP-754 Increase query limits in GP2 for users

- packages/contentful/migrations/crn/discussions/20241016120158-create-discussions.js
- packages/contentful/migrations/crn/messages/20241016114412-create-messages.js
Based on the diagram below, this pr is to create the new content models (discussions & messages). In a subsequent pr I will update the quick checks details fields to reference the `Discussions` model.
> [ASAP-534] - add discussions and messages models

- apps/asap-cli/src/scripts/algolia/performance/engagement.ts
- apps/asap-cli/src/scripts/algolia/performance/tests/engagement.test.ts
- apps/crn-server/src/utils/analytics/engagement.ts
- apps/crn-server/test/fixtures/analytics.fixtures.ts
- apps/crn-server/test/utils/analytics/engagement.test.ts
- packages/react-components/src/molecules/CaptionItem.tsx
- packages/react-components/src/molecules/__tests__/CaptionItem.test.tsx
- packages/react-components/src/organisms/EngagementTable.tsx
- packages/react-components/src/templates/AnalyticsEngagementPageBody.tsx
- **update engagement % counting to use members instead of total speakers**
- **engagement performance uses percentage data**
- **update engagement table to use % for performance comparison**
> Update Engagement analytics logic

- apps/crn-server/src/routes/public/research-output.route.ts
Tested using [this research output in dev](https://app.contentful.com/spaces/5v6w5j61tndm/environments/Development/entries/5e30d8a6-bbab-4688-b826-228b5fdf7ae8). 
In Dev Public API
In PR Public API
> [ASAP-774] - fix public api description field

- packages/react-components/src/icons/index.ts
- packages/react-components/src/icons/success-icon.tsx
- packages/react-components/src/molecules/StatusButton.tsx
- packages/react-components/src/molecules/__tests__/StatusButton.test.tsx
- packages/react-components/src/organisms/ManuscriptCard.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptCard.test.tsx
- Manages different styles and visuals depending on the status of the manuscript and the role of the current user (compliance reviewer or not)
- Expected outcome: [Check on figma](https://www.figma.com/design/zY4fHBAsXCiyW6gGrnS4Yy/CRN-%2F-Design-%2F-Network?node-id=26060-273891&t=RkoV3BRPPPebSuqY-1)
- Acceptance criteria:
1. Confirm the statues are displayed in the above defined colors for Grantees and ASAP Staff on Compliance Summary page
> Asap-544 manage manuscript status colors

- packages/contentful/migrations/crn/users/20241213103301-remove-labs-link-existing-entries.js
Adding an existing linked entry was causing confusion
so we're going to change it to always create a new lab-membership entry
> ASAP-813 Allow only lab membership creation on the CMS

- packages/contentful-app-extensions/membership-reference/src/locations/Field.tsx
- packages/contentful-app-extensions/membership-reference/src/test/locations/Field.test.tsx
- packages/contentful/migrations/crn/users/20241216101304-change-lab-membership-appearance.js
This PR updates the existing `membership-reference` Contentful custom app so it can show labs properly. It also adds a migration so the fields `labs` from `users` uses  `membership-reference` as appearance.
> ASAP-812 Custom app to display lab membership

- apps/gp2-frontend/src/events/__tests__/api.test.ts
- apps/gp2-frontend/src/events/api.ts
This PR makes the events appear in descending event date order. 
This is done by passing a boolean to the `search` function (code reference - https://github.com/yldio/asap-hub/blob/master/packages/algolia/src/client.ts#L232):
Like is done in CRN (code reference - https://github.com/yldio/asap-hub/blob/master/apps/crn-frontend/src/events/api.ts#L30):
---
Before and after this change
> ASAP-810 Reorder Events in GP2 Dashboard

- apps/crn-server/src/data-providers/contentful/manuscript.data-provider.ts
- apps/crn-server/test/data-providers/contentful/manuscript.data-provider.test.ts
- apps/crn-server/test/fixtures/manuscript.fixtures.ts
This PR fixes the issue of teams not being updated in the `Manuscript` content type and the edit updating the last version, but the first one.
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-800
> ASAP-800 Teams and versions updated correctly

- packages/frontend-utils/src/cookie-consent/__tests__/index.test.ts
- packages/frontend-utils/src/cookie-consent/index.ts
[ASAP-817](https://asaphub.atlassian.net/browse/ASAP-817)
[ASAP-817]: https://asaphub.atlassian.net/browse/ASAP-817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ASAP-817 - [CRN][GP2] Cookies - Google Analytics collection issue

- packages/algolia/schema/gp2/algolia-reverse-timestamp-schema.json
- packages/algolia/schema/gp2/algolia-schema.json
- packages/algolia/src/filters.ts
- packages/algolia/test/filters.test.ts
- packages/model/src/event.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-845
This bug happens because the filter `project.id` was missing in the query sent to algolia and in the facet configuration.
---
It's possible to see below that in dev the past events tab is showing events from another project (left side of screenshot) in the PR env it doesn't.
> ASAP-845 Fix GP2 filter event by project

- packages/react-components/src/organisms/ManuscriptCard.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptCard.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-918
---
This PR adds the tabs `Manuscripts and Reports` and `Discussions` to the Manuscript Card.
https://github.com/user-attachments/assets/ee50fd83-8acb-4f20-8b90-a7cdcb643116
The visual changes apart from the tabs are out of the scope of this ticket (ASAP-918). The visual changes are part of this other ticket https://asaphub.atlassian.net/browse/ASAP-924.
> ASAP-918 Display Manuscripts and Discussions in tab view

- packages/contentful/migrations/crn/manuscriptVersions/20250501152002-add-original-version-id-field.js
Looking at the [manuscript sheet provided by ASAP](https://docs.google.com/spreadsheets/d/1x4hpX4-RTcKSqZELBgHQWXxciRZa77Nw-PX4aire7h0/edit?usp=sharing), there are missing manuscripts / manuscript versions. This means that after the migration, some manuscript versions will have different ids (ids refers to the id generated with the team grant id, manuscript count, version count etc). This field will store the original id to help the client cross reference. 
The field should not be editable in the cms
> [ASAP-889] - add original version id field

- apps/crn-server/src/data-providers/contentful/external-author.data-provider.ts
- apps/crn-server/src/data-providers/contentful/reminder.data-provider.ts
- apps/crn-server/test/data-providers/contentful/external-authors.data-provider.test.ts
This pr fixes two issues
- Version mismatch issues when updating an external author https://yld.slack.com/archives/C0258KQR64V/p1747994524507109
To replicate the error:
In Dev try creating a manuscript with an existing external author
- Null manuscript versions when generating manuscript reminders
https://yld.slack.com/archives/C0258KQR64V/p1747947591549309
To replicate the error:
In Dev, add a draft version to a manuscript and publish the manuscript. It should be a manuscript your user should receive reminders for.
> Fix: CRN API Errors

- .github/actions/sls-remove/action.yml
This PR is created to fix the issue of having the newly added secrets as required but not passed down in the sls-remove stage as  shows below:
Similar to what we have in our code base 'n-a' value is passed instead of the actual values since sls-remove doesn't really require those secrets
> Fix: sls remove required env variables

- package.json
- scripts/build-babel.sh
Improves Babel build performance by separating the initial compilation phase from watch mode.
Changes:
- Run initial build sequentially before starting watchers
- Move initial compilation from scripts/build-babel.sh to root package.json
- Use `-j 1` for build phase, then `-j 1000` for watch phase
Benefits:
- Reduces CPU competition during startup
- Prevents system slowdown on less powerful machines
- No significant increase in boot time
- System remains responsive during the initial compilation period (in my computer, this used to take 10 minutes 😁 ).
Technical details:
The `-j 1` parameter controls parallel processes during compilation. This can be adjusted based on machine capabilities, higher values may cause system slowness on weaker hardware.
The change to scripts/build-babel.sh only …
> Improve watch:babel performance by separating build and watch phases
