yldio/asap-hub

- jest-base.config.js
- package.json
> Jest ESLint config improvements

- .yarn/plugins/@yarnpkg/plugin-constraints.js
- .yarn/plugins/@yarnpkg/plugin-typescript.js
- .yarn/plugins/@yarnpkg/plugin-workspace-tools.js
- .yarnrc.yml
> add yarn TypeScript plugin

- .pnp.js
- package.json
- yarn.lock
> clean script

- .gitlab-ci.yml
- serverless.js
> ci: deploy storybook

- ci/tf.sh
> chore: ensure a new workspace is created

- apps/frontend/src/home/Home.css
- apps/frontend/src/home/Home.tsx
- apps/storybook/src/GoogleSigninButton.stories.tsx
- apps/storybook/src/OrcidSigninButton.stories.tsx
- packages/react-components/src/atoms/Button.tsx
- packages/react-components/src/atoms/__tests__/Button.test.tsx
- packages/react-components/src/icons/google-signin-light-normal.tsx
- packages/react-components/src/icons/google.tsx
- packages/react-components/src/icons/orcid.tsx
- packages/react-components/src/organisms/auth/GoogleSigninButton.tsx
- packages/react-components/src/organisms/auth/LoginLogoutButton.tsx
- packages/react-components/src/organisms/auth/OrcidSigninButton.tsx
- packages/react-components/src/organisms/auth/__tests__/GoogleSigninButton.test.tsx
- packages/react-components/src/organisms/auth/__tests__/OrcidSigninButton.test.tsx
- packages/react-components/src/organisms/auth/index.ts
> SSO buttons

- packages/react-components/src/atoms/TextField.tsx
- packages/react-components/src/molecules/LabeledPasswordField.tsx
> feat(text-field): move text slightly down from centre

- apps/storybook/src/text.tsx
- packages/react-components/src/atoms/Display.tsx
- packages/react-components/src/atoms/Divider.tsx
- packages/react-components/src/atoms/Headline2.tsx
- packages/react-components/src/atoms/Headline3.tsx
- packages/react-components/src/atoms/Headline4.tsx
- packages/react-components/src/messages/Welcome.tsx
- packages/react-components/src/messages/__tests__/Welcome.tsx
- packages/react-components/src/molecules/AgreeToTerms.tsx
- packages/react-components/src/molecules/Header.tsx
- packages/react-components/src/templates/Signin.tsx
- packages/react-components/src/text.ts
Most of this is allowing headings to appear styled as a different heading level - so we can match design requirements while still maintaining correct heading level order, yay!
> fix(signin): design improvements

- apps/users-service/src/handlers/fetch-me.ts
- apps/users-service/src/utils/validate-user.ts
- apps/users-service/test/handlers/users.connect-by-code.test.ts
- apps/users-service/test/handlers/users.fetch-by-code.test.ts
- apps/users-service/test/handlers/users.fetch-by-id.test.ts
- apps/users-service/test/handlers/users.fetch-me.test.ts
- apps/users-service/test/helpers/events.ts
> feat: get /me endpoint

- apps/users-service/src/cms/research-outputs.ts
- apps/users-service/src/controllers/research-outputs.ts
- apps/users-service/src/handlers/fetch-research-outputs.ts
- apps/users-service/test/handlers/users.fetch-research-outputs.test.ts
- apps/users-service/test/helpers/create-user.ts
- serverless.js
Depends on #95. Will rebase once merged
> feat: fetch ROMPs endpoint

- apps/storybook/src/Layout.stories.tsx
- apps/storybook/src/Navigation.stories.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/molecules/Navigation.tsx
- packages/react-components/src/molecules/__tests__/Navigation.test.tsx
- packages/react-components/src/molecules/index.ts
- packages/react-components/src/organisms/Layout.tsx
- packages/react-components/src/organisms/__tests__/Layout.test.tsx
Doesn't consider mobile implementation since we don't have specs for it.
> feat: create low fidelity navigation

- apps/storybook/config/preview.jsx
- apps/storybook/src/Profile.stories.tsx
@jeysal we need to schedule some time to go over this.
> fix: wrap profile with router

- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/entities/user.ts
- apps/asap-server/test/helpers/create-user.ts
- apps/frontend/src/users/Profile.tsx
- apps/frontend/src/users/__tests__/Profile.test.tsx
- apps/storybook/src/ProfileBiography.stories.tsx
- apps/storybook/src/ProfileSkills.stories.tsx
- apps/storybook/src/Tag.stories.tsx
- dev/squidex/schemas/users.json
- packages/model/src/user.ts
- packages/react-components/src/atoms/Tag.tsx
- packages/react-components/src/atoms/__tests__/Tag.test.tsx
- packages/react-components/src/atoms/index.ts
- packages/react-components/src/index.ts
- packages/react-components/src/pages/WelcomePage.tsx
- packages/react-components/src/pages/__tests__/WelcomePage.test.tsx
- packages/react-components/src/templates/ProfileSkills.tsx
- packages/react-components/src/templates/index.ts
> feat: add skills to user schema

- apps/asap-server/src/cms/teams.ts
- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/entities/team.ts
- apps/asap-server/src/utils/parse-mjff-csv.ts
- apps/asap-server/test/handlers/teams/fetch.test.ts
- apps/asap-server/test/helpers/create-user.ts
- apps/asap-server/test/helpers/teams.ts
- apps/frontend/src/teams/__tests__/Team.test.tsx
- apps/frontend/src/teams/__tests__/TeamList.test.tsx
- dev/squidex/__json/app.json
- dev/squidex/__json/contents.json
- dev/squidex/__json/rule.json
- dev/squidex/__json/schema.json
- dev/squidex/__json/workflow.json
- dev/squidex/schemas/teams.json
- packages/model/src/team.ts
Closes
===
- https://trello.com/c/xijfDX9W/267-be-create-link-to-proposal-on-team-schema
- https://trello.com/c/yaIKXVpN/269-be-add-property-skills-to-team-schema
Also addresses some chores that were due to be addressed
> feat: add proposalURL and skills to teams

- apps/storybook/src/Avatar.stories.tsx
- apps/storybook/src/ProfileHeader.stories.tsx
- apps/storybook/src/ProfilePage.stories.tsx
- packages/react-components/src/atoms/Avatar.tsx
- packages/react-components/src/atoms/__tests__/Avatar.test.tsx
- packages/react-components/src/templates/ProfileHeader.tsx
> feat(profile): proper Avatar images

- apps/frontend/src/auth/AuthProvider.tsx
- docs/config/auth0.md
This seems to fix it for me on Brave Browser with 3rd party cookie blocking.
Throw your browsers at it, folks! ^^
> fix(auth): session preservation without 3rd party cookies

- apps/storybook/src/ForgotPasswordPage.stories.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/templates/ForgotPasswordPage.tsx
- packages/react-components/src/templates/__tests__/ForgotPasswordPage.test.tsx
- packages/react-components/src/templates/index.ts
Turns out the 'Email Sent' page requires quite a few component library changes, submitting this simple one ahead
> feat: forgot password page design

- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/entities/user.ts
- apps/asap-server/src/utils/assets.ts
- apps/asap-server/test/utils/assets.test.ts
- dev/squidex/schemas/users.json
* Use asset to store avatar (profile picture)
> chore: use asset as avatar

- apps/storybook/src/Card.stories.tsx
- packages/react-components/src/atoms/Card.tsx
- packages/react-components/src/atoms/__tests__/Card.test.tsx
- packages/react-components/src/card.ts
- packages/react-components/src/organisms/PeopleCard.tsx
The first instance of a card that we need to fill up to the edge has appeared...
> refactor(card): normal/min padding => normal/no padding

- packages/services-common/src/squidex/index.ts
- packages/services-common/test/squidex/squidex.test.ts
* changed the pagination default to 8 as per unspoken request
> chore: type squidex search query

- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/test/handlers/teams/fetch-by-id.test.ts
- apps/asap-server/test/handlers/teams/fetch.test.ts
- apps/asap-server/test/handlers/teams/integration.test.ts
https://support.squidex.io/t/filter-by-reference-on-array-returns-400/2406
> fix: use odata on fetch user on teams

- apps/asap-server/src/controllers/users.ts
- apps/asap-server/test/handlers/users/fetch.test.ts
Just tested in dev and I can confirm it's working
> feat: add and to user search

- .gitlab-ci.yml
- package.json
bundlesize is dead and has bugs like 'diff against master' not working anymore at all
> ci: try bundlewatch instead of bundlesize

- apps/storybook/src/Icons.stories.tsx
- apps/storybook/src/ProfileHeader.stories.tsx
- packages/fixtures/src/users.ts
- packages/react-components/src/atoms/Link.tsx
- packages/react-components/src/button.tsx
- packages/react-components/src/icons/edit.tsx
- packages/react-components/src/icons/index.ts
- packages/react-components/src/templates/ProfileHeader.tsx
- packages/react-components/src/templates/__tests__/ProfileHeader.browser-test.tsx
- packages/react-components/src/templates/__tests__/ProfileHeader.test.tsx
This is behind a 'feature flag' in that the props aren't passed yet
> feat(profile-header): edit buttons

- apps/storybook/src/LabeledTextArea.stories.tsx
- packages/react-components/src/atoms/TextArea.tsx
- packages/react-components/src/atoms/TextField.tsx
- packages/react-components/src/atoms/__tests__/TextArea.test.tsx
- packages/react-components/src/molecules/LabeledTextArea.tsx
- packages/react-components/src/molecules/__tests__/LabeledTextArea.test.tsx
also removed minLength since it never worked
> feat(text-area): tip and character count

- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/entities/user.ts
- apps/asap-server/src/handlers/teams/update.ts
- apps/asap-server/src/handlers/users/update.ts
- apps/frontend/src/network/team/Routes.tsx
- apps/frontend/src/network/team/__tests__/Routes.test.tsx
- packages/model/src/team.ts
- packages/model/src/user.ts
- packages/react-components/src/templates/ToolModal.tsx
* move navigation out of component library into frontend
* type the requests
> refactor: edit saving

- apps/storybook/src/flags.tsx
- packages/react-context/src/flags.tsx
- packages/react-context/src/index.ts
idk what I was thinking, this is so much cleaner anyway
> fix(storybook): flag knobs for pages with multiple flags

- packages/react-components/src/molecules/Modal.tsx
- packages/react-components/src/organisms/EditModal.tsx
- packages/react-components/src/organisms/__tests__/EditModal.test.tsx
request cancellation comes later
> feat(edit-modal): save error message

- apps/frontend/src/App.tsx
- apps/frontend/src/auth/CheckAuth.tsx
- apps/frontend/src/content/Content.tsx
- apps/frontend/src/dashboard/Dashboard.tsx
- apps/frontend/src/discover/Discover.tsx
- apps/frontend/src/network/Network.tsx
- apps/frontend/src/network/TeamList.tsx
- apps/frontend/src/network/UserList.tsx
- apps/frontend/src/network/teams/TeamProfile.tsx
- apps/frontend/src/network/users/UserProfile.tsx
- apps/frontend/src/news/Body.tsx
- apps/frontend/src/news/Routes.tsx
- apps/frontend/src/shared-research/ResearchOutput.tsx
- apps/frontend/src/shared-research/ResearchOutputList.tsx
- apps/frontend/src/shared-research/Routes.tsx
- apps/storybook/src/Loading.stories.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/molecules/Loading.tsx
- packages/react-components/src/molecules/__tests__/Loading.test.tsx
- packages/react-components/src/molecules/index.ts
- packages/react-components/src/templates/Layout.tsx
before this gets completely out of hand...
> refactor: extract Loading component

- apps/storybook/src/TabNav.stories.tsx
- packages/react-components/src/molecules/TabNav.tsx
- packages/react-components/src/molecules/__tests__/TabNav.test.tsx
- packages/react-components/src/templates/UserProfileHeader.tsx
Separate PR, the main one for the ticket comes tomorrow.
Will have to discuss this one with James a bit, the scrollbar is a bit weird 😅
> feat(tab-nav): support horizontal overflow

- apps/storybook/src/TagList.stories.tsx
- packages/react-components/src/molecules/TagList.tsx
- packages/react-components/src/molecules/__tests__/TagList.browser-test.tsx
- packages/react-components/src/molecules/__tests__/TagList.test.tsx
- packages/react-components/src/organisms/TeamCard.tsx
managed to split out another thing that can be merged into master as-is
> refactor(tag-list): support custom mobile/desktop tag limits

- apps/frontend/src/network/Network.tsx
- apps/frontend/src/network/routes.ts
- apps/storybook/src/Icons.stories.tsx
- apps/storybook/src/NetworkHeader.stories.tsx
- apps/storybook/src/NetworkPage.stories.tsx
- packages/react-components/src/icons/groups.tsx
- packages/react-components/src/icons/index.ts
- packages/react-components/src/molecules/TabNav.tsx
- packages/react-components/src/templates/NetworkPageHeader.tsx
- packages/react-components/src/templates/__tests__/NetworkPage.test.tsx
- packages/react-components/src/templates/__tests__/NetworkPageHeader.test.tsx
split this one out to be reviewed already
> feat(network): groups tab

- apps/asap-server/test/handlers/dashboard/fetch.test.ts
- apps/asap-server/test/handlers/discover/fetch.test.ts
- apps/asap-server/test/handlers/groups/fetch-by-team-id.test.ts
- apps/asap-server/test/handlers/groups/fetch.test.ts
- apps/asap-server/test/handlers/news-and-events/fetch-by-id.test.ts
- apps/asap-server/test/handlers/news-and-events/fetch.test.ts
- apps/asap-server/test/handlers/research-outputs/fetch-by-id.test.ts
- apps/asap-server/test/handlers/research-outputs/fetch.test.ts
- apps/asap-server/test/handlers/teams/fetch-by-id.test.ts
- apps/asap-server/test/handlers/teams/fetch.test.ts
- apps/asap-server/test/handlers/teams/integration.test.ts
- apps/asap-server/test/handlers/teams/update.test.ts
- apps/asap-server/test/handlers/users/fetch-by-id.test.ts
- apps/asap-server/test/handlers/users/fetch.test.ts
- apps/asap-server/test/handlers/users/integration.test.ts
- apps/asap-server/test/handlers/users/update-avatar.test.ts
- apps/asap-server/test/handlers/users/update.test.ts
- apps/asap-server/test/handlers/webhooks/webhook-connect.test.ts
- apps/asap-server/test/handlers/webhooks/webhook-fetch-by-code.test.ts
- apps/asap-server/test/handlers/webhooks/webhook-sync-orcid.test.ts
- apps/asap-server/test/helpers/events.ts
- apps/asap-server/test/utils/instrumentation.test.ts
This PR updates the parameter type in the handler event generator (for tests) and fixes the errors that the correct type reveals.
> fix: handler event helper

- apps/storybook/src/GroupProfileHeader.stories.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/templates/GroupProfileHeader.tsx
- packages/react-components/src/templates/__tests__/GroupProfileHeader.test.tsx
- packages/react-components/src/templates/index.ts
> feat(react-components): Group Header

- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/utils/types.ts
- apps/asap-server/test/controllers/users.test.ts
- apps/asap-server/test/fixtures/orcid.fixtures.ts
- apps/asap-server/test/fixtures/users.fixtures.ts
- apps/asap-server/test/handlers/users/fetch.test.ts
- apps/asap-server/test/handlers/users/update.test.ts
Because this PR will become massive if I move all the endpoints at once, I'm only moving the controller tests for now. 
This PR also fixes a bug with the user search, bug I caught while migrating the endpoint.
> feat: migrates user controller tests and fix search

- apps/asap-server/src/app.ts
- apps/asap-server/src/controllers/calendars.ts
- apps/asap-server/src/routes/calendars.route.ts
- apps/asap-server/test/controllers/calendars.test.ts
- apps/asap-server/test/mocks/calendar-controller.mock.ts
- apps/asap-server/test/routes/calendars.test.ts
- serverless.js
see: https://trello.com/c/N4pVs7i0/938-migrate-calendars-to-express-handler
> feat: Move /calendars to express handler

- apps/asap-server/src/app.ts
- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/routes/research-outputs.route.ts
- apps/asap-server/test/controllers/dashboard.test.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/mocks/research-outputs-controller.mock.ts
- apps/asap-server/test/routes/research-outputs.test.ts
- apps/asap-server/test/routes/teams.test.ts
- serverless.js
See: https://trello.com/c/tI403YCo/939-migrate-research-outputs-to-express-handler
> feat: Move /research-outputs to express handler

- apps/asap-server/src/app.ts
- apps/asap-server/src/controllers/pages.ts
- apps/asap-server/src/routes/pages.route.ts
- apps/asap-server/test/controllers/pages.test.ts
- apps/asap-server/test/mocks/page-controller.mock.ts
- apps/asap-server/test/routes/pages.test.ts
- serverless.js
https://trello.com/c/jUIGpU4D/941-migrate-pages-to-express-handler
> feat: Move /pages to express handler

- apps/storybook/src/GroupProfilePage.stories.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/templates/ContentPage.tsx
- packages/react-components/src/templates/DashboardPage.tsx
- packages/react-components/src/templates/DashboardPageHeader.tsx
- packages/react-components/src/templates/DiscoverPage.tsx
- packages/react-components/src/templates/DiscoverPageHeader.tsx
- packages/react-components/src/templates/EventsPage.tsx
- packages/react-components/src/templates/EventsPageHeader.tsx
- packages/react-components/src/templates/GroupProfileHeader.tsx
- packages/react-components/src/templates/GroupProfilePage.tsx
- packages/react-components/src/templates/Layout.tsx
- packages/react-components/src/templates/NetworkPage.tsx
- packages/react-components/src/templates/NetworkPageHeader.tsx
- packages/react-components/src/templates/NewsAndEventsPage.tsx
- packages/react-components/src/templates/NewsAndEventsPageHeader.tsx
- packages/react-components/src/templates/NewsOrEventPage.tsx
- packages/react-components/src/templates/ResearchOutputPage.tsx
- packages/react-components/src/templates/SharedResearchPage.tsx
- packages/react-components/src/templates/SharedResearchPageHeader.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- packages/react-components/src/templates/TeamProfilePage.tsx
- packages/react-components/src/templates/UserProfileHeader.tsx
- packages/react-components/src/templates/UserProfilePage.tsx
- packages/react-components/src/templates/__tests__/GroupProfilePage.test.tsx
- packages/react-components/src/templates/index.ts
and fix GroupProfile{Header,Page} TODO
> refactor(react-components): default layout content to stretch

- apps/asap-server/src/app.ts
- apps/asap-server/src/controllers/news-and-events.ts
- apps/asap-server/src/routes/news-and-events.route.ts
- apps/asap-server/test/controllers/news-and-events.test.ts
- apps/asap-server/test/fixtures/news-and-events.fixtures.ts
- apps/asap-server/test/handlers/dashboard/fetch.test.ts
- apps/asap-server/test/handlers/news-and-events/fetch.test.ts
- apps/asap-server/test/mocks/news-and-events-controller.mock.ts
- apps/asap-server/test/routes/news-and-events.test.ts
- serverless.js
https://trello.com/c/ZNtPc999/942-migrate-news-and-events-to-express-handler
> feat: Move /news-and-events to express handler

- apps/asap-server/src/app.ts
- apps/asap-server/src/controllers/discover.ts
- apps/asap-server/src/routes/discover.route.ts
- apps/asap-server/test/controllers/discover.test.ts
- apps/asap-server/test/fixtures/discover.fixtures.ts
- apps/asap-server/test/mocks/discover-controller.mock.ts
- apps/asap-server/test/routes/discover.test.ts
- serverless.js
see: https://trello.com/c/LPl2c6Xu/943-migrate-discover-to-express-handler
> feat: Move /discover to express handler

- tsconfig.json
Updates the compilation target in tsconfig to e2015 which is node 12 compatible.
> fix: local server node version fix

- apps/asap-server/src/entities/group.ts
- apps/asap-server/src/entities/user.ts
- apps/asap-server/src/utils/squidex.ts
- packages/squidex/src/entities/user.ts
https://support.squidex.io/t/arrays-with-nested-references-convert-null-values-to-null/2892
https://trello.com/c/VA1BAQSi/964-bug-null-returned-from-from-user-by-id-endpoint
> fix: remove nulls from user response

- apps/asap-server/src/controllers/events.ts
- apps/asap-server/src/routes/events.route.ts
- apps/asap-server/test/controllers/events.test.ts
- apps/asap-server/test/fixtures/events.fixtures.ts
- apps/asap-server/test/mocks/event-controller.mock.ts
- apps/asap-server/test/routes/events.test.ts
see: https://trello.com/c/7QGsDOAB/925-create-an-endpoint-to-return-event-details-on-the-asap-hub-events-id
> feat: Create /events/{event_id} endpoint

- apps/asap-server/src/app.ts
- apps/asap-server/src/controllers/events.ts
- apps/asap-server/src/routes/events.route.ts
- apps/asap-server/src/routes/groups.route.ts
- apps/asap-server/test/controllers/events.test.ts
- apps/asap-server/test/routes/groups.test.ts
https://trello.com/c/gNDGwSjm/930-create-an-endpoint-to-return-the-events-on-the-asap-hub-groups-id-events
> feat: Create `/groups/{groupId}/events` endpoint

- apps/asap-server/src/handlers/webhooks/webhook-sync-calendar.ts
- apps/asap-server/src/handlers/webhooks/webhook-sync-orcid.ts
- apps/asap-server/test/fixtures/orcid.fixtures.ts
- apps/asap-server/test/handlers/webhooks/webhook-sync-calendar.fixtures.ts
- apps/asap-server/test/handlers/webhooks/webhook-sync-calendar.test.ts
- apps/asap-server/test/handlers/webhooks/webhook-sync-orcid.fixtures.ts
- apps/asap-server/test/handlers/webhooks/webhook-sync-orcid.test.ts
- packages/squidex/schema/rules/rule1.json
- packages/squidex/src/entities/calendar.ts
- packages/squidex/src/entities/event.ts
- packages/squidex/src/entities/group.ts
- packages/squidex/src/entities/index.ts
- packages/squidex/src/entities/news-or-event.ts
- packages/squidex/src/entities/page.ts
- packages/squidex/src/entities/research-output.ts
- packages/squidex/src/entities/team.ts
- packages/squidex/src/entities/user.ts
- packages/squidex/src/entities/webhook.ts
https://trello.com/c/tVNbQr5t/988-subscribe-to-changes-on-squidex-calendar-collection
TODO:
> feat: squidex calendar webhook

- serverless.js
> feat: add serverless handler

- apps/frontend/src/welcome/Welcome.tsx
- apps/frontend/src/welcome/__tests__/Welcome.test.tsx
The registration flow is broken. Removing the preventive validation to enable users to register.
> feat: remove welcome invite validation

- apps/frontend/src/network/teams/api.ts
This PR fixes an issue we are having in prod. If the FE wants to improve coverage, feel free to add tests. :+1:
> fix: set content type header on patch request

- apps/storybook/src/EventCard.stories.tsx
- apps/storybook/src/EventInfo.stories.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/molecules/EventInfo.tsx
- packages/react-components/src/molecules/__tests__/EventInfo.test.tsx
- packages/react-components/src/molecules/index.ts
- packages/react-components/src/organisms/EventCard.tsx
- packages/react-components/src/organisms/__tests__/EventCard.test.tsx
Also threw in a component extraction I need for my ticket already
- refactor(react-components): split EventInfo out of EventCard
- fix(event-info): multi group behavior
- fix(event-info): show end day if different from start day
> event fixes, multi commit, do not squash

- apps/asap-server/src/controllers/events.ts
- apps/asap-server/src/controllers/groups.ts
- apps/asap-server/src/entities/event.ts
- apps/asap-server/src/routes/events.route.ts
- apps/asap-server/test/controllers/events.test.ts
- apps/asap-server/test/fixtures/events.fixtures.ts
- apps/asap-server/test/routes/events.route.test.ts
- packages/squidex/src/entities/calendar.ts
see: https://trello.com/c/WiQBClcy/1023-add-groups-to-event-response
> feat: Add groups to event response

- .pnp.js
- apps/asap-server/src/entities/event.ts
- apps/frontend/package.json
- apps/frontend/src/events/Event.tsx
- apps/frontend/src/events/Events.tsx
- apps/frontend/src/events/Upcoming.tsx
- apps/frontend/src/events/__tests__/Event.test.tsx
- apps/frontend/src/events/state.ts
- apps/storybook/src/JoinEvent.stories.tsx
- packages/eslint-config-asap-hub/index.js
- packages/model/package.json
- packages/model/src/event.ts
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/JoinEvent.tsx
- packages/react-components/src/organisms/__tests__/JoinEvent.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/EventPage.tsx
- packages/react-components/src/templates/__tests__/EventPage.test.tsx
- yarn.lock
I haven't figured out what's going on with the fake timers, so we may need to merge this and I sort out the tests later
> feat(event): join event section

- apps/asap-server/src/controllers/events.ts
- apps/asap-server/src/controllers/groups.ts
- apps/asap-server/src/entities/event.ts
- apps/asap-server/src/entities/group.ts
- apps/asap-server/src/entities/news-and-events.ts
- apps/asap-server/test/controllers/events.test.ts
- apps/asap-server/test/fixtures/events.fixtures.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/storybook/src/EventInfo.stories.tsx
- packages/model/src/event.ts
- packages/model/src/group.ts
- packages/react-components/src/icons/event-placeholder.tsx
- packages/react-components/src/molecules/EventInfo.tsx
- packages/react-components/src/molecules/__tests__/EventInfo.test.tsx
- packages/squidex/schema/schemas/events.json
- packages/squidex/schema/schemas/groups.json
- packages/squidex/src/entities/event.ts
- packages/squidex/src/entities/group.ts
https://trello.com/c/C4S4plSK/1011-event-thumbnails
> feat: add thumbnail information to event

- apps/asap-server/src/controllers/events.ts
- apps/asap-server/src/utils/sync-google-calendar.ts
- apps/asap-server/src/utils/sync-google-event.ts
- apps/asap-server/test/controllers/calendars.test.ts
- apps/asap-server/test/controllers/events.test.ts
- apps/asap-server/test/fixtures/events.fixtures.ts
- apps/asap-server/test/mocks/event-controller.mock.ts
- apps/asap-server/test/utils/sync-google-calendar.test.ts
- apps/asap-server/test/utils/sync-google-event.test.ts
- packages/squidex/schema/schemas/events.json
- packages/squidex/src/entities/event.ts
https://trello.com/c/aHO7UP9B/1047-add-missing-events-to-the-hub
> feat: add googleID to events

- apps/storybook/src/EventCard.stories.tsx
- apps/storybook/src/EventInfo.stories.tsx
- apps/storybook/src/EventNotes.stories.tsx
- apps/storybook/src/JoinEvent.stories.tsx
- apps/storybook/src/NewsAndEventsCard.stories.tsx
- apps/storybook/src/NewsAndEventsPage.stories.tsx
- apps/storybook/src/NewsAndEventsPageBody.stories.tsx
- apps/storybook/src/NewsOrEventPage.stories.tsx
- packages/fixtures/src/events.ts
- packages/model/src/event.ts
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/EventNotes.tsx
- packages/react-components/src/organisms/__tests__/EventNotes.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/EventPage.tsx
- packages/react-components/src/templates/__tests__/EventPage.test.tsx
(Backend does not deliver them yet)
> feat(react-components): show event notes

- packages/squidex/schema/schemas/events.json
https://trello.com/c/eEw8BLgb/1063-admin-improvements-on-cms-for-events
> chore: add separators and order fields to event schema

- apps/asap-server/src/controllers/calendars.ts
- apps/asap-server/src/handlers/jobs/resubscribe-calendars.ts
- apps/asap-server/src/handlers/webhooks/webhook-calendar-created.ts
- apps/asap-server/src/utils/types.ts
- apps/asap-server/test/controllers/calendars.test.ts
- apps/asap-server/test/fixtures/calendars.fixtures.ts
- apps/asap-server/test/handlers/jobs/resubscribe-calendars.test.ts
- apps/asap-server/test/handlers/webhooks/webhook-calendar-created.test.ts
- apps/asap-server/test/helpers/events.ts
- apps/asap-server/test/mocks/calendar-controller.mock.ts
- packages/squidex/schema/schemas/calendars.json
- packages/squidex/src/entities/calendar.ts
- packages/squidex/src/squidex.ts
- serverless.js
see: https://trello.com/c/YCqoAePq/1024-add-a-cron-job-to-resubscribe-to-calendar-event-changes
> feat: Add a scheduled job to resubscribe the calendars

- apps/frontend/src/network/groups/__tests__/GroupList.test.tsx
- apps/storybook/src/EventCard.stories.tsx
- apps/storybook/src/EventInfo.stories.tsx
- apps/storybook/src/EventTime.stories.tsx
- apps/storybook/src/date.ts
- packages/fixtures/src/events.ts
- packages/fixtures/src/groups.ts
- packages/react-components/src/__tests__/date.test.ts
- packages/react-components/src/date.ts
- packages/react-components/src/index.ts
- packages/react-components/src/molecules/EventInfo.tsx
- packages/react-components/src/molecules/EventTime.tsx
- packages/react-components/src/molecules/__tests__/EventInfo.test.tsx
- packages/react-components/src/molecules/__tests__/EventTime.test.tsx
- packages/react-components/src/molecules/index.ts
and extract EventTime component
> feat(event-info): show original time zones

- ci/.gitlab-ci.squidex.yml
This PR fixes the sync squidex schema job:
- Previously: ❌ https://gitlab.com/yldio/asap-hub/-/jobs/1086893776
- Now: ✅  https://gitlab.com/yldio/asap-hub/-/jobs/1087090573
> fix(devops): fix sync script

- apps/asap-server/test/controllers/events.test.ts
- packages/squidex/schema/schemas/events.json
https://trello.com/c/HST5YU8n/1093-additional-meeting-materials-is-not-returning-all-additional-meeting-materials-to-fe
> feat: http(s) required in url

- apps/asap-server/src/app.ts
The code is open source, but still ¯\_(ツ)_/¯
> chore: disable express header

- .github/workflows/sls_teardown.yml
- .gitlab-ci.yml
Here is an example of a successful execution of this action: 
https://github.com/yldio/asap-hub/actions/runs/655679124
> feat(devops): free branch resources when PR is merged

- apps/asap-server/src/controllers/events.ts
- apps/asap-server/src/entities/event.ts
- packages/model/src/event.ts
- packages/squidex/schema/schemas/events.json
- packages/squidex/src/entities/event.ts
https://trello.com/c/LvoyDaov/1081-remove-label-fields-from-additional-meeting-materials-be-and-cms
> fix(events): remove label from meeting details

- apps/asap-server/src/controllers/calendars.ts
- apps/asap-server/src/handlers/webhooks/webhook-calendar-created.ts
- apps/asap-server/src/handlers/webhooks/webhook-events-updated.ts
- apps/asap-server/src/middleware/error-handler.ts
- apps/asap-server/src/utils/instrumented-framework.ts
- apps/asap-server/src/utils/sync-google-event.ts
- apps/asap-server/test/middleware/error-handler.test.ts
Rearranges most of the log parameter order to include all of the data in the logs, as per documentation: https://github.com/pinojs/pino/blob/master/docs/api.md#error
> chore: Improve logging 

- apps/asap-server/src/utils/sync-google-calendar.ts
Reverses order of parameters in order to adhere to the logging library input
> chore: Improve event logging

- packages/react-components/src/atoms/Avatar.tsx
- packages/react-components/src/card.ts
- packages/react-components/src/molecules/EventInfo.tsx
- packages/react-components/src/organisms/NewsAndEventsCard.tsx
- packages/react-components/src/organisms/NewsAndEventsSection.tsx
- packages/react-components/src/organisms/PageCard.tsx
- packages/react-components/src/organisms/PagesSection.tsx
- packages/react-components/src/templates/DashboardPageBody.tsx
This PR applies the following changes:
- https://trello.com/c/0wj3BE42/1026-header-profile-image-component
- https://trello.com/c/cyPb0idA/1027-dashboard-discover-asap-card-component
- https://trello.com/c/nN27oHQe/1028-dashboard-discover-page
- https://trello.com/c/JtR8pGxZ/1029-square-image-component
> feat: minor design changes

- apps/frontend/src/events/Events.tsx
- apps/frontend/src/hooks/__tests__/search.test.ts
- apps/frontend/src/hooks/search.ts
- apps/frontend/src/network/Network.tsx
- apps/frontend/src/network/groups/GroupProfile.tsx
- apps/frontend/src/shared-research/Routes.tsx
> refactor(frontend): pull debouncedSearchQuery into useSearch hook

- packages/flags/src/index.ts
- packages/react-components/src/templates/EventsPageHeader.tsx
- packages/react-components/src/templates/GroupProfileHeader.tsx
- packages/react-components/src/templates/__tests__/EventsPageHeader.test.tsx
- packages/react-components/src/templates/__tests__/GroupProfileHeader.test.tsx
different branch, maybe this will finally be run by CI 🙈
> refactor: remove event flags

- packages/squidex/schema/schemas/calendars.json
- packages/squidex/schema/schemas/events.json
- Fixing this since I noticed they were not required during calendar creation.
- Also added some UI separators to improve UX 👨🏽‍🎨
> fix: make calendar props required

- apps/storybook/src/EventMaterials.stories.tsx
- packages/react-components/src/__tests__/date.test.ts
- packages/react-components/src/atoms/Card.tsx
- packages/react-components/src/date.ts
- packages/react-components/src/molecules/EventMaterialComingSoon.tsx
- packages/react-components/src/molecules/EventMaterialUnavailable.tsx
- packages/react-components/src/molecules/__tests__/EventMaterialUnavailable.test.tsx
- packages/react-components/src/molecules/index.ts
- packages/react-components/src/organisms/EventMaterials.tsx
- packages/react-components/src/organisms/JoinEvent.tsx
- packages/react-components/src/organisms/__tests__/EventMaterials.test.tsx
- packages/react-components/src/templates/__tests__/EventPage.test.tsx
- packages/react-components/src/templates/__tests__/GroupProfileAbout.test.tsx
and surface any material status only on past events
> feat(events): surface unavailable material status

- packages/react-components/src/organisms/NewsAndEventsCard.tsx
- packages/react-components/src/organisms/ResultList.tsx
- packages/react-components/src/organisms/SearchAndFilter.tsx
- packages/react-components/src/organisms/TeamCard.tsx
- packages/react-components/src/organisms/UserProfileBackground.tsx
- fix: spacing on the team card members value
- fix: padding on news and events card's figure
- fix: remove padding from result header
- fix: filter dropdown padding and margin
- fix: spacing of details in the profile page
> Fix: spacing issues

- apps/auth-frontend/src/login/__tests__/Login.test.tsx
- apps/frontend/src/welcome/__tests__/Welcome.test.tsx
- packages/react-components/src/templates/SigninForm.tsx
- packages/react-components/src/templates/WelcomePage.tsx
- packages/react-components/src/templates/__tests__/SigninForm.test.tsx
- packages/react-components/src/templates/__tests__/WelcomePage.test.tsx
Copy changes for clarity's sake.
Test updates to match new copy.
> fix: update copy on Welcome and SigninForm pages

- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
see: https://trello.com/c/sjAnbB2y/1153-make-tags-searchable-on-research-outputs
> feat: Make tags searchable

- packages/react-components/src/atoms/Avatar.tsx
- packages/react-components/src/button.tsx
- packages/react-components/src/organisms/TeamProfileOverview.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- updates the heading styles
- changes the way team members are displayed
- updates buttons disabled state
> feat: team page styling update

- packages/squidex/schema/schemas/labs.json
- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/schema/schemas/users.json
Creates the schema for labs as well as relationship with users and research-outputs.
see: https://trello.com/c/Ly0oEF8s/1131-create-labs
> feat: Create Labs entity

- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/src/entities/research-output.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- apps/asap-server/test/routes/research-outputs.route.test.ts
- apps/frontend/src/shared-research/__tests__/ResearchOutput.test.tsx
- apps/frontend/src/shared-research/__tests__/Routes.test.tsx
- packages/fixtures/src/research-outputs.ts
- packages/model/src/research-output.ts
- packages/squidex/src/entities/research-output.ts
see: https://trello.com/c/p7j5BZl7/1127-add-tags-to-research-output-response
> feat: Add tags to research outputs response

- apps/storybook/src/SearchAndFilter.stories.tsx
- packages/model/src/research-output.ts
- packages/react-components/src/organisms/SharedResearchCard.tsx
- packages/react-components/src/templates/SharedResearchPageHeader.tsx
Ticket: https://trello.com/c/H9FxenFD/1161-add-shared-output-filter-options
> feat(ROMS): enable all ROMS types and filters on FE

- packages/squidex/schema/schemas/users.json
This improvement is not tracked on a ticket. This was a request from B from the morning before the sprint started.
> chore(users): improve cms user schema UI

- serverless.js
Ticket: https://trello.com/c/fbEazk54/1046-move-secrets-from-ci-to-secrets-manager
> chore(devops): move env vars to SSM

- packages/squidex/schema/schemas/research-outputs.json
https://trello.com/c/H9FxenFD/1161-add-shared-output-filter-options
> fix(roms): add types to CMS schema

- ci/.gitlab-ci.squidex.yml
- ci/integration/Dockerfile
- dev/Dockerfile
Ticket: https://trello.com/c/NeQ0WKpk/1165-fix-squidex-app-rules-synchronisation
Synchronisation working back again. 
I've reverted the pipeline config to only sync on merge to master, like it should.
> fix(rules): try syncing rules

- apps/asap-cli/src/import/protocols/insert.ts
- apps/asap-cli/src/invite/index.ts
- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/entities/news-and-events.ts
- apps/asap-server/src/entities/user.ts
- apps/asap-server/test/controllers/news-and-events.test.ts
- apps/asap-server/test/helpers/users.ts
- packages/squidex/src/entities/common.ts
fixes: https://trello.com/c/iXZzQCel/1223-%F0%9F%90%9B-bug-news-listing
> fix: News and events thumbnail null bug

- ci/.gitlab-ci.squidex.yml
- packages/squidex/schema/schemas/research-outputs.json
Ticket: https://trello.com/c/Zk49QfyC/1185-change-the-field-original-publish-date-on-the-cms
> feat(publishDate): make publishDate a date picker

- apps/asap-cli/src/cli.ts
- apps/asap-cli/src/invite/index.ts
- apps/asap-cli/test/invite.test.ts
see: https://trello.com/c/hU9PRAES/1179-invitation-script-should-invite-any-user-irrespective-of-role
> feat: Make role optional in the invite script

- apps/storybook/src/Modal.stories.tsx
- packages/react-components/src/molecules/Modal.tsx
- packages/react-components/src/molecules/ModalEditHeader.tsx
- packages/react-components/src/organisms/EditModal.tsx
* divider line
* scrolling body
* height cap
> feat(modal): layout changes

- apps/storybook/src/SearchAndFilter.stories.tsx
- packages/react-components/src/analytics.ts
- packages/react-components/src/molecules/SearchField.tsx
- packages/react-components/src/molecules/__tests__/SearchField.test.tsx
- packages/react-components/src/organisms/Filter.tsx
- packages/react-components/src/organisms/SearchAndFilter.tsx
- packages/react-components/src/organisms/__tests__/Filter.test.tsx
- packages/react-components/src/organisms/__tests__/SearchAndFilter.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/GoogleTagManager.tsx
- packages/react-components/src/templates/SharedResearchPage.tsx
- packages/react-components/src/templates/SharedResearchPageHeader.tsx
Recommend reviewing the two commits separately:
- refactor(react-components): extract Filter out of SearchAndFilter
- feat(filter): analytics
> feat(filter): analytics

- .dockerignore
- dev/Dockerfile
- dev/README.md
- dev/docker-compose.yaml
- dev/fixtures/user.json
- dev/setup-squidex.sh
- package.json
Ticket: https://trello.com/c/WH7OSCwI/1190-integration-tests-local-setup
> fix(local-setup): simplify local squidex setup

- packages/squidex/schema/schemas/research-outputs.json
https://trello.com/c/Yr0RMItd/1129-as-an-admin-i-want-to-associate-research-outputs-with-users
* does involve any code changes as per requirements
> feature: Add authors to research-output schema

- .github/workflows/backups.yml
Missing requirement for: https://trello.com/c/1oHlF3sU/1204-create-and-store-dev-squidex-data-dump
> feat(gh-actions): trigger dev backup once a day

- .github/workflows/dev.backup.yml
- .github/workflows/prod.backup.yml
- serverless.ts
Ticket: https://trello.com/c/cBQQw8Uy/1226-create-and-store-prod-squidex-data-dump
The expire policy on the bucket applies to `dev` which makes sense. 
**Before merging, the branch condition has to be removed from cloudformation**
> feat(actions): backup prod action

- apps/asap-cli/src/import/protocols/insert.ts
- apps/asap-cli/test/import/protocols.fixture.ts
- apps/asap-server/src/migrations/1620402284-default-fields-roms.ts
- packages/model/src/common.ts
- packages/model/src/research-output.ts
- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/src/entities/research-output.ts
Ticket: https://trello.com/c/gK3a6puv/1132-update-roms-schema
Not adding a rollback script since it doesn't make sense here.
Rolling back in the future would just be dangerous as it would delete data.
> feat(roms): add new fields and adds defauls migration

- apps/asap-cli/src/invite/index.ts
- apps/asap-cli/test/invite.fixtures.ts
- apps/asap-cli/test/invite.test.ts
completes the last requirement of: https://trello.com/c/hU9PRAES/1179-invitation-script-should-invite-any-user-irrespective-of-role
> feat: Add teams to user invite script

- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/entities/research-output.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/controllers/teams.test.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- apps/asap-server/test/routes/research-outputs.route.test.ts
- apps/storybook/src/SharedResearchOutput.stories.tsx
- packages/model/src/research-output.ts
- packages/react-components/src/templates/SharedResearchOutput.tsx
- packages/react-components/src/templates/__tests__/SharedResearchOutput.test.tsx
- packages/squidex/src/entities/research-output.ts
https://trello.com/c/cjxPPXMc/1231-show-access-instructions-card-on-an-output-details-page
> feat(shared-research-output): access instructions

- apps/asap-cli/src/cli.ts
- apps/asap-cli/src/import/protocols/insert.ts
- apps/asap-cli/src/import/users/insert.ts
- apps/asap-cli/src/invite/index.ts
- apps/asap-cli/src/logger.ts
- apps/asap-cli/test/invite.test.ts
- packages/squidex/src/squidex.ts
Ticket: https://trello.com/c/hU9PRAES/1179-invitation-script-should-invite-any-user-irrespective-of-role
> fix(asap-cli): use array for ids, add error handling

- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/entities/research-output.ts
- apps/asap-server/src/entities/team.ts
- apps/asap-server/src/utils/types.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/research-output.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- apps/asap-server/test/routes/research-outputs.route.test.ts
- packages/fixtures/src/research-outputs.ts
- packages/fixtures/src/users.ts
- packages/model/src/research-output.ts
- packages/squidex/src/entities/research-output.ts
For https://trello.com/c/dUrWu11Q/1230-show-authors-on-an-output-detail-page
No proper backend impl, just fixed type errors
> feat(model): research output authors

- packages/react-components/src/templates/ContactInfoModal.tsx
https://trello.com/c/Z7ryz5Vd/1263-edit-my-profile-change-copy-in-modal
> Copy change

- packages/react-components/src/__tests__/utils.test.tsx
- packages/react-components/src/atoms/Anchor.tsx
- packages/react-components/src/atoms/NavigationLink.tsx
- packages/react-components/src/utils.ts
https://trello.com/c/DYDrU6ww/1108-on-rtf-hyperlinks-starting-with-https-are-not-working-fe
> Fix problems with internal absolute urls

- apps/frontend/src/network/users/__tests__/UserProfile.test.tsx
> fix: FE component formatting error

- .gitlab-ci.yml
- packages/squidex/schema/__json/schema.json
- packages/squidex/schema/schemas/research-outputs.json
Ticket: https://trello.com/c/ef7Mw780/1237-reorder-cms-fields-for-research-outputs
- feat(CI): apply schema to PR squidex app
- chore(RO): change RO fields order
> chore(RO): change RO fields order

- apps/asap-server/test/fixtures/users.fixtures.ts
- apps/asap-server/test/integration/fetch-users.integration-test.ts
- apps/storybook/src/PeopleCard.stories.tsx
- apps/storybook/src/UserProfilePage.stories.tsx
- packages/model/src/user.ts
- packages/react-components/src/templates/PersonalInfoModal.tsx
- packages/react-components/src/templates/__tests__/PersonalInfoModal.test.tsx
- packages/squidex/schema/schemas/users.json
https://trello.com/c/2VPjYAXj/1293-update-the-degrees-list
> feat: Update the degree list

- apps/storybook/src/UserProfileRecentWorks.stories.tsx
- packages/react-components/src/icons/external-link.tsx
- packages/react-components/src/organisms/UserProfileRecentWorks.tsx
- packages/react-components/src/organisms/__tests__/UserProfileRecentWorks.test.tsx
- packages/react-components/src/templates/UserProfileAbout.tsx
- packages/react-components/src/templates/__tests__/UserProfileAbout.test.tsx
https://trello.com/c/Edup6vrT/1224-orcid-empty-state
> Orcid empty state

- packages/react-components/src/atoms/Card.tsx
- packages/react-components/src/atoms/TagLabel.tsx
- packages/react-components/src/molecules/TabNav.tsx
- packages/react-components/src/organisms/AdditionalMaterials.tsx
- packages/react-components/src/organisms/ResultList.tsx
- packages/react-components/src/organisms/SharedResearchOutputHeaderCard.tsx
- packages/react-components/src/templates/SharedResearchOutput.tsx
https://trello.com/c/RwcwXNgV/1328-add-ellipsis-to-type-and-subtype-and-introduce-layout-limitations
> feat(react-components): various small design fixes

- apps/storybook/src/SharedResearchOutput.stories.tsx
- apps/storybook/src/UsersList.stories.tsx
- packages/model/src/research-output.ts
- packages/react-components/src/molecules/TeamsList.tsx
- packages/react-components/src/molecules/UsersList.tsx
- packages/react-components/src/molecules/__tests__/UsersList.test.tsx
https://trello.com/c/bYYP5wQK/1250-add-external-authors-to-roms-on-detail-page
> Feat: External Authors

- apps/storybook/src/UserProfilePage.stories.tsx
- packages/react-components/src/icons/github.tsx
- packages/react-components/src/icons/globe.tsx
- packages/react-components/src/icons/google-scholar.tsx
- packages/react-components/src/icons/linked-in.tsx
- packages/react-components/src/icons/orcid-social.tsx
- packages/react-components/src/icons/research-gate.tsx
- packages/react-components/src/icons/researcher-id.tsx
- packages/react-components/src/icons/twitter.tsx
- packages/react-components/src/molecules/SocialIcons.tsx
- packages/react-components/src/molecules/__tests__/SocialIcons.test.tsx
- packages/react-components/src/templates/UserProfileHeader.tsx
- packages/react-components/src/templates/__tests__/UserProfileHeader.test.tsx
https://trello.com/c/ZGYvylID/1300-surface-website-1-and-website-2-on-user-profile
> Feat: Website 1 & 2 for social icons

- apps/frontend/src/shared-research/__tests__/ResearchOutput.test.tsx
- packages/react-components/src/templates/SharedResearchProposal.tsx
- packages/react-components/src/templates/__tests__/SharedResearchProposal.test.tsx
https://trello.com/c/3NhzfUDR/1313-show-teams-on-proposal-page
> Feat: Add team list to proposal and update test

- .pnp.js
- apps/frontend/src/network/users/Editing.tsx
- apps/frontend/src/network/users/__tests__/Editing.test.tsx
- packages/react-components/package.json
- packages/react-components/src/__tests__/form.test.tsx
- packages/react-components/src/atoms/TextField.tsx
- packages/react-components/src/form.ts
- packages/react-components/src/molecules/Modal.tsx
- packages/react-components/src/molecules/TeamsList.tsx
- packages/react-components/src/templates/ContactInfoModal.tsx
- packages/react-components/src/templates/__tests__/ContactInfoModal.test.tsx
- packages/react-components/tsconfig.json
- packages/validation/.eslintrc.js
- packages/validation/package.json
- packages/validation/src/index.ts
- packages/validation/src/user.ts
- packages/validation/tsconfig.json
- yarn.lock
https://trello.com/c/KX24uBln/639-5-edit-social-media-links
> Feat: Extends edit personal information modal

- packages/react-components/src/templates/ContactInfoModal.tsx
- packages/react-components/src/templates/__tests__/ContactInfoModal.test.tsx
https://trello.com/c/afgH4HvJ/1379-change-the-error-message-for-website-1-and-2-on-edit-my-profile-modal
> Feat: Change copy

- .gitlab-ci.yml
- apps/frontend/src/config.ts
- serverless.ts
Adds Application ID to frontend and asap-server
see: https://trello.com/c/ZgizdZzU/1329-set-up-algolia-search-engine
> feat: Add Algolia config 

- .pnp.js
- apps/asap-server/package.json
- apps/asap-server/src/entities/user.ts
- apps/asap-server/src/routes/user.route.ts
- apps/asap-server/test/controllers/users.test.ts
- apps/asap-server/test/fixtures/users.fixtures.ts
- apps/asap-server/test/routes/user.route.test.ts
- apps/asap-server/tsconfig.json
- packages/model/src/user.ts
- packages/validation/package.json
- packages/validation/src/user.ts
- packages/validation/test/fixtures/user.fixtures.ts
- packages/validation/test/user.test.ts
- packages/validation/tsconfig.json
- yarn.lock
see: https://trello.com/c/XnOmu8Ni/1301-enable-complete-users-to-publish-their-profile
- added a validation function for profile completeness
- refactored some tests, added extra coverage for the `patch` method in the user controller
- applied the validation rules in the route as they dont seem to belong to the controller method
> feat: Onboard user

- apps/asap-cli/src/import/protocols/insert.ts
- apps/asap-cli/test/import/protocols.fixture.ts
- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/entities/research-output.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/research-output.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- packages/fixtures/src/research-outputs.ts
- packages/model/src/research-output.ts
- packages/squidex/src/entities/research-output.ts
- packages/squidex/src/entities/team.ts
- packages/squidex/src/squidex.ts
Implement the BE component of the Contact CTA card, as detailed here: https://trello.com/c/UJXl8wzr/1234-add-contact-cta-to-output-details-page
The BE should return a deduplicated array of PMs emails for the relevant shared RO.
> Contact CTA card BE implementation

- apps/frontend/src/network/users/Editing.tsx
- apps/frontend/src/network/users/__tests__/Editing.test.tsx
- apps/storybook/src/ContactInfoModal.stories.tsx
- packages/react-components/src/icons/globe.tsx
- packages/react-components/src/molecules/__tests__/SocialIcons.test.tsx
- packages/react-components/src/templates/ContactInfoModal.tsx
- packages/react-components/src/templates/__tests__/ContactInfoModal.test.tsx
https://trello.com/c/v0Ars5ZT/1403-user-cannot-edit-previously-saved-websites
> Fix: Contact info modal isn't showing data

- docs/js-infra.md
> fix: js-infra formatting

- apps/storybook/src/AdditionalMaterials.stories.tsx
- apps/storybook/src/CheckboxGroup.stories.tsx
Fixes http://929.hub.asap.science/.storybook/?path=/story/organisms-checkbox-group--normal
> Fix checkbox group

- apps/storybook/src/SharedResearchCard.stories.tsx
- apps/storybook/src/UsersList.stories.tsx
- packages/react-components/src/atoms/Avatar.tsx
- packages/react-components/src/molecules/UsersList.tsx
- packages/react-components/src/molecules/__tests__/UsersList.test.tsx
- packages/react-components/src/organisms/SharedResearchCard.tsx
- packages/react-components/src/organisms/__tests__/SharedResearchCard.test.tsx
- packages/react-components/src/templates/__tests__/TeamProfileOutputs.test.tsx
https://trello.com/c/7S1d8oEy/1245-show-authors-on-outputs-list
> Feat: Add authors to list

- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/entities/research-output.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/controllers/teams.test.ts
- apps/asap-server/test/controllers/users.test.ts
- apps/asap-server/test/fixtures/users.fixtures.ts
- serverless.ts
https://trello.com/b/0i1h6dJy/asap-hub-task-board
Adds custom API Gateway logs so that we are able to identify the errors better
> feat: Hide non-onboarded users from the hub

- packages/squidex/schema/schemas/calendars.json
- packages/squidex/schema/schemas/events.json
- packages/squidex/schema/schemas/groups.json
- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/schema/schemas/teams.json
- packages/squidex/schema/schemas/users.json
https://trello.com/c/AVJY4vRb/1440-changes-to-schemas-on-the-cms
> feat: Make schema changes

- apps/frontend/src/network/users/Editing.tsx
- apps/frontend/src/network/users/__mocks__/api.ts
- apps/frontend/src/network/users/__tests__/Editing.test.tsx
- apps/frontend/src/network/users/__tests__/api.test.ts
- apps/frontend/src/network/users/api.ts
- apps/storybook/src/LabeledTypeahead.stories.tsx
- apps/storybook/src/PersonalInfoModal.stories.tsx
- packages/react-components/src/atoms/Typeahead.tsx
- packages/react-components/src/atoms/__tests__/Typeahead.test.tsx
- packages/react-components/src/select.ts
- packages/react-components/src/templates/PersonalInfoModal.tsx
- packages/react-components/src/templates/__tests__/PersonalInfoModal.test.tsx
https://trello.com/c/StkDlFFF/1351-change-input-field-for-institution
> Feat: Async Typeahead

- packages/squidex/schema/schemas/research-outputs.json
- packages/squidex/src/entities/research-output.ts
https://trello.com/c/GvN2W66A/1398-store-accession-for-each-roms-output
> feat: Add accession field to research-outputs

- .gitlab-ci.yml
- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/routes/user.route.ts
- apps/asap-server/src/utils/__mocks__/validate-token.ts
- apps/asap-server/test/controllers/users.test.ts
- apps/asap-server/test/middleware/permission-handler.test.ts
- apps/asap-server/test/routes/user.route.test.ts
https://trello.com/c/tOgvW09z/1476-enable-profile-endpoint
> feat: Enable profile endpoint for non-onboarded, logged users

- apps/storybook/src/LabeledMultiSelect.stories.tsx
- packages/react-components/src/atoms/Ellipsis.tsx
- packages/react-components/src/atoms/Tag.tsx
- packages/react-components/src/atoms/__tests__/Ellipsis.browser-test.tsx
- packages/react-components/src/atoms/__tests__/Tag.test.tsx
- packages/react-components/src/molecules/__tests__/TagList.test.tsx
- packages/react-components/src/select.ts
https://trello.com/c/Z2UpR4F3/1356-3-introduce-ellipsing-on-tags
> introduce ellipsing on tags 

- packages/react-components/src/atoms/Link.tsx
- packages/react-components/src/molecules/ExternalLink.tsx
> fix: link styles  

- packages/squidex/schema/schemas/users.json
Add admin notes section to user schema
> Add admin notes section to user schema

- apps/asap-server/src/config.ts
- apps/asap-server/src/handlers/webhooks/fetch-by-code/fetch-by-code.ts
- apps/asap-server/test/handlers/webhooks/fetch-by-code/fetch-by-code.test.ts
- packages/model/src/user.ts
Follow up on https://trello.com/c/rd7Z4bX0/1331-enable-authentication-for-the-search
> feat: Algolia authentication - remove fail-safe feature

- apps/storybook/src/SharedResearchOutput.stories.tsx
- packages/react-components/src/__tests__/utils.test.tsx
- packages/react-components/src/atoms/Link.tsx
- packages/react-components/src/organisms/UserProfileRecentWorks.tsx
- packages/react-components/src/templates/SharedResearchOutput.tsx
- packages/react-components/src/templates/__tests__/SharedResearchOutput.test.tsx
- packages/react-components/src/utils.ts
https://trello.com/c/FUqUFy3Q/1394-expand-additional-information-section
[previous pr](https://github.com/yldio/asap-hub/pull/969)
> 1394 expand additional information section 2

- packages/react-components/src/molecules/Modal.tsx
https://trello.com/c/LspAzgHD/1358-modal-wont-scroll-on-firefox
> changing display grid to flex on modals

- packages/react-components/src/templates/ToolModal.tsx
- packages/react-components/src/templates/__tests__/ToolModal.test.tsx
- packages/validation/src/index.ts
- packages/validation/src/teams.ts
- packages/validation/test/teams.test.ts
https://trello.com/c/Gxvd1zId/1038-keep-users-from-inputting-incomplete-urls-on-team-tools
> fix: validates team tool url protocol

- apps/frontend/src/AuthenticatedApp.tsx
- apps/frontend/src/Onboardable.tsx
- apps/frontend/src/__tests__/Onboardable.test.tsx
- apps/frontend/src/hooks/__tests__/current-user-profile-tab-route.test.tsx
- apps/frontend/src/hooks/current-user-profile-tab-route.ts
- apps/frontend/src/hooks/index.ts
- apps/frontend/src/network/users/Editing.tsx
- apps/frontend/src/network/users/UserProfile.tsx
- apps/frontend/src/network/users/__tests__/Editing.test.tsx
- apps/storybook/src/Layout.stories.tsx
- apps/storybook/src/OnboardModal.stories.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/OnboardingHeader.tsx
- packages/react-components/src/organisms/__tests__/OnboardingHeader.test.tsx
- packages/react-components/src/templates/Layout.tsx
- packages/react-components/src/templates/OnboardModal.tsx
- packages/react-components/src/templates/__tests__/Layout.test.tsx
- packages/react-components/src/templates/__tests__/OnboardModal.test.tsx
- packages/react-components/src/templates/index.ts
- packages/routing/src/network.ts
https://trello.com/c/XnOmu8Ni/1301-enable-complete-users-to-publish-their-profile
> Feat: Onboarding Modal

- apps/frontend/src/AuthenticatedApp.tsx
- apps/storybook/src/Layout.stories.tsx
- apps/storybook/src/MainNavigation.stories.tsx
- apps/storybook/src/UserNavigation.stories.tsx
- apps/storybook/src/layout.tsx
- packages/react-components/src/atoms/NavigationLink.tsx
- packages/react-components/src/atoms/__tests__/NavigationLink.test.tsx
- packages/react-components/src/molecules/Header.tsx
- packages/react-components/src/molecules/__tests__/Header.test.tsx
- packages/react-components/src/organisms/MainNavigation.tsx
- packages/react-components/src/organisms/MenuHeader.tsx
- packages/react-components/src/organisms/UserNavigation.tsx
- packages/react-components/src/organisms/__tests__/MainNavigation.test.tsx
- packages/react-components/src/organisms/__tests__/MenuHeader.test.tsx
- packages/react-components/src/organisms/__tests__/UserNavigation.test.tsx
- packages/react-components/src/templates/Layout.tsx
- packages/react-components/src/templates/__tests__/Layout.browser-test.tsx
- packages/react-components/src/templates/__tests__/Layout.test.tsx
https://github.com/yldio/asap-hub/pull/961
> feat: disable nav bar items

- README.md
- ci/.gitlab-ci.integration.yml
- dev/base.Dockerfile
Fix singleton sync import errors by bumping squidex CLI version (for both import and export)
> Fix singleton sync import errors

- apps/frontend/src/network/users/__tests__/Editing.test.tsx
- apps/frontend/src/network/users/state.ts
https://trello.com/c/w9f0CSPI/1499-when-i-publish-my-profile-i-am-not-redirected-to-the-homepage
> Fix: Wait for token before continuing

- packages/react-components/src/atoms/MultiSelect.tsx
- packages/react-components/src/atoms/__tests__/MultiSelect.test.tsx
- packages/react-components/src/select.ts
- packages/react-components/src/templates/SkillsModal.tsx
- packages/react-components/src/templates/__tests__/SkillsModal.test.tsx
- [Logic](https://trello.com/c/e4E2lT5P/1424-error-states-behaviour-on-labeled-multi-select-tags) 
- [Styles](https://trello.com/c/RUSgkDNJ/1425-error-state-appearance-on-labeled-multi-select-tags)
> fix: error states on Labeled Multi-Select (tags)

- .gitlab-ci.yml
https://trello.com/c/ETFGxtoD/1516-fix-docker-rate-limits-breaking-pipeline
* replace base image with one from gitlab
> chore: Improve gitlab pipeline

- .gitlab-ci.yml
- ci/.gitlab-ci.integration.yml
https://trello.com/c/ETFGxtoD/1516-fix-docker-rate-limits-breaking-pipeline
* replace base docker image for .pre stage with one from gitlab
> chore: Improve gitlab pipeline v2

- apps/frontend/src/network/users/Research.tsx
- apps/storybook/src/UserProfileResearch.stories.tsx
- packages/react-components/src/templates/UserProfileResearch.tsx
- packages/react-components/src/templates/__tests__/UserProfileResearch.test.tsx
https://trello.com/c/DlUxtxmL/1521-hide-contact-footer-on-a-users-own-profile
> removing contact footer on user's profile

- apps/frontend/src/network/users/About.tsx
- apps/frontend/src/network/users/__tests__/About.test.tsx
- apps/storybook/src/UserProfileAbout.stories.tsx
- packages/flags/src/index.ts
- packages/react-components/src/templates/UserProfileAbout.tsx
- packages/react-components/src/templates/__tests__/UserProfileAbout.test.tsx
- packages/routing/src/network.ts
https://trello.com/c/rIK8W6v6/1498-remove-the-orcid-recent-works-pencil
> fix: removes the edit button from recent works

- apps/frontend/src/App.tsx
- apps/frontend/src/auth/SentryAuth0.tsx
- package.json
Raised tech debt ticket to look at this https://trello.com/c/eTXxPR0d/1523-bundle-size
> Fix: Bump bundle size

- .gitlab-ci.yml
- apps/frontend/scripts/sentry-release.js
Upload source maps for both dev and production builds
> Set sentry DSN specifically on development.

- packages/react-components/src/organisms/ToastStack.tsx
- packages/react-components/src/templates/Layout.tsx
https://trello.com/c/I7z0VkYv/815-cannot-scroll-all-the-way-to-the-bottom-on-low-height-screens
> fixing scroll issues with onboarding header and small screens

- .pnp.js
- apps/frontend/package.json
- apps/frontend/src/dashboard/Dashboard.tsx
- apps/frontend/src/dashboard/__tests__/Dashboard.test.tsx
- apps/frontend/src/hooks/__tests__/algolia.test.tsx
- apps/frontend/src/hooks/algolia.ts
- apps/frontend/src/shared-research/__mocks__/api.ts
- apps/frontend/src/shared-research/__tests__/ResearchOutputList.test.tsx
- apps/frontend/src/shared-research/__tests__/Routes.test.tsx
- apps/frontend/src/shared-research/__tests__/api.test.ts
- apps/frontend/src/shared-research/api.ts
- apps/frontend/src/shared-research/state.ts
- packages/fixtures/package.json
- packages/fixtures/src/research-outputs.ts
- packages/fixtures/src/util.ts
- packages/flags/src/index.ts
- packages/react-components/src/organisms/Filter.tsx
- packages/react-components/src/organisms/SearchAndFilter.tsx
- packages/react-components/src/organisms/__tests__/Filter.test.tsx
- yarn.lock
https://trello.com/c/A7AEOhIN/1432-2-enable-authentication-for-the-search
https://trello.com/c/GmHFftId/1341-8-search-for-more-fields-on-research-outputs
> Feature: Algolia

- apps/asap-server/src/config.ts
- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/handlers/research-output/index-handler.ts
- apps/asap-server/src/handlers/user/invite-handler.ts
- apps/asap-server/src/handlers/webhooks/webhook-research-output.ts
- apps/asap-server/test/fixtures/research-output.fixtures.ts
- apps/asap-server/test/handlers/jobs/resubscribe-calendars.test.ts
- apps/asap-server/test/handlers/research-output/index-handler.test.ts
- apps/asap-server/test/handlers/user/invite-handler.test.ts
- apps/asap-server/test/handlers/webhooks/webhook-research-output.test.ts
- apps/asap-server/test/helpers/events.ts
- apps/asap-server/test/helpers/webhooks.ts
- apps/asap-server/test/mocks/algolia-client.mock.ts
- packages/services-common/src/framework/lambda.ts
- packages/squidex/schema/rules/rule2.json
- packages/squidex/schema/rules/rule3.json
- serverless.ts
see: https://trello.com/c/JtbZrKeL/1332-5-enable-continuous-data-synchronisation-of-research-outputs
> feat: Sync research-outputs in Algolia

- packages/validation/src/user.ts
https://trello.com/c/ReZf7mwZ/1531-dont-accept-spaces-on-social-profiles
> changing validation regex for User Social to not accept white space

- apps/asap-server/src/entities/group.ts
- apps/asap-server/src/entities/team.ts
- apps/asap-server/test/controllers/teams.test.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- apps/asap-server/test/fixtures/users.fixtures.ts
- apps/storybook/src/Icons.stories.tsx
- apps/storybook/src/TeamProfilePage.stories.tsx
- packages/fixtures/src/teams.ts
- packages/model/src/group.ts
- packages/model/src/team.ts
- packages/react-components/src/icons/index.ts
- packages/react-components/src/icons/lab.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- packages/react-components/src/templates/__tests__/TeamProfileHeader.test.tsx
- packages/react-components/src/templates/__tests__/TeamProfilePage.test.tsx
https://trello.com/c/jCrcFx2C/1505-show-count-of-labs-on-team-pages-header
> feat: Add Lab count to team response

- .github/workflows/master-sync.yml
> Fix missing quote

- packages/react-components/src/appearance.ts
- packages/react-components/src/icons/index.ts
- packages/react-components/src/icons/success.tsx
- packages/react-components/src/organisms/OnboardingFooter.tsx
- packages/react-components/src/organisms/__tests__/OnboardingFooter.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/Layout.tsx
https://trello.com/c/dyta7Z8J/1555-update-onboarding-banner-appearance
> Feat: Onboarding footer

- apps/storybook/src/LabeledDropdown.stories.tsx
- apps/storybook/src/LabeledMultiSelect.stories.tsx
- apps/storybook/src/LabeledTextArea.stories.tsx
- apps/storybook/src/LabeledTextField.stories.tsx
- apps/storybook/src/LabeledTypeahead.stories.tsx
- packages/react-components/src/molecules/LabeledDropdown.tsx
- packages/react-components/src/molecules/LabeledMultiSelect.tsx
- packages/react-components/src/molecules/LabeledTextArea.tsx
- packages/react-components/src/molecules/LabeledTextField.tsx
- packages/react-components/src/molecules/LabeledTypeahead.tsx
- packages/react-components/src/molecules/__tests__/LabeledDropdown.test.tsx
- packages/react-components/src/molecules/__tests__/LabeledMultiSelect.test.tsx
- packages/react-components/src/molecules/__tests__/LabeledTextArea.test.tsx
- packages/react-components/src/molecules/__tests__/LabeledTextField.test.tsx
- packages/react-components/src/molecules/__tests__/LabeledTypeahead.test.tsx
- packages/react-components/src/templates/BiographyModal.tsx
- packages/react-components/src/templates/ContactInfoModal.tsx
- packages/react-components/src/templates/OpenQuestionsModal.tsx
- packages/react-components/src/templates/PersonalInfoModal.tsx
- packages/react-components/src/templates/SkillsModal.tsx
- packages/react-components/src/templates/TeamMembershipModal.tsx
- packages/react-components/src/templates/ToolModal.tsx
- packages/react-components/src/templates/__tests__/BiographyModal.test.tsx
- packages/react-components/src/templates/__tests__/ContactInfoModal.test.tsx
- packages/react-components/src/templates/__tests__/OpenQuestionsModal.test.tsx
- packages/react-components/src/templates/__tests__/PersonalInfoModal.test.tsx
- packages/react-components/src/templates/__tests__/SkillsModal.test.tsx
- packages/react-components/src/templates/__tests__/TeamMembershipModal.test.tsx
- packages/react-components/src/templates/__tests__/ToolModal.test.tsx
https://trello.com/c/JkgRVAzs/1553-flag-optional-and-mandatory-fields-within-modals
> feat: flag optional and mandatory fields

- .gitlab-ci.yml
Adds back custom env vars for squidex creds in PR envs.
> fix: Invalid squidex credentials in PR environments

- apps/asap-server/src/controllers/groups.ts
- apps/asap-server/src/handlers/calendar/subscribe-handler.ts
Fixes the invalid group-calendar query
Also fixes the poor event logging
> fix: Invalid calendar query

- apps/asap-server/src/controllers/events.ts
Fixes the invalid event-calendar query
> fix: Invalid event-calendar query

- packages/react-components/src/messages/Layout.tsx
- packages/react-components/src/messages/Welcome.tsx
https://trello.com/c/AALNB6TU/1564-update-copy-on-the-invite-email-template-must
> fix: update welcome email

- apps/asap-server/scripts/schema-update.sh
- apps/asap-server/src/gql/graphql.ts
- packages/react-components/src/messages/Welcome.tsx
https://trello.com/c/ipJaRJAU/1605-remove-time-mentions-to-welcome-email
> fix: update welcome email copy

- apps/asap-server/src/gql/graphql.ts
- apps/frontend/src/Onboardable.tsx
- apps/frontend/src/__tests__/Onboardable.test.tsx
- apps/frontend/src/hooks/__tests__/onboarding.test.tsx
- apps/frontend/src/hooks/index.ts
- apps/frontend/src/hooks/onboarding.tsx
- apps/frontend/src/network/users/__tests__/Editing.test.tsx
- apps/frontend/src/network/users/state.ts
- apps/storybook/src/Layout.stories.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/OnboardingFooter.tsx
- packages/react-components/src/organisms/__tests__/OnboardingFooter.test.tsx
- packages/react-components/src/templates/Layout.tsx
- packages/react-components/src/templates/OnboardModal.tsx
- packages/react-components/src/templates/__tests__/Layout.test.tsx
- packages/react-components/src/templates/__tests__/OnboardModal.test.tsx
- packages/validation/src/user.ts
- packages/validation/test/user.test.ts
https://trello.com/c/1EX3pNFY/1563-add-dynamic-copy-to-onboarding-banner-must
> Feat: Dynamic Onboarding Text

- apps/asap-server/validate-orcids-script/validate-orcids.ts
> fix: ORCID validation script

- apps/asap-server/src/entities/group.ts
- apps/asap-server/test/controllers/groups.test.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- packages/squidex/src/entities/group.ts
https://trello.com/c/BGpl9FI2/1539-fix-missing-leader-error
> fix: Group leader saved as draft bug

- apps/asap-server/src/entities/research-output.ts
- apps/asap-server/src/entities/team.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/fixtures/research-output.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- packages/fixtures/src/research-outputs.ts
- packages/model/src/research-output.ts
https://trello.com/b/0i1h6dJy/asap-hub-task-board
> refactor: removes teams field from ro

- apps/storybook/src/NetworkTeams.stories.tsx
- apps/storybook/src/TeamCard.stories.tsx
- packages/react-components/src/organisms/TeamCard.tsx
- packages/react-components/src/organisms/__tests__/TeamCard.test.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- packages/react-components/src/templates/__tests__/NetworkTeams.test.tsx
- packages/react-components/src/utils/__tests__/text.test.tsx
- packages/react-components/src/utils/text.ts
https://trello.com/c/MdzNzcUS/1493-3-show-count-of-labs-on-team-listing-on-network
> feat: show count of labs on Team listing on Network

- apps/frontend/src/network/teams/Workspace.tsx
- packages/react-components/src/templates/TeamProfileWorkspace.tsx
- packages/react-components/src/templates/__tests__/TeamProfileWorkspace.test.tsx
- packages/routing/src/network.ts
https://trello.com/c/zyL3gPDO/1560-first-tool-in-workspace-not-editable
> Fix: First edit tool

- apps/frontend/src/api/news.ts
- apps/frontend/src/news/NewsList.tsx
- apps/frontend/src/news/__tests__/NewsList.test.tsx
- apps/storybook/src/NewsPageBody.stories.tsx
- packages/fixtures/src/news.ts
- packages/react-components/src/templates/NewsPageBody.tsx
- packages/react-components/src/templates/__tests__/NewsPageBody.test.tsx
https://trello.com/c/TlUBmgnw/698-news-pagination
> feat: News pagination

- packages/react-components/src/templates/WelcomePage.tsx
https://trello.com/c/TkrfzHTq/1639-copy-changes-to-welcome-page
> fix: update copy

- README.md
- apps/asap-server/src/gql/graphql.ts
- apps/asap-server/src/migrations/1636027226-move-repurposed-fields.ts
- apps/asap-server/src/schema/schema.graphql
- apps/asap-server/test/fixtures/teams.fixtures.ts
- packages/squidex/schema/schemas/teams.json
- packages/squidex/schema/schemas/users.json
- packages/squidex/src/entities/team.ts
- packages/squidex/src/entities/user.ts
Create new fields in User schema:
Skills = expertiseandResourceTags
SkillsDescription = expertiseandResourceDescription
approach = mainResearchInterests
> chore: adds fields to user for migration

- packages/react-components/src/atoms/MultiSelect.tsx
- packages/react-components/src/atoms/__tests__/MultiSelect.test.tsx
https://trello.com/c/DCZP4I8H/1559-%F0%9F%90%9B-tags-input-area-stops-working-after-a-right-click
> Fixing tags area not working after right click

- packages/react-components/src/atoms/Button.tsx
- packages/react-components/src/atoms/Link.tsx
https://trello.com/c/AVgw3qc9/1626-2-make-link-styled-component-button-consistent-with-link-styles
> using links styles on button with link prop

- packages/react-components/src/molecules/UsersList.tsx
https://trello.com/c/dhNldpL0/1710-fix-avatar-in-user-list
> Fix Avatar in user list 

- apps/frontend/src/App.tsx
- apps/frontend/src/__tests__/App.test.tsx
- apps/frontend/src/network/teams/Outputs.tsx
- apps/frontend/src/network/teams/__tests__/Outputs.test.tsx
- apps/frontend/src/network/users/Outputs.tsx
- apps/frontend/src/network/users/__tests__/Outputs.test.tsx
- apps/frontend/src/shared-research/ResearchOutputList.tsx
- apps/frontend/src/shared-research/__tests__/ResearchOutputList.test.tsx
- apps/storybook/src/flags.tsx
- packages/flags/src/__tests__/index.test.ts
- packages/flags/src/index.ts
- packages/react-components/src/organisms/SharedResearchCard.tsx
- packages/react-components/src/organisms/__tests__/SharedResearchCard.test.tsx
- packages/react-components/src/templates/TeamProfileOutputs.tsx
- packages/react-components/src/templates/UserProfileResearchOutputs.tsx
- packages/react-components/src/templates/__tests__/TeamProfileOutputs.test.tsx
- packages/react-components/src/templates/__tests__/UserProfileResearchOutputs.test.tsx
- packages/react-context/src/__tests__/flags.test.tsx
- packages/react-context/src/flags.tsx
https://trello.com/c/obyvqP86/1662-2-allow-feature-flags-to-be-overridden-by-a-cookie-value
> feat: update feature flags by setting a cookie manually

- apps/frontend/src/App.tsx
- apps/frontend/src/__tests__/App.test.tsx
- apps/frontend/src/dashboard/__tests__/Dashboard.test.tsx
- apps/frontend/src/network/teams/Outputs.tsx
- apps/frontend/src/network/teams/__tests__/Outputs.test.tsx
- apps/frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- apps/frontend/src/network/users/Outputs.tsx
- apps/frontend/src/network/users/__tests__/Outputs.test.tsx
- apps/frontend/src/network/users/__tests__/UserProfile.test.tsx
- apps/frontend/src/shared-research/ResearchOutputList.tsx
- apps/frontend/src/shared-research/__tests__/ResearchOutputList.test.tsx
- apps/frontend/src/shared-research/__tests__/Routes.test.tsx
- apps/frontend/src/shared-research/state.ts
- apps/storybook/src/flags.tsx
- packages/flags/src/__tests__/index.test.ts
- packages/flags/src/index.ts
- packages/react-components/src/organisms/SharedResearchCard.tsx
- packages/react-components/src/organisms/__tests__/SharedResearchCard.test.tsx
- packages/react-components/src/organisms/__tests__/SharedResearchOutputHeaderCard.test.tsx
- packages/react-components/src/templates/TeamProfileOutputs.tsx
- packages/react-components/src/templates/UserProfileResearchOutputs.tsx
- packages/react-components/src/templates/__tests__/TeamProfileOutputs.test.tsx
- packages/react-components/src/templates/__tests__/UserProfileResearchOutputs.test.tsx
- packages/react-context/src/__tests__/flags.test.tsx
- packages/react-context/src/flags.tsx
https://github.com/yldio/asap-hub/pull/1140
> feat: update feature flags by setting a cookie manually 

- .gitlab-ci.yml
- apps/frontend/src/structure/ErrorBoundary.tsx
- apps/frontend/src/structure/Frame.tsx
- apps/frontend/src/structure/__tests__/ErrorBoundary.test.tsx
https://trello.com/c/LMBDvJpz/1667-3-revisit-error-handling-for-search
> feat: handle Algolia errors

- packages/react-components/src/organisms/RichText.tsx
- packages/react-components/src/organisms/__tests__/RichText.test.tsx
https://trello.com/c/CdqhCoFK/1684-change-toc-on-rich-text-component
> Feat: Rtf update

- apps/frontend/src/App.tsx
- apps/frontend/src/auth/__tests__/react-auth0-spa.test.tsx
- apps/frontend/src/auth/react-auth0-spa.tsx
https://trello.com/c/BZEGD3jD/1594-3-users-are-able-to-navigate-the-hub-even-if-they-are-logged-out
> Feat: Auth0 session expire

- apps/frontend/src/App.tsx
- apps/frontend/src/auth/CheckAuth.tsx
- apps/frontend/src/auth/__tests__/react-auth0-spa.test.tsx
- apps/frontend/src/auth/react-auth0-spa.tsx
- packages/auth/src/index.ts
https://trello.com/c/VPukC1qT/1737-search-triggers-a-refresh-on-every-keystroke
> adressing rerenders when using search

- .github/actions/slack/action.yml
- .github/workflows/dev-algolia-sync.yml
- .github/workflows/env-teardown.yml
- .github/workflows/master-sync.yml
- .github/workflows/prod-algolia-sync.yml
- .github/workflows/prod-backup.yml
https://trello.com/c/OXIi9twA/1584-3-add-failure-success-notification-to-github-actions
> feat: Add GitHub Slack notifications

- serverless.ts
https://trello.com/c/p2pue20D/1738-cors-issue-on-production
> Add additional cors rules to allow users to patch

- apps/asap-server/src/handlers/calendar/subscribe-handler.ts
- apps/asap-server/test/handlers/calendar/subscribe-handler.test.ts
- serverless.ts
https://trello.com/c/MncCAJym/1717-retry-to-subscribe-to-calendars-after-faillure
> feat: retry to subscribe to calendars after failure

- packages/react-components/src/templates/UnsupportedBrowserPage.tsx
https://trello.com/c/kVaBBjpe/1558-1-update-browser-not-supported-messaging
> update copy for browser not supported

- packages/react-components/src/molecules/SearchField.tsx
https://trello.com/c/JTHPTPXw/1716-1-prevent-users-from-performing-searches-that-break-algolia-api
> Feat: Set max length on search field

- apps/asap-server/test/routes/news.route.test.ts
- apps/frontend/src/dashboard/__tests__/Dashboard.test.tsx
- apps/frontend/src/news/__tests__/NewsList.test.tsx
- apps/storybook/src/MainNavigation.stories.tsx
- packages/react-components/src/templates/DashboardPageBody.tsx
- packages/react-components/src/templates/NewsPageHeader.tsx
https://trello.com/c/fcuTizTI/1747-1-change-header-in-news
> Feat: News and events copy change

- apps/asap-server/src/controllers/research-outputs.ts
- apps/asap-server/src/entities/research-output.ts
- apps/asap-server/src/migrations/1637748102-move-type-proposal-to-grant-research.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/frontend/src/shared-research/__tests__/api.test.ts
- apps/frontend/src/shared-research/api.ts
- packages/model/src/research-output.ts
- packages/react-components/src/templates/SharedResearchOutput.tsx
- packages/react-components/src/templates/__tests__/SharedResearchOutput.test.tsx
*  ~~update the filter on Shared Outputs by adding **Grant Document** as an option and removing **Proposal**~~
* migrate all Proposal ROs to Grant Document type and give it the Proposal subtype
* re index ROMS in algolia
* clean up the old Proposal type
> feat/1686 Remove Proposal RO type from codebase

- apps/storybook/src/SharedResearchOutput.stories.tsx
- packages/react-components/src/templates/SharedResearchOutput.tsx
https://trello.com/c/5My9r4Bx/1727-2-change-detail-pages-for-presentation
> fix: update ro templates

- .gitlab-ci.yml
- ci/.gitlab-ci.integration.yml
https://trello.com/c/gDV2zPNE/1701-speed-up-the-deploy-job-in-ci-pipeline
> Seperate SLS Deploy from Package

- apps/asap-server/src/migrations/1639476045046-move-responsabilities-interests-from-teams-to-users.ts
https://trello.com/c/bbCQGhe4/1768-2-prep-for-migration-of-interests-and-responsibilities-user-profile
https://drive.google.com/drive/folders/1ZOFkVvUpxLa17gL_aDzMlpHXZSJ0vXY_
> feat: migration user fields

- .github/workflows/dev-backup.yml
- apps/asap-server/src/app.ts
- apps/asap-server/src/controllers/groups.ts
- apps/asap-server/src/controllers/teams.ts
- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/handlers/webhooks/cronjob-sync-orcid.ts
- apps/asap-server/src/handlers/webhooks/fetch-by-code/handler.ts
- apps/asap-server/src/handlers/webhooks/webhook-connect-by-code.ts
- apps/asap-server/src/handlers/webhooks/webhook-sync-orcid.ts
- apps/asap-server/test/controllers/groups.test.ts
- apps/asap-server/test/controllers/research-outputs.test.ts
- apps/asap-server/test/controllers/teams.test.ts
- apps/asap-server/test/controllers/users.test.ts
- apps/asap-server/test/entities/team.test.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/asap-server/test/fixtures/research-output.fixtures.ts
- apps/asap-server/test/fixtures/teams.fixtures.ts
- apps/asap-server/test/fixtures/users.fixtures.ts
- apps/asap-server/test/integration/fetch-users.integration-test.ts
- apps/asap-server/test/mocks/squidex-graphql-client-with-server.mock.ts
https://trello.com/c/CeH5RrUB/1748-use-mock-server-for-testing-all-controllers
This should also test the failure from https://github.com/yldio/asap-hub/pull/1172
> chore: add mock server tests to controllers

- apps/asap-server/src/entities/user.ts
- apps/frontend/src/network/users/Research.tsx
- apps/frontend/src/network/users/__tests__/Research.test.tsx
- apps/storybook/src/RoleModal.stories.tsx
- packages/flags/src/index.ts
- packages/model/src/user.ts
- packages/react-components/src/index.ts
- packages/react-components/src/templates/RoleModal.tsx
- packages/react-components/src/templates/__tests__/RoleModal.test.tsx
- packages/react-components/src/templates/index.ts
- packages/routing/src/network.ts
https://trello.com/c/rtdFrMBd/1749-create-new-your-role-on-asap-modal
> feat: add "your role" modal

- apps/frontend/public/index.html
No Ticket,
Include the build version in the HTML meta
> Feat: Add pipeline id, job id and when it was triggered into index.html

- packages/react-components/src/molecules/ExternalLink.tsx
- packages/react-components/src/molecules/__tests__/ExternalLink.test.tsx
- packages/react-components/src/organisms/SharedResearchMetadata.tsx
- packages/react-components/src/organisms/__tests__/SharedResearchCard.test.tsx
https://trello.com/c/zFWyCReZ/1386-1-external-link-icon-on-list-view-shared-outputs
> fix: external link ui

- apps/frontend/src/network/teams/Outputs.tsx
- apps/frontend/src/network/teams/__tests__/Outputs.test.tsx
- apps/frontend/src/network/users/Outputs.tsx
- apps/frontend/src/network/users/__tests__/Outputs.test.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/templates/UserProfileResearchOutputs.tsx
- packages/react-components/src/utils/__tests__/text.test.tsx
- packages/react-components/src/utils/text.ts
https://trello.com/c/2k1LqL7C/1628-custom-filenames-for-csv-exports-on-team-on-profile-pages
> Feat: Custom filenames for exports

- apps/asap-cli/test/helpers/squidex.ts
- apps/asap-server/test/helpers/squidex.ts
- packages/squidex/src/auth.ts
- packages/squidex/test/auth.test.ts
- packages/squidex/test/index.test.ts
- packages/squidex/test/mocks/access-token.mock.ts
Fixes the issue whereby a new token was generated each time due to an invalid expiration check
> fix: Token expiration check

- README.md
We are testing the idea that when a branch is out of date from master but cleanly rebase/merges that gitlab master build isn't triggered
> Testing theroy

- apps/frontend/src/network/users/Research.tsx
- apps/frontend/src/network/users/__tests__/Research.test.tsx
- apps/frontend/src/network/users/__tests__/UserProfile.test.tsx
- apps/storybook/src/UserProfileRole.stories.tsx
- packages/flags/src/index.ts
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/UserProfileRole.tsx
- packages/react-components/src/organisms/__tests__/UserProfileRole.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/UserProfileResearch.tsx
- packages/react-components/src/templates/__tests__/UserProfileResearch.test.tsx
https://trello.com/c/BSOkU9wR/1733-create-new-section-for-your-role-on-asap
> new roles section

- packages/react-components/src/organisms/SharedResearchCard.tsx
- packages/react-components/src/organisms/SharedResearchMetadata.tsx
- packages/react-components/src/organisms/SharedResearchOutputHeaderCard.tsx
- packages/react-components/src/organisms/__tests__/SharedResearchMetadata.test.tsx
- packages/react-components/src/organisms/__tests__/SharedResearchOutputHeaderCard.test.tsx
https://trello.com/c/zFWyCReZ/1386-1-external-link-icon-on-list-view-shared-outputs
> fix: ros link ui

- apps/storybook/src/HelpSection.stories.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/HelpSection.tsx
https://trello.com/c/wQ0KEpEL/1809-update-helpsection-footer
> Help section Story

- apps/asap-server/src/entities/group.ts
- apps/asap-server/test/fixtures/groups.fixtures.ts
- apps/frontend/src/network/groups/GroupProfile.tsx
- apps/storybook/src/GroupProfilePage.stories.tsx
- apps/storybook/src/GroupTools.stories.tsx
- packages/fixtures/src/groups.ts
- packages/model/src/group.ts
- packages/react-components/src/organisms/GroupTools.tsx
- packages/react-components/src/organisms/__tests__/GroupTools.test.tsx
- packages/react-components/src/templates/EventPage.tsx
- packages/react-components/src/templates/GroupProfileAbout.tsx
- packages/react-components/src/templates/GroupProfileHeader.tsx
- packages/react-components/src/templates/__tests__/EventPage.test.tsx
- packages/react-components/src/templates/__tests__/GroupProfileHeader.test.tsx
https://trello.com/c/88gDXWFR/1799-omit-subscribe-from-group-and-event-pages-when-group-is-inactive
> Feat: Group inactive

- apps/asap-server/src/autogenerated-gql/graphql.ts
- apps/asap-server/src/schema/autogenerated-schema.graphql
This is in order to fix the schema that went out of sync with prod
> feat: Update squidex graphql TS definitions

- apps/asap-server/src/controllers/users.ts
- apps/asap-server/src/entities/team.ts
- apps/asap-server/test/controllers/users.test.ts
- packages/model/src/team.ts
- packages/react-components/src/templates/NetworkPageHeader.tsx
- packages/squidex/schema/schemas/users.json
https://asaphub.atlassian.net/browse/CRN-646?atlOrigin=eyJpIjoiYjExZTA4ODI5YWRlNGIzZmE3MDU3ODg0MGJlMTY5YzciLCJwIjoiaiJ9
> feat: new option on team member role

- apps/frontend/src/network/teams/TeamOutput.tsx
- apps/frontend/src/network/teams/__tests__/TeamOutput.test.tsx
- apps/frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- packages/fixtures/src/research-outputs.ts
- packages/react-components/src/organisms/TeamCreateOutputHeader.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputHeader.test.tsx
- packages/react-components/src/templates/__tests__/TeamCreateOutputPage.test.tsx
- packages/routing/src/index.ts
- packages/routing/src/network.ts
https://asaphub.atlassian.net/browse/CRN-651
> CRN-651 allow users to create outputs of different types

- .github/workflows/algolia-sync-v2.yml
- .github/workflows/dev-algolia-sync-v2.yml
- .github/workflows/env-algolia-sync-v2.yml
- .github/workflows/prod-algolia-sync-v2.yml
- .gitlab-ci.yml
- package.json
The first commit contains the refactoring. 
Contains a fix where external authors was missing from remove entity step:
[fix build; refactor prod sync script](https://github.com/yldio/asap-hub/pull/1355/commits/c4205538e93f46f42dc9b00836f97f7b2605cd60)[](https://github.com/marot)
Fixes cron job by defaulting to all entities: 
[default to all for cronjob](https://github.com/yldio/asap-hub/pull/1355/commits/d10e337c348b421d3f2b1c2a9adb0cb75c4b6f8a)[](https://github.com/marot)
Fix removal of data if modifying a single entity:
[remove data from temp index (we intend to remove old data and insert …](https://github.com/yldio/asap-hub/pull/1355/commits/437656f0ac00beb037a24d190a4799766dab5aaf)
> Refactor sync workflows

- apps/storybook/src/EventCard.stories.tsx
- apps/storybook/src/EventPage.stories.tsx
- packages/react-components/src/organisms/EventCard.tsx
- packages/react-components/src/organisms/__tests__/EventCard.test.tsx
- packages/react-components/src/templates/EventPage.tsx
- packages/react-components/src/templates/__tests__/EventPage.test.tsx
https://asaphub.atlassian.net/jira/software/c/projects/CRN/boards/8?modal=detail&selectedIssue=CRN-721
> feat: update Events UI

- apps/storybook/src/GroupProfileAbout.stories.tsx
- packages/react-components/src/organisms/GroupInformation.tsx
- packages/react-components/src/organisms/__tests__/GroupInformation.test.tsx
https://asaphub.atlassian.net/browse/CRN-727
> CRN-727 remove collapsing functionality in group description

- packages/react-components/src/organisms/Form.tsx
- packages/react-components/src/organisms/ToastStack.tsx
- packages/react-components/src/organisms/__tests__/Form.test.tsx
- packages/react-components/src/organisms/__tests__/ToastStack.test.tsx
https://asaphub.atlassian.net/jira/software/c/projects/CRN/boards/8?modal=detail&selectedIssue=CRN-702
> fix: updates form error UI

- packages/react-components/src/organisms/Form.tsx
- packages/react-components/src/organisms/TeamCreateOutputForm.tsx
- packages/react-components/src/organisms/__tests__/Form.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputForm.test.tsx
https://asaphub.atlassian.net/jira/software/c/projects/CRN/boards/8?modal=detail&selectedIssue=CRN-688
> feat: add cancel button to create RO form

- apps/crn-server/src/handlers/lab/index-lab-users-handler.ts
- apps/crn-server/src/handlers/teams/index-team-users-handler.ts
- apps/crn-server/src/handlers/user/index-handler.ts
- apps/crn-server/test/handlers/lab/index-lab-users-handler.test.ts
- apps/crn-server/test/handlers/teams/index-team-users-handler.test.ts
- apps/crn-server/test/handlers/user/index-handler.test.ts
- do not show a user on the search results if:
1. they are non-onboarded  (not done yet!)
2. they are marked as hidden  (done)
- release feature flag: ALGOLIA_USER_SEARCH
> CRN-619 Improve and refine User search results

- .eslintrc.js
- apps/asap-cli/src/import/index.ts
- apps/asap-cli/src/import/users/insert.ts
- apps/crn-server/src/routes/research-outputs.route.ts
- apps/crn-server/src/validation/research-output.validation.ts
- apps/crn-server/test/controllers/research-outputs.test.ts
- apps/crn-server/test/fixtures/research-output.fixtures.ts
- apps/crn-server/test/routes/research-outputs.route.test.ts
- apps/storybook/src/TeamCreateOutputExtraInformationCard.stories.tsx
- packages/model/src/research-output.ts
- packages/model/tests/research-output.test.ts
- packages/react-components/.eslintrc.js
- packages/react-components/src/atoms/Dropdown.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/TeamCreateOutputExtraInformationCard.tsx
- packages/react-components/src/organisms/TeamCreateOutputForm.tsx
- packages/react-components/src/organisms/TeamCreateOutputIdentifier.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputExtraInformationCard.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputForm.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputIdentifier.test.tsx
- packages/react-components/src/research-output-identifier-type.ts
- packages/validation/src/user.ts
This PR contains
https://asaphub.atlassian.net/browse/CRN-596
https://asaphub.atlassian.net/browse/CRN-738
https://asaphub.atlassian.net/browse/CRN-736
> CRN-738 make identifier required new env

- apps/crn-frontend/src/network/teams/__tests__/TeamOutput.test.tsx
- apps/crn-server/src/controllers/research-outputs.ts
- apps/crn-server/src/validation/research-output.validation.ts
- apps/crn-server/test/controllers/research-outputs.test.ts
- apps/crn-server/test/routes/research-outputs.route.test.ts
- packages/model/src/external-author.ts
- packages/model/src/research-output.ts
- packages/react-components/src/organisms/TeamCreateOutputForm.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputForm.test.tsx
- packages/squidex/src/entities/external-author.ts
https://asaphub.atlassian.net/jira/software/c/projects/CRN/boards/8?modal=detail&selectedIssue=CRN-794
https://cloud.squidex.io/app/asap-hub-dev/content/research-outputs/6b3bbb16-1dfc-42da-852a-64698c2f17fc/history
> feat: create RO handles external authors creation

- packages/algolia/algolia-schema.json
CRN-811 Add the identifier types into the Algolia search
> CRN-811 Add the identifier types into the Algolia search

- apps/storybook/src/LabeledMultiSelect.stories.tsx
- packages/react-components/src/atoms/MultiSelect.tsx
- packages/react-components/src/atoms/__tests__/MultiSelect.test.tsx
- packages/react-components/src/icons/plus.tsx
- packages/react-components/src/organisms/AuthorSelect.tsx
- packages/react-components/src/organisms/TeamCreateOutputForm.tsx
- packages/react-components/src/organisms/__tests__/AuthorSelect.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputForm.test.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
https://asaphub.atlassian.net/jira/software/c/projects/CRN/boards/8?modal=detail&selectedIssue=CRN-795
> feat: RO form handles adding new external authors

- apps/crn-frontend/src/events/Events.tsx
- apps/crn-frontend/src/events/__tests__/Events.test.tsx
- packages/react-components/src/templates/EventsPageHeader.tsx
- packages/react-components/src/templates/__tests__/EventsPageHeader.test.tsx
> CRN 826 move the location of the calendar events tab and rename

- apps/crn-server/src/validation/research-output.validation.ts
- packages/react-components/src/organisms/TeamCreateOutputIdentifier.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputIdentifier.test.tsx
- packages/validation/src/index.ts
- packages/validation/src/research-output.ts
Add error message to identifier field
> CRN-808 Add error message to identifier field

- apps/crn-server/src/controllers/research-outputs.ts
- apps/crn-server/src/validation/research-output.validation.ts
- apps/crn-server/test/controllers/research-outputs.test.ts
- packages/react-components/src/organisms/TeamCreateOutputFormSharingCard.tsx
- packages/react-components/src/templates/ContactInfoModal.tsx
- packages/react-components/src/utils/__tests__/common.test.tsx
- packages/react-components/src/utils/common.ts
- packages/validation/src/index.ts
- packages/validation/src/url.ts
- packages/validation/src/user.ts
Expected Behaviour: User should be directed to the URL field with an error message ‘Please enter a valid URL’. This should  not be displayed at the top of the page.
> CRN-848 Validation error to be displayed on the URL field when user does not specify the domain

- .github/renovate.json
Renovate dependency updater with basic configuration
> CRN-749 Dependency updater

- .env.example
- .github/workflows/reusable-build.yml
- packages/auth/src/config.ts
https://asaphub.atlassian.net/browse/CRN-779
> removes AUTH0 defaults

- apps/crn-frontend/src/events/Event.tsx
- apps/storybook/src/SpeakersList.stories.tsx
- packages/fixtures/src/events.ts
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/EventCard.tsx
- packages/react-components/src/organisms/JoinEvent.tsx
- packages/react-components/src/organisms/SpeakersList.tsx
- packages/react-components/src/organisms/__tests__/SpeakerList.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/EventPage.tsx
- packages/react-components/src/templates/__tests__/EventPage.test.tsx
- packages/react-components/src/utils/__tests__/events.test.tsx
- packages/react-components/src/utils/events.ts
- packages/react-components/src/utils/index.ts
- packages/validation/src/user-guards.ts
- packages/validation/test/user-guards.test.ts
Created a Speakers List component that gets included in the EventPage as per the requirements in this ticket:
https://asaphub.atlassian.net/jira/software/c/projects/CRN/boards/6?modal=detail&selectedIssue=CRN-a
> Added speakers list component to EventPage

- apps/crn-frontend/src/shared-research/__mocks__/api.ts
- apps/storybook/src/TeamCreateOutputExtraInformationCard.stories.tsx
- apps/storybook/src/TeamCreateOutputForm.stories.tsx
- apps/storybook/src/TeamCreateOutputPage.stories.tsx
- packages/fixtures/src/research-tags.ts
- packages/react-components/src/organisms/TeamCreateOutputExtraInformationCard.tsx
- packages/react-components/src/organisms/TeamCreateOutputForm.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputExtraInformationCard.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputForm.test.tsx
> CRN-694 Edit organisms

- .pnp.cjs
- packages/errors/package.json
- packages/errors/src/asap-error.ts
- packages/errors/src/generic-error.ts
- packages/errors/src/index.ts
- packages/errors/src/not-found-error.ts
- packages/errors/src/validation-error.ts
- packages/services-common/test/framework/lambda.test.ts
- packages/squidex/test/put.test.ts
- yarn.lock
Log response.body on HTTPError
> Bugfix/Add HTTP Error response.body logging

- packages/model/src/research-output.ts
- packages/react-components/src/atoms/Dropdown.tsx
- packages/react-components/src/atoms/__tests__/Dropdown.test.tsx
- packages/react-components/src/form.ts
- packages/react-components/src/organisms/TeamCreateOutputExtraInformationCard.tsx
- packages/react-components/src/organisms/TeamCreateOutputForm.tsx
- packages/react-components/src/organisms/TeamCreateOutputIdentifier.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputForm.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputIdentifier.test.tsx
- packages/validation/src/research-output.ts
https://asaphub.atlassian.net/browse/CRN-862
> fixes removing of None from Identifier field

- apps/crn-frontend/src/network/teams/TeamOutput.tsx
- apps/crn-frontend/src/network/teams/state.ts
- apps/crn-frontend/src/shared-research/__tests__/api.test.ts
- apps/crn-frontend/src/shared-research/api.ts
- apps/storybook/src/TeamCreateOutputExtraInformationCard.stories.tsx
- apps/storybook/src/TeamCreateOutputForm.stories.tsx
- apps/storybook/src/TeamCreateOutputPage.stories.tsx
- packages/fixtures/src/research-tags.ts
- packages/react-components/src/atoms/Dropdown.tsx
- packages/react-components/src/organisms/TeamCreateOutputExtraInformationCard.tsx
- packages/react-components/src/organisms/TeamCreateOutputForm.tsx
- packages/react-components/src/organisms/TeamCreateOutputFormSharingCard.tsx
- packages/react-components/src/organisms/TeamCreateOutputIdentifier.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputExtraInformationCard.test.tsx
- packages/react-components/src/organisms/__tests__/TeamCreateOutputForm.test.tsx
- packages/react-components/src/organisms/__tests__/TeamOutputSharingCard.test.tsx
- packages/react-components/src/templates/__tests__/TeamCreateOutputPage.test.tsx
> CRN-746 Edit subtype

- .github/workflows/on-demand-algolia-sync.yml
- .github/workflows/on-push-master.yml
- .github/workflows/reusable-algolia-sync.yml
Converts Algolia-sync to a reusable workflow and adds it to the master workflow for dev and prod
> feat: CRN-863 Add Algolia sync to master workflow

- apps/storybook/src/Icons.stories.tsx
- packages/react-components/src/icons/error.tsx
- packages/react-components/src/icons/index.ts
- packages/react-components/src/molecules/ErrorCard.tsx
- packages/react-components/src/molecules/ToastCard.tsx
- packages/react-components/src/molecules/__tests__/ErrorCard.test.tsx
- packages/react-components/src/molecules/__tests__/ToastCard.test.tsx
- packages/react-components/src/organisms/Toast.tsx
- packages/react-components/src/organisms/__tests__/EditModal.test.tsx
- packages/react-components/src/organisms/__tests__/EventCard.test.tsx
Replaces warning icon by error icon in ErrorCard component.
> Fix error card icon

- packages/react-components/src/molecules/AssociationList.tsx
- packages/react-components/src/molecules/UsersList.tsx
I've added a wrapper div to each one of the parts, so the container treats them as two sections and apply the spaces correctly
> [CRN-972] Shared Research design issue

- .github/actions/sls-remove/action.yml
- .github/workflows/on-remove.yml
> fixes remove gp2 sls

- apps/crn-server/scripts/export-entity.ts
- apps/crn-server/src/app.ts
- apps/crn-server/src/data-providers/assets.data-provider.ts
- apps/crn-server/src/data-providers/users.data-provider.ts
- apps/crn-server/src/handlers/lab/index-lab-users-handler.ts
- apps/crn-server/src/handlers/teams/index-team-users-handler.ts
- apps/crn-server/src/handlers/user/index-handler.ts
- apps/crn-server/src/handlers/user/sync-orcid-handler.ts
- apps/crn-server/src/handlers/webhooks/cronjob-sync-orcid.ts
- apps/crn-server/src/handlers/webhooks/fetch-by-code/handler.ts
- apps/crn-server/src/handlers/webhooks/webhook-connect-by-code.ts
- apps/crn-server/src/validation/user.validation.ts
- apps/crn-server/test/data-providers/assets.data-provider.ts
- apps/crn-server/test/data-providers/users.data-provider.test.ts
- apps/crn-server/test/fixtures/users.fixtures.ts
- apps/crn-server/test/integration/research-outputs.integration-test.ts
- apps/crn-server/test/integration/users.integration-test.ts
- apps/crn-server/test/mocks/user-data-provider.mock.ts
- apps/crn-server/test/routes/user.route.test.ts
- apps/gp2-server/src/data-providers/user.data-provider.ts
- apps/gp2-server/test/data-providers/user.data-provider.test.ts
- packages/model/src/user.ts
- packages/squidex/src/entities/crn/user.ts
- packages/squidex/src/rest.ts
* adds the `role` required property to the user PATCH request payload
* modify's the integration tests to use data providers public interface only
> fix: Data Provider integration tests

- .github/actions/squidex-sync/action.yml
- .github/workflows/reusable-deployment.yml
[Syncs GP2 Squidex](https://asaphub.atlassian.net/browse/GP2-43)
To be deployed before: https://github.com/yldio/asap-hub/pull/1884
Selects which app to deploy to Squidex
> adds parameter to set squidex sync app

- .github/actions/squidex-sync/action.yml
- .github/workflows/reusable-deployment.yml
[Syncs GP2 Squidex](https://asaphub.atlassian.net/browse/GP2-43)
To be deployed after: https://github.com/yldio/asap-hub/pull/1888
This syncs production GP2 Squidex
> sync gp2 squidex production

- .github/workflows/on-schedule-backup-dev.yml
- .github/workflows/on-schedule-backup-prod.yml
https://asaphub.atlassian.net/browse/GP2-44
> backup gp2 squidex

- .github/actions/setup-environment/action.yml
- .github/scripts/squidex/common.py
- .github/scripts/squidex/create-app.py
- .github/scripts/squidex/delete-app.py
- .github/workflows/on-remove.yml
- .github/workflows/reusable-create-environment.yml
https://asaphub.atlassian.net/browse/GP2-44
This PR renames the CRN Squidex App.
> GP2 44 set up squidex pr environments backup rename crn squidex

- .pnp.cjs
- apps/asap-cli/package.json
- apps/crn-messages/package.json
- apps/crn-server/package.json
- apps/gp2-messages/package.json
- apps/gp2-server/package.json
- packages/messages-common/package.json
- packages/server-common/package.json
- yarn.lock
> Revert "fix(deps): update dependency aws-sdk to v2.1196.0"

- apps/gp2-frontend/src/AuthenticatedApp.tsx
- apps/gp2-frontend/src/users/Users.tsx
- apps/gp2-frontend/src/users/__tests__/Users.test.tsx
- packages/gp2-components/src/organisms/MainNavigation.tsx
- packages/routing/src/gp2/index.ts
- packages/routing/src/gp2/users.ts
Ticket (https://asaphub.atlassian.net/browse/GP2-76)
Created route and page with a simple header for the User tab
> feat: Users page and route added

- apps/auth0-rules/src/__tests__/add-user-metadata.test.ts
- apps/auth0-rules/src/add-user-metadata.ts
- apps/gp2-server/src/data-providers/user.data-provider.ts
- apps/gp2-server/test/data-providers/user.data-provider.test.ts
- apps/gp2-server/test/fixtures/user.fixtures.ts
- packages/model/src/gp2/user.ts
https://asaphub.atlassian.net/browse/GP2-95
> fix gp2 login

- .github/Dockerfile
- .github/workflows/on-remove.yml
- .github/workflows/on-schedule-backup-dev.yml
- .github/workflows/on-schedule-backup-prod.yml
- .github/workflows/reusable-algolia-sync.yml
- .github/workflows/reusable-build-analysis.yml
- .github/workflows/reusable-build.yml
- .github/workflows/reusable-create-environment.yml
- .github/workflows/reusable-deployment.yml
- .github/workflows/reusable-test.yml
- .github/workflows/reusable-verify.yml
- README.md
- bumps squidex cli to 8.21
- uses new package
> fix/squidex cli 8.21

- apps/gp2-frontend/src/users/Users.tsx
- apps/gp2-server/src/data-providers/user.data-provider.ts
- apps/gp2-server/test/data-providers/user.data-provider.test.ts
- apps/gp2-server/test/fixtures/user.fixtures.ts
- apps/storybook/src/AssociationList.stories.tsx
- apps/storybook/src/gp2-components/UserCard.stories.tsx
- apps/storybook/src/gp2-components/UsersPage.stories.tsx
- packages/gp2-components/src/molecules/UserRegion.tsx
- packages/gp2-components/src/molecules/__tests__/UserRegion.test.tsx
- packages/gp2-components/src/organisms/UserCard.tsx
- packages/gp2-components/src/organisms/UsersPageBody.tsx
- packages/gp2-components/src/organisms/WorkingGroupsBody.tsx
- packages/gp2-components/src/organisms/__tests__/UserCard.test.tsx
- packages/gp2-components/src/organisms/__tests__/UsersPageBody.test.tsx
- packages/gp2-components/src/templates/UsersPage.tsx
- packages/gp2-components/src/templates/__tests__/UsersPage.test.tsx
- packages/model/src/gp2/user.ts
- packages/model/tests/gp2/user.test.ts
- packages/squidex/src/entities/gp2/user.ts
(Ticket:https://asaphub.atlassian.net/browse/GP2-78)
Created the component which will show the users in the user directory.
> feat: added user entity

- packages/squidex/schema/crn/schemas/users.json
CI breaking because of missing field
> fix alumni

- packages/react-components/src/organisms/TeamCard.tsx
- packages/react-components/src/organisms/__tests__/TeamCard.test.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- packages/react-components/src/templates/TeamProfilePage.tsx
- packages/react-components/src/templates/__tests__/TeamProfileHeader.test.tsx
- packages/react-components/src/templates/__tests__/TeamProfilePage.test.tsx
Card           |  Page
Card           |  Page
> CRN 1072 Inactive Teams (FE)

- apps/auth0-rules/src/__tests__/add-user-metadata.test.ts
- apps/auth0-rules/src/__tests__/connect-user.test.ts
- apps/auth0-rules/src/add-user-metadata.ts
- apps/auth0-rules/src/connect-user.ts
- apps/auth0-rules/src/types.d.ts
- apps/crn-frontend/src/auth/Signin.tsx
- apps/crn-frontend/src/auth/__tests__/Signin.test.tsx
- apps/gp2-frontend/src/auth/Signin.tsx
- apps/storybook/src/WelcomePage.stories.tsx
- packages/react-components/src/templates/WelcomePage.tsx
- packages/react-components/src/templates/__tests__/WelcomePage.test.tsx
- add alumni rule to add-user-metadata webhook
- fix the auth0 rule invalid import
- change the error message for alumni error
> feat: CRN-1033 Prevent Alumni from accessing the hub

- apps/crn-frontend/src/network/Network.tsx
- apps/crn-frontend/src/network/__tests__/Network.test.tsx
- apps/crn-frontend/src/network/groups/GroupList.tsx
- apps/crn-server/src/controllers/groups.ts
- apps/crn-server/src/data-providers/groups.data-provider.ts
- apps/crn-server/test/controllers/groups.test.ts
- apps/crn-server/test/data-providers/groups.data-provider.test.ts
- packages/model/src/group.ts
- packages/react-components/src/templates/NetworkPageHeader.tsx
- packages/react-components/src/templates/__tests__/NetworkPageHeader.test.tsx
JIRA ticket: https://asaphub.atlassian.net/browse/CRN-1070
> CRN-1070 Adding filter to groups list view

- apps/storybook/src/gp2-components/CardWithBackground.stories.tsx
- apps/storybook/src/gp2-components/ExpandableText.stories.tsx
- apps/storybook/src/gp2-components/HeaderLogo.stories.tsx
- apps/storybook/src/gp2-components/IconWithLabel.stories.tsx
- apps/storybook/src/gp2-components/NavigationLink.stories.tsx
- apps/storybook/src/gp2-components/UserCardInfo.stories.tsx
- apps/storybook/src/gp2-components/UserMenu.stories.tsx
- packages/gp2-components/src/icons/index.ts
- packages/gp2-components/src/index.ts
- packages/gp2-components/src/molecules/index.ts
(Ticket:https://asaphub.atlassian.net/browse/GP2-96)
Added GP2 organisms into storybook
> Gp2 96 storybook frontend (molecules)

- apps/crn-frontend/src/network/Network.tsx
- apps/crn-frontend/src/network/__tests__/Network.test.tsx
- apps/crn-frontend/src/network/teams/TeamList.tsx
- apps/crn-server/src/controllers/teams.ts
- apps/crn-server/src/data-providers/teams.data-provider.ts
- apps/crn-server/test/controllers/teams.test.ts
- apps/crn-server/test/data-providers/teams.data-provider.test.ts
- packages/model/src/team.ts
- packages/react-components/src/templates/NetworkPageHeader.tsx
- packages/react-components/src/templates/__tests__/NetworkPageHeader.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/CRN-1074
> CRN-1074 Adding filter to teams list view

- apps/crn-frontend/src/network/teams/TeamProfile.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- packages/react-components/src/templates/__tests__/TeamProfileHeader.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/CRN-1087
Active Team             |  Inactive Team
> CRN-1087 Remove upcoming events tab from team detail page when inactive

- .github/scripts/contentful/teardown.sh
- .github/workflows/on-remove.yml
Reopening because previous PR failed to create Squidex app.
> CRN-1119 | Hotfix | Prevent erroneous deletion of Development environment

- apps/storybook/src/gp2-components/BasicLayout.stories.tsx
- apps/storybook/src/gp2-components/DashboardPage.stories.tsx
- apps/storybook/src/gp2-components/DashboardPageBody.stories.tsx
- apps/storybook/src/gp2-components/DashboardPageHeader.stories.tsx
- apps/storybook/src/gp2-components/ProjectDetailPage.stories.tsx
- apps/storybook/src/gp2-components/ProjectsPage.stories.tsx
- apps/storybook/src/gp2-components/Theme.stories.tsx
- apps/storybook/src/gp2-components/UserDetailPage.stories.tsx
- apps/storybook/src/gp2-components/WorkingGroupOverview.stories.tsx
- apps/storybook/src/gp2-components/WorkingGroupResources.stories.tsx
- apps/storybook/src/gp2-components/WorkingGroupsPage.stories.tsx
- packages/gp2-components/src/index.ts
- packages/gp2-components/src/templates/index.ts
(Ticket:https://asaphub.atlassian.net/browse/GP2-96)
Added GP2 templates into storybook
> Gp2 96 storybook frontend (templates)

- .pnp.cjs
- apps/gp2-server/.eslintrc.js
- apps/gp2-server/package.json
- apps/gp2-server/scripts/README
- apps/gp2-server/scripts/import-users.ts
- apps/gp2-server/src/app.ts
- apps/gp2-server/src/data-providers/user.data-provider.ts
- apps/gp2-server/src/handlers/webhooks/fetch-by-code-handler.ts
- apps/gp2-server/src/handlers/webhooks/webhook-connect-by-code.ts
- apps/gp2-server/test/data-providers/user.data-provider.test.ts
- apps/gp2-server/test/fixtures/user.fixtures.ts
- apps/gp2-server/test/mocks/user-data-provider.mock.ts
- packages/model/src/gp2/user.ts
- packages/server-common/package.json
- packages/server-common/src/utils/csv-parse.ts
- packages/server-common/src/utils/index.ts
- packages/server-common/test/utils/csv-parse.test.ts
- packages/squidex/src/entities/gp2/user.ts
- yarn.lock
> feat: GP2-101 User Import Script

- apps/auth0-rules/src/__tests__/add-user-metadata.test.ts
- apps/auth0-rules/src/add-user-metadata.ts
- apps/gp2-server/src/autogenerated-gql/gql.ts
- apps/gp2-server/src/autogenerated-gql/graphql.ts
- apps/gp2-server/src/data-providers/user.data-provider.ts
- apps/gp2-server/src/queries/users.queries.ts
- apps/gp2-server/src/schema/autogenerated-schema.graphql
- apps/gp2-server/test/fixtures/user.fixtures.ts
- packages/fixtures/src/gp2/users.ts
- packages/gp2-components/src/organisms/__tests__/UsersPageBody.test.tsx
- packages/model/src/gp2/user.ts
- packages/squidex/schema/gp2/schemas/users.json
> Revert "feat/GP2 onboarded user"

- apps/storybook/src/gp2-components/BasicLayout.stories.tsx
Changed import of Basic Layout in GP2 Storybook
> GP2 Storybook Fix

- .github/actions/contentful-checks/action.yml
- .github/actions/sls-deployment/action.yml
- .github/actions/sls-package/action.yml
- .github/scripts/contentful/create.sh
- .github/scripts/contentful/teardown.sh
- .github/workflows/on-push-branch.yml
- .github/workflows/on-remove.yml
- .github/workflows/reusable-build.yml
- .github/workflows/reusable-create-environment.yml
- .github/workflows/reusable-deployment.yml
- apps/crn-server/serverless.ts
Notable changes:
* add a `setup` job before the `build`, `create-environment` and `deployment`
* user lowercase for pseudo-boolean values
* move the contentful env limit check to where the env is actually created
Outstanding tasks for another PR
* use contentful cli to create the env
> feat: CRN-1122 Set Contentful Env for Serverless

- .github/workflows/on-push-master.yml
- .github/workflows/reusable-build.yml
- .github/workflows/reusable-deployment.yml
- add content env input
- make input required
> fix: Contentful Env Missing 

- apps/crn-server/src/autogenerated-gql/graphql.ts
- apps/crn-server/src/schema/autogenerated-schema.graphql
- packages/squidex/schema/crn/schemas/working-groups.json
Adds the new Working Groups schema to Squidex
> feat: CRN-1048 Create Working Group entity - part 1

- .github/workflows/reusable-deployment.yml
- .gitignore
- modify the migration-runner job
- Add a migration & add emacs tempfiles to gitignore.
> feat: CRN-1122 Run Contentful migrations for PR envs

- apps/crn-frontend/src/AuthenticatedApp.tsx
- packages/gp2-components/src/organisms/UserNavigation.tsx
- packages/gp2-components/src/organisms/__tests__/UserNavigation.test.tsx
- packages/react-components/src/molecules/UserMenuButton.tsx
- packages/react-components/src/molecules/__tests__/UserMenuButton.test.tsx
- packages/react-components/src/templates/Layout.tsx
Fix: Unknown User being displayed on Login.
> Fix/GP2 Unknown User

- apps/gp2-frontend/src/working-groups/WorkingGroupDetail.tsx
- apps/gp2-frontend/src/working-groups/__tests__/WorkingGroupDetail.test.tsx
Restricts the add resources route on working groups to administrators only
> only renders add resource route when user is administrator

- .github/scripts/contentful/teardown.sh
- .github/workflows/on-remove.yml
First run:
Second run against the same PR:
> fix: CRN-1157 Contentful Environment Teardown

- packages/contentful/migrations/news/20221109111824-remove-id-from-news.js
> CRN-1052 Removes field id from news content model (Contentful)

- apps/gp2-frontend/src/projects/ProjectDetail.tsx
- apps/gp2-frontend/src/projects/__tests__/ProjectDetail.test.tsx
- apps/gp2-frontend/src/projects/__tests__/api.test.tsx
- apps/gp2-frontend/src/projects/api.ts
- apps/gp2-frontend/src/projects/state.ts
- apps/gp2-frontend/src/working-groups/WorkingGroupDetail.tsx
- packages/fixtures/src/gp2/projects.ts
- packages/gp2-components/src/templates/__tests__/ProjectResources.test.tsx
- packages/gp2-components/src/templates/__tests__/WorkingGroupResources.test.tsx
https://asaphub.atlassian.net/browse/GP2-121
> GP-121 - Add project resource to client

- .pnp.cjs
- apps/crn-frontend/src/__tests__/App.test.tsx
- apps/crn-frontend/src/__tests__/AuthenticatedApp.test.tsx
- apps/crn-frontend/src/auth/__tests__/CheckAuth.test.tsx
- apps/crn-frontend/src/auth/__tests__/Logout.test.tsx
- apps/crn-frontend/src/auth/__tests__/Signin.test.tsx
- apps/crn-frontend/src/onboarding/__tests__/ContinueOnboarding.test.tsx
- apps/crn-frontend/src/welcome/__tests__/Welcome.test.tsx
- apps/crn-server/test/routes/reminders.route.test.ts
- apps/crn-server/test/routes/teams.route.test.ts
- apps/gp2-frontend/src/__tests__/App.test.tsx
- apps/gp2-frontend/src/__tests__/AuthenticatedApp.test.tsx
- apps/gp2-frontend/src/auth/__tests__/CheckAuth.test.tsx
- apps/gp2-frontend/src/auth/__tests__/Logout.test.tsx
- apps/gp2-frontend/src/auth/__tests__/Signin.test.tsx
- apps/gp2-frontend/src/welcome/__tests__/Welcome.test.tsx
- apps/storybook/src/Layout.stories.tsx
- apps/storybook/src/UserMenuButton.stories.tsx
- packages/fixtures/src/auth.ts
- packages/fixtures/src/gp2/auth.ts
- packages/fixtures/src/gp2/index.ts
- packages/gp2-components/package.json
- packages/gp2-components/src/auth-test-utils.tsx
- packages/gp2-components/src/index.ts
- packages/gp2-components/src/organisms/__tests__/UserNavigation.test.tsx
- packages/gp2-components/tsconfig.json
- packages/react-components/src/auth-test-utils.tsx
- yarn.lock
- starts refactor of Auth0ProviderCRN
- continues refactoring of auth-test-utils"
- rename crn auth test
- rename gp2 auth test
> GP2 121 auth test utils

- .github/actions/test-unit/action.yml
- apps/crn-server/src/data-providers/users.data-provider.ts
- apps/crn-server/test/data-providers/users.data-provider.test.ts
> removes unused parseUserToDataObject

- apps/gp2-server/src/data-providers/user.data-provider.ts
- apps/gp2-server/src/routes/user.route.ts
- apps/gp2-server/src/validation/user.validation.ts
- apps/gp2-server/test/data-providers/user.data-provider.test.ts
- apps/gp2-server/test/fixtures/user.fixtures.ts
- apps/gp2-server/test/routes/user.route.test.ts
- packages/model/src/gp2/user.ts
- packages/squidex/src/entities/gp2/user.ts
- packages/validation/src/gp2/index.ts
- packages/validation/src/gp2/user.ts
- packages/validation/src/index.ts
- packages/validation/test/fixtures/gp2/user.fixtures.ts
- packages/validation/test/gp2/user.test.ts
- adds patch user route to gp2
- adds extra coverage over onboarding user
> GP2 111 onboarding user core details edit modal simple data set user patch

- apps/gp2-frontend/src/working-groups/EditResourceModal.tsx
- apps/gp2-frontend/src/working-groups/__tests__/EditResourceModal.test.tsx
- packages/gp2-components/src/organisms/ResourceModal.tsx
- packages/gp2-components/src/organisms/__tests__/ResourceModal.test.tsx
- packages/react-components/src/organisms/EditModal.tsx
(Ticket:https://asaphub.atlassian.net/browse/GP2-127)
Delete Resource from Working Group
> GP2-127-Frontend

- apps/gp2-frontend/src/hooks/__tests__/search.test.ts
- apps/gp2-frontend/src/hooks/search.ts
- apps/gp2-frontend/src/projects/state.ts
- apps/gp2-frontend/src/users/UserList.tsx
- apps/gp2-frontend/src/users/__tests__/Routes.test.tsx
- apps/gp2-frontend/src/users/__tests__/UserList.test.tsx
- apps/gp2-frontend/src/users/__tests__/api.test.tsx
- apps/gp2-frontend/src/users/api.ts
- apps/gp2-frontend/src/working-groups/WorkingGroupList.tsx
- apps/gp2-frontend/src/working-groups/__tests__/Routes.test.tsx
- apps/gp2-frontend/src/working-groups/__tests__/WorkingGroupList.test.tsx
- apps/gp2-frontend/src/working-groups/__tests__/api.test.tsx
- apps/gp2-frontend/src/working-groups/api.ts
- apps/gp2-frontend/src/working-groups/state.ts
- apps/gp2-server/src/data-providers/user.data-provider.ts
- apps/gp2-server/src/routes/user.route.ts
- apps/gp2-server/test/controllers/user.controller.test.ts
- apps/gp2-server/test/data-providers/user.data-provider.test.ts
- apps/gp2-server/test/routes/user.route.test.ts
- packages/gp2-components/src/organisms/FiltersModal.tsx
- packages/gp2-components/src/organisms/__tests__/FiltersModal.test.tsx
- packages/model/src/gp2/common.ts
- packages/model/src/gp2/project.ts
- packages/model/src/gp2/user.ts
- packages/server-common/src/validation/validation.ts
> Add Expertise/Interest, Working Groups, Projects to filter's modal and search query to request

- apps/crn-frontend/src/network/Network.tsx
- apps/crn-frontend/src/network/__tests__/Network.test.tsx
- apps/crn-frontend/src/network/groups/GroupList.tsx
- apps/crn-frontend/src/network/groups/__tests__/GroupList.test.tsx
- apps/crn-frontend/src/network/teams/TeamList.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamList.test.tsx
- apps/crn-frontend/src/network/users/UserList.tsx
- apps/crn-frontend/src/network/users/__tests__/UserList.test.tsx
- apps/crn-frontend/src/network/working-groups/WorkingGroupList.tsx
- apps/crn-frontend/src/network/working-groups/__tests__/WorkingGroupList.test.tsx
- apps/crn-frontend/src/network/working-groups/api.ts
- apps/crn-frontend/src/network/working-groups/state.ts
- apps/crn-server/src/controllers/working-groups.ts
- apps/crn-server/src/data-providers/working-groups.data-provider.ts
- apps/crn-server/test/controllers/working-groups.test.ts
- apps/crn-server/test/data-providers/working-groups.data-provider.test.ts
- packages/fixtures/src/working-groups.ts
- packages/model/src/working-group.ts
- packages/react-components/src/templates/NetworkPageHeader.tsx
- packages/react-components/src/templates/__tests__/NetworkPageHeader.test.tsx
Jira ticket https://asaphub.atlassian.net/browse/CRN-1180
> [CRN-1180] Add search bar and filter for working groups list page

- apps/storybook/src/NetworkWorkingGroups.stories.tsx
- apps/storybook/src/WorkingGroupCard.stories.tsx
- packages/react-components/src/organisms/WorkingGroupCard.tsx
- packages/react-components/src/organisms/__tests__/WorkingGroupCard.test.tsx
- packages/react-components/src/templates/__tests__/NetworkWorkingGroups.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/CRN-1195
Mobile           |  Desktop
> CRN-1195 Complete tag in Working Group List View

- apps/gp2-frontend/public/index.html
- apps/gp2-frontend/src/onboarding/CoreDetails.tsx
- apps/gp2-frontend/src/onboarding/Routes.tsx
- apps/gp2-frontend/src/onboarding/__tests__/CoreDetails.test.tsx
- packages/fixtures/src/gp2/users.ts
- packages/gp2-components/src/index.ts
- packages/gp2-components/src/molecules/ContactSupport.tsx
- packages/gp2-components/src/molecules/index.ts
- packages/gp2-components/src/organisms/ContactInformationModal.tsx
- packages/gp2-components/src/organisms/KeyInformationModal.tsx
- packages/gp2-components/src/organisms/UsersPageBody.tsx
- packages/gp2-components/src/organisms/__tests__/ContactInformationModal.test.tsx
- packages/gp2-components/src/organisms/__tests__/UsersPageBody.test.tsx
- packages/gp2-components/src/organisms/index.ts
- packages/react-components/src/atoms/Subtitle.tsx
- packages/react-components/src/molecules/LabeledTextField.tsx
Tickets:
https://asaphub.atlassian.net/browse/GP2-147
https://asaphub.atlassian.net/browse/GP2-139
> add Onboarding - Contact Details Modal and Users - display pagination information

- apps/crn-frontend/src/network/__tests__/Network.test.tsx
- apps/gp2-frontend/src/users/__tests__/UserDetail.test.tsx
- apps/gp2-server/src/handlers/user/invite-handler.ts
- apps/gp2-server/test/handlers/webhooks/webhook-connect-by-code.test.ts
- packages/gp2-components/src/templates/UserOverview.tsx
- packages/gp2-components/src/templates/__tests__/UserOverview.test.tsx
- packages/server-common/src/handlers/user/invite.handler.ts
> renames expertise and interests to keywords

- packages/model/src/research-output.ts
- packages/squidex/schema/crn/schemas/research-tags.json
Jira ticket: https://asaphub.atlassian.net/browse/CRN-995
- To add one new Protocol Type named ‘Sequencing’ to the Research Tags entity in the CMS
- To add one new Type named ‘Sequencing’ to the Protocol Document Type drop-down list on the Shared Output form
> CRN-995 Add New Type to Protocol shared output form

- apps/gp2-frontend/src/onboarding/Background.tsx
- apps/gp2-frontend/src/onboarding/__tests__/Background.test.tsx
- packages/gp2-components/src/index.ts
- packages/gp2-components/src/molecules/ContactSupport.tsx
- packages/gp2-components/src/organisms/KeywordsModal.tsx
- packages/gp2-components/src/organisms/__tests__/KeywordsModal.test.tsx
- packages/gp2-components/src/organisms/index.ts
- packages/react-components/src/atoms/MultiSelect.tsx
Ticket: https://asaphub.atlassian.net/browse/GP2-149
> add Keywords modal to Onboarding

- apps/crn-server/src/autogenerated-gql/graphql.ts
- apps/crn-server/src/schema/autogenerated-schema.graphql
- apps/gp2-server/src/autogenerated-gql/graphql.ts
- apps/gp2-server/src/schema/autogenerated-schema.graphql
> Squidex Schema

- packages/gp2-components/src/molecules/EditableCard.tsx
- packages/gp2-components/src/molecules/UserPosition.tsx
- packages/gp2-components/src/molecules/UserPositions.tsx
- packages/gp2-components/src/organisms/Resources.tsx
- packages/gp2-components/src/organisms/UserDetailHeaderCard.tsx
(Ticket:https://asaphub.atlassian.net/browse/GP2-190)
Fix positioning of certain icons, namely the add, the edit and the copy (and others that appear)
> GP2-190-Icons

- apps/crn-server/test/fixtures/news.fixtures.ts
- apps/gp2-server/src/autogenerated-gql/gql.ts
- apps/gp2-server/src/autogenerated-gql/graphql.ts
- apps/gp2-server/src/data-providers/news.data-provider.ts
- apps/gp2-server/src/queries/news.queries.ts
- apps/gp2-server/src/schema/autogenerated-schema.graphql
- apps/gp2-server/test/fixtures/news.fixtures.ts
- packages/model/src/gp2/news.ts
- packages/squidex/schema/gp2/schemas/news-and-events.json
In the GP2 News Schema/Response:
> updates news schema to have short text

- .github/workflows/reusable-test.yml
> Remove concurrency limit as it doesn't seem to help.

- apps/crn-frontend/src/network/groups/GroupProfile.tsx
- apps/crn-frontend/src/network/working-groups/Calendar.tsx
- apps/crn-frontend/src/network/working-groups/WorkingGroupProfile.tsx
- apps/crn-frontend/src/network/working-groups/__tests__/WorkingGroupProfile.test.tsx
- apps/storybook/src/GroupProfileCalendar.stories.tsx
- packages/model/src/working-group.ts
- packages/react-components/src/templates/GroupProfileCalendar.tsx
- packages/react-components/src/templates/WorkingGroupPageHeader.tsx
- packages/react-components/src/templates/__tests__/GroupProfileCalendar.test.tsx
- packages/routing/src/network.ts
Jira ticket: https://asaphub.atlassian.net/browse/CRN-1296
---
Hub: https://2576.hub.asap.science/network/working-groups/0182aef4-0d46-4ec7-aae0-584d0b0e3bad/calendar
> CRN-1296 Calendar Page for Working Groups

- .github/workflows/reusable-verify.yml
- apps/e2e-tests/jest-e2e.config.js
Add longer timeout to e2e tests
Add retry logic to e2e tests
> fix: Verify step

- packages/gp2-components/src/organisms/Resources.tsx
(Ticket:https://asaphub.atlassian.net/browse/GP2-263)
Change the color of the resource title to blue if the resource has the type 'Link'
> GP2-263-Frontend

- apps/storybook/src/gp2-components/Resources.stories.tsx
- packages/gp2-components/src/organisms/Resources.tsx
- packages/gp2-components/src/organisms/__tests__/Resources.test.tsx
- packages/gp2-components/src/templates/ProjectResources.tsx
- packages/gp2-components/src/templates/WorkingGroupResources.tsx
- packages/react-components/src/atoms/Card.tsx
(Ticket: https://asaphub.atlassian.net/browse/GP2-234)
Change color and format of the information note in resources
> GP2-234-Informational-Message

- README.md
There were a few non-obvious bits of the README when it came to getting things set up for the first time locally. Add a few lines of guidance to hopefully make this a bit more obvious.
> Add guidance on setting up users for the first time

- apps/gp2-frontend/src/AuthenticatedApp.tsx
- apps/gp2-frontend/src/OnboardedApp.tsx
- apps/gp2-frontend/src/__tests__/OnboardedApp.test.tsx
- apps/gp2-frontend/src/dashboard/Dashboard.tsx
- apps/gp2-frontend/src/dashboard/__tests__/Dashboard.test.tsx
- apps/storybook/src/gp2-components/DashboardPageBody.stories.tsx
- packages/gp2-components/src/templates/DashboardPageBody.tsx
- packages/gp2-components/src/templates/__tests__/DashboardPageBody.test.tsx
- packages/react-components/src/organisms/DashboardUpcomingEvents.tsx
Ticket: https://asaphub.atlassian.net/browse/GP2-194
> add upcoming events on Dashboard

- apps/crn-server/src/app.ts
- apps/crn-server/src/controllers/events.ts
- apps/crn-server/src/handlers/event/index-event-handler.ts
- apps/crn-server/src/handlers/event/index-external-author-events-handler.ts
- apps/crn-server/src/handlers/event/index-group-events-handler.ts
- apps/crn-server/src/handlers/event/index-team-events-handler.ts
- apps/crn-server/src/handlers/event/index-user-events-handler.ts
- apps/crn-server/src/handlers/webhooks/webhook-events-updated.ts
- apps/crn-server/src/routes/events.route.ts
- apps/crn-server/src/routes/groups.route.ts
- apps/crn-server/test/fixtures/calendars.fixtures.ts
- packages/server-common/src/controllers/event.controller.ts
- packages/server-common/src/controllers/index.ts
- packages/server-common/src/handlers/calendar/subscribe-handler.ts
- packages/server-common/src/handlers/webhooks/events-updated.handler.ts
- packages/server-common/src/handlers/webhooks/index.ts
- packages/server-common/src/utils/index.ts
- packages/server-common/src/utils/sync-google-calendar.ts
- packages/server-common/src/utils/sync-google-event.ts
- packages/server-common/src/validation/sync-google-event.validation.ts
- packages/server-common/test/fixtures/calendar.fixtures.ts
- packages/server-common/test/fixtures/events.fixtures.ts
- packages/server-common/test/fixtures/google-events.fixtures.ts
- packages/server-common/test/handlers/webhooks/connect-by-code.handler.test.ts
- packages/server-common/test/handlers/webhooks/events-updated.handler.test.ts
- packages/server-common/test/mocks/event-controller.mock.ts
- packages/server-common/test/utils/sync-google-calendar.test.ts
- packages/server-common/test/utils/sync-google-event.test.ts
> GP2 event handler

- .github/renovate.json
- .github/workflows/on-push-branch.yml
Remove limits on package updates
> Cancel branch inprogress jobs

- .github/actions/algolia-import-entity/action.yml
- .github/actions/contentful-checks/action.yml
- .github/workflows/on-demand-algolia-sync.yml
- .github/workflows/reusable-algolia-sync.yml
- .github/workflows/reusable-create-environment.yml
- .github/workflows/reusable-deployment.yml
- apps/crn-server/scripts/export-entity.ts
- apps/crn-server/src/data-providers/contentful/users.data-provider.ts
- apps/crn-server/test/data-providers/contentful/users.data-provider.test.ts
- create and set up algolia index for contentful on branch
- add on-demand algolia sync for contentful
- add a dummy UserContentfulDataProvider to simulate syncing from Contentful
> feat: CRN-1274 Algolia Contentful Setup

- apps/gp2-auth-frontend/__tests__/html-snapshot.build-output-test.ts
- apps/gp2-auth-frontend/public/index.html
(Ticket: https://asaphub.atlassian.net/browse/GP2-268)
Fix typeface of Sign In page title
> GP2-268 Fix typeface of Sign In page title

- packages/gp2-components/src/organisms/Resources.tsx
- packages/gp2-components/src/organisms/__tests__/Resources.test.tsx
(Ticket: https://asaphub.atlassian.net/browse/GP2-263)
Add the title of the resource to the link
> GP2 263 - Fix the title of resources in resource list

- .github/actions/test-unit/action.yml
> Revert "Remove retry"

- packages/gp2-components/src/organisms/UserProjects.tsx
- packages/gp2-components/src/organisms/UserWorkingGroups.tsx
- packages/gp2-components/src/organisms/__tests__/UserProjects.test.tsx
- packages/gp2-components/src/organisms/__tests__/UserWorkingGroups.test.tsx
(Ticket:https://asaphub.atlassian.net/browse/GP2-269)
Add empty state to the GP2 groups for the onboarding
> GP2 269 - (Onboarding) GP2 Groups Empty State

- apps/gp2-frontend/src/events/Event.tsx
- packages/fixtures/src/gp2/events.ts
- packages/gp2-components/src/index.ts
- packages/gp2-components/src/molecules/EventSpeakers.tsx
- packages/gp2-components/src/molecules/__tests__/EventSpeakers.test.tsx
- packages/gp2-components/src/molecules/index.ts
- packages/gp2-components/src/templates/components.tsx
- packages/model/src/gp2/event.ts
- packages/react-components/src/molecules/Collapsible.tsx
- packages/react-components/src/templates/EventPage.tsx
- packages/react-components/src/types/emotion.d.ts
Ticket: https://asaphub.atlassian.net/browse/GP2-249
> add speakers section to event details page

- packages/gp2-components/src/templates/OutputForm.tsx
- packages/react-components/src/organisms/Form.tsx
- packages/react-components/src/organisms/__tests__/Form.test.tsx
- packages/react-components/src/templates/ResearchOutputForm.tsx
- packages/react-components/src/templates/__tests__/ResearchOutputForm.test.tsx
Addressing this comment https://github.com/yldio/asap-hub/pull/2756#discussion_r1129290729
> refactor: Form returns getWrappedOnSave as children param

- apps/gp2-frontend/src/outputs/OutputList.tsx
- apps/gp2-frontend/src/outputs/__tests__/api.test.tsx
- apps/gp2-frontend/src/outputs/api.ts
- apps/gp2-frontend/src/outputs/state.ts
- apps/gp2-frontend/src/working-groups/WorkingGroupDetail.tsx
- apps/gp2-frontend/src/working-groups/__tests__/WorkingGroupDetail.test.tsx
- apps/gp2-server/src/routes/output.route.ts
- apps/gp2-server/src/validation/output.validation.ts
- apps/gp2-server/test/routes/output.route.test.ts
- packages/gp2-components/src/organisms/WorkingGroupDetailHeader.tsx
- packages/model/src/gp2/output.ts
Ticket: https://asaphub.atlassian.net/browse/GP2-274
> add shared outputs to working group details page

- apps/storybook/src/RelatedResearch.stories.tsx
- packages/react-components/src/atoms/Pill.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/RelatedResearch.tsx
- packages/react-components/src/organisms/__tests__/RelatedResearch.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/SharedResearchOutput.tsx
- packages/react-components/src/templates/__tests__/SharedResearchOutput.test.tsx
> Added new relatedResearch component

- .github/actions/contentful-backup/action.yml
- .github/environment/Development
- .github/environment/Production
- .github/workflows/on-schedule-backup-dev.yml
- .github/workflows/on-schedule-backup-prod.yml
- apps/crn-server/serverless.ts
- package.json
- yarn.lock
* Creates a new S3 bucket for storing CRN contentful backups
* Creates a new action for generating the backup and pushing to S3
* Adds a call to this action to the dev and prod nightly backup builds
> CRN-1321 - add contentful backup job to nightly backup workflow

- apps/gp2-frontend/src/users/UserDetail.tsx
- apps/gp2-frontend/src/users/__tests__/UserDetail.test.tsx
- packages/gp2-components/src/organisms/ProjectDetailHeader.tsx
- packages/gp2-components/src/organisms/UserDetailHeader.tsx
- packages/routing/src/gp2/users.ts
Ticket: https://asaphub.atlassian.net/browse/GP2-276
> add shared outputs to user details page

- apps/crn-frontend/src/events/__tests__/EventList.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- apps/gp2-frontend/src/events/__tests__/api.test.ts
- apps/gp2-frontend/src/events/api.ts
- apps/gp2-frontend/src/projects/ProjectDetail.tsx
- apps/gp2-frontend/src/projects/Routes.tsx
- apps/gp2-frontend/src/projects/__tests__/ProjectDetail.test.tsx
- apps/gp2-frontend/src/working-groups/WorkingGroupDetail.tsx
- packages/frontend-utils/src/events/__tests__/options.test.tsx
- packages/frontend-utils/src/events/index.ts
- packages/gp2-components/src/organisms/ProjectDetailHeader.tsx
- empty commit to create pr
- adds events upcoming and past to working groups
- adds test coverage for events
- adds missing coverage
- tests correct count is displayed
- starts adding events to projects page
> GP2 224 upcoming and past events on projects tab

- apps/gp2-frontend/src/onboarding/Routes.tsx
Ticket: https://asaphub.atlassian.net/browse/GP2-233
> GP2-233 fix onboarding loading

- packages/gp2-components/src/organisms/KeyInformationModal.tsx
- packages/react-components/src/organisms/EditModal.tsx
- fixing bug on modal prompt after save
- empty commit
> GP2 283 bug fix 2

- .github/actions/test-unit/action.yml
- packages/gp2-components/src/templates/__tests__/OutputForm.test.tsx
- empty commit
- wip
- updates for OutputForm test
> GP2 OutputForm tests

- packages/gp2-components/src/templates/ProjectOverview.tsx
- packages/gp2-components/src/templates/WorkingGroupOverview.tsx
- packages/react-components/src/molecules/MembersList.tsx
- packages/react-components/src/molecules/__tests__/MembersList.test.tsx
Ticket: https://asaphub.atlassian.net/browse/GP2-321
> gp2-321 fix users links on project and working group details pages

- apps/gp2-frontend/src/outputs/OutputList.tsx
- packages/gp2-components/src/organisms/OutputCard.tsx
- packages/gp2-components/src/organisms/__tests__/OutputCard.test.tsx
Ticket: https://asaphub.atlassian.net/browse/GP2-319
> fix Output card on Outputs page to only show the edit button if user is an administrator

- apps/gp2-frontend/src/events/EventsList.tsx
- apps/gp2-frontend/src/events/__tests__/Routes.test.tsx
- packages/gp2-components/src/icons/index.ts
- packages/gp2-components/src/icons/no-event-calendar-icon.tsx
- packages/gp2-components/src/index.ts
- packages/gp2-components/src/molecules/EmptyState.tsx
- packages/gp2-components/src/organisms/ProjectsBody.tsx
(Ticket : https://asaphub.atlassian.net/browse/GP2-226)
Add empty state to upcoming and past events in the events page
> GP2-226 - Events - empty state page on main Events page

- apps/crn-frontend/src/network/ProfileSwitch.tsx
- apps/crn-frontend/src/network/teams/Outputs.tsx
- apps/crn-frontend/src/network/teams/TeamProfile.tsx
- apps/crn-frontend/src/network/teams/__tests__/Outputs.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- apps/crn-frontend/src/network/working-groups/Outputs.tsx
- apps/crn-frontend/src/network/working-groups/WorkingGroupProfile.tsx
- apps/crn-frontend/src/network/working-groups/__tests__/Outputs.test.tsx
- apps/crn-frontend/src/network/working-groups/__tests__/WorkingGroupProfile.test.tsx
- apps/crn-frontend/src/shared-research/__mocks__/api.ts
- apps/crn-frontend/src/shared-research/__tests__/api.test.ts
- apps/crn-frontend/src/shared-research/__tests__/export.test.ts
- apps/crn-frontend/src/shared-research/api.ts
- apps/crn-frontend/src/shared-research/export.ts
- apps/crn-frontend/src/shared-research/state.ts
- apps/storybook/src/ProfileOutputs.stories.tsx
- apps/storybook/src/SharedResearchCard.stories.tsx
- packages/react-components/src/atoms/Pill.tsx
- packages/react-components/src/atoms/__tests__/Pill.test.tsx
- packages/react-components/src/organisms/SharedResearchCard.tsx
- packages/react-components/src/organisms/__tests__/SharedResearchCard.test.tsx
- packages/react-components/src/templates/NoOutputsPage.tsx
- packages/react-components/src/templates/ProfileOutputs.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- packages/react-components/src/templates/WorkingGroupPageHeader.tsx
- packages/react-components/src/templates/__tests__/ProfileOutputs.test.tsx
- packages/react-components/src/templates/__tests__/TeamProfileHeader.test.tsx
- packages/react-components/src/templates/__tests__/WorkingGroupPageHeader.test.tsx
- packages/routing/src/network.ts
This is ready for review. Please ignore the backend stuff as its going in on a different PR
>  Display Shared Research Drafts for Team and Work Group

- packages/react-components/src/layout.ts
- packages/react-components/src/organisms/NoEvents.tsx
- packages/react-components/src/organisms/ProfileCardList.tsx
- packages/react-components/src/templates/GroupProfileHeader.tsx
- packages/react-components/src/templates/GroupProfilePage.tsx
- packages/react-components/src/templates/NetworkPageHeader.tsx
- packages/react-components/src/templates/NoOutputsPage.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- packages/react-components/src/templates/TeamProfilePage.tsx
- packages/react-components/src/templates/UserProfileHeader.tsx
- packages/react-components/src/templates/UserProfilePage.tsx
- packages/react-components/src/templates/UserProfileSearchAndFilter.tsx
- packages/react-components/src/templates/WorkingGroupPage.tsx
- packages/react-components/src/templates/WorkingGroupPageHeader.tsx
> Revert "Refactored some of the spacing on the network, user, team, interest a…"

- packages/gp2-components/src/organisms/__tests__/KeyInformationModal.test.tsx
This was failing occasionally in CI with a timeout. Increase the timeout so it doesn't.
> Increase timeout for long-running test

- apps/gp2-server/src/app.ts
- apps/gp2-server/src/autogenerated-gql/graphql.ts
- apps/gp2-server/src/controllers/page.controller.ts
- apps/gp2-server/src/data-providers/page.data-provider.ts
- apps/gp2-server/src/entities/index.ts
- apps/gp2-server/src/entities/page.entity.ts
- apps/gp2-server/src/routes/page.route.ts
- apps/gp2-server/src/schema/autogenerated-schema.graphql
- apps/gp2-server/test/controllers/page.controller.test.ts
- apps/gp2-server/test/data-providers/page.data-provider.test.ts
- apps/gp2-server/test/fixtures/page.fixtures.ts
- apps/gp2-server/test/mocks/page-controller.mock.ts
- apps/gp2-server/test/mocks/page-data-provider.mock.ts
- apps/gp2-server/test/routes/page.route.test.ts
- packages/squidex/schema/gp2/schemas/pages.json
(Ticket: https://asaphub.atlassian.net/browse/GP2-281)
Create the backend for the Privacy Policy and Terms and Conditions pages
> GP2 281 - Pages - Privacy Policy and Terms and Conditions (backend)

- .github/actions/setup-environment/action.yml
- .github/actions/sls-deployment/action.yml
- .github/actions/sls-package/action.yml
- .github/environment/Branch
- .github/environment/Development
- .github/environment/Production
- .github/workflows/on-remove.yml
- .github/workflows/reusable-algolia-sync.yml
- .github/workflows/reusable-build.yml
- .github/workflows/reusable-create-environment.yml
- .github/workflows/reusable-deployment.yml
- apps/crn-server/serverless.ts
- empty commit
- update github actions to prefix with crn for algolia
- updates algolia to use new crn prefix
- updates crn serverless to read from correct variable
> GP2 setup algolia 2

- packages/gp2-components/src/molecules/UserMenu.tsx
- packages/gp2-components/src/molecules/__tests__/UserMenu.test.tsx
- packages/gp2-components/src/organisms/UserNavigation.tsx
(Ticket:https://asaphub.atlassian.net/browse/GP2-338)
Add the ability to close the User Menu dropdown when the user clicks anywhere on the page
> GP2-338 - Close dropdown when clicking anywhere on the page

- apps/gp2-frontend/src/App.tsx
- apps/gp2-frontend/src/content/Content.tsx
- apps/gp2-frontend/src/content/__mocks__/api.ts
- apps/gp2-frontend/src/content/__tests__/Content.test.tsx
- apps/gp2-frontend/src/content/__tests__/api.test.ts
- apps/gp2-frontend/src/content/api.ts
- apps/gp2-frontend/src/content/state.ts
- packages/gp2-components/src/molecules/UserMenu.tsx
- packages/gp2-components/src/molecules/__tests__/UserMenu.test.tsx
- packages/gp2-components/src/templates/components.tsx
- packages/react-components/src/templates/ContentPage.tsx
- packages/react-components/src/types/emotion.d.ts
(Ticket: https://asaphub.atlassian.net/browse/GP2-281)
Create the frontend for the Privacy Policy and Terms and Conditions pages
> GP2 281 - Pages - Privacy Policy and Terms and Conditions (frontend) 

- .github/workflows/reusable-verify.yml
- apps/e2e-tests/config.ts
- Adds E2E test coverage to GP2
> e2e tests cover gp2

- packages/gp2-components/src/molecules/HeaderLogo.tsx
- packages/gp2-components/src/molecules/__tests__/HeaderLogo.test.tsx
- packages/gp2-components/src/organisms/MainNavigation.tsx
- packages/gp2-components/src/organisms/NavigationHeader.tsx
- packages/gp2-components/src/organisms/UserNavigation.tsx
- packages/gp2-components/src/organisms/__tests__/UserNavigation.test.tsx
(Ticket: https://asaphub.atlassian.net/browse/GP2-339)
Fix the spacing between the components inside the Navigation Bar, aswell as the removal of some elements.
> GP2 339 - Fix Navigation Bar

- .github/workflows/on-remove.yml
- apps/gp2-server/serverless.ts
- notify of failure on gp2 contentful removal
- adds backup S3 for contentful
> GP2 380 add backup and restore workflows

- apps/gp2-frontend/src/outputs/state.ts
(Ticket: https://asaphub.atlassian.net/browse/GP2-423)
> GP2 423 - Outputs not updating after create/update

- apps/gp2-server/src/validation/user.validation.ts
- packages/gp2-components/src/organisms/ContactInformationModal.tsx
- packages/gp2-components/src/organisms/OpenQuestionsModal.tsx
- packages/gp2-components/src/organisms/__tests__/ContactInformationModal.test.tsx
- packages/gp2-components/src/organisms/__tests__/OpenQuestionsModal.test.tsx
https://asaphub.atlassian.net/jira/software/projects/GP2/boards/9?selectedIssue=GP2-446
> addresing changes to open question modal

- packages/contentful/migrations/gp2/contributingCohorts/6ekgyp1432o9-create-contributing-cohorts-1682073967694.js
- packages/contentful/migrations/gp2/contributingCohortsMembership/6ekgyp1432o9-create-contributing-cohorts-membership-1682073967694.js
- packages/contentful/migrations/gp2/users/5v6w5j61tndm-create-users-1681926038954.js
- packages/contentful/migrations/gp2/users/6ekgyp1432o9-create-users-1682073967694.js
- packages/contentful/src/gp2/autogenerated-gql/graphql.ts
- packages/contentful/src/gp2/schema/autogenerated-schema.graphql
Ticket: https://asaphub.atlassian.net/browse/GP2-387
> GP2-387 create users, contributing cohorts and contributing cohorts membership content model

- apps/crn-frontend/src/network/teams/TeamOutput.tsx
- apps/crn-frontend/src/network/working-groups/WorkingGroupOutput.tsx
- apps/crn-frontend/src/shared-research.ts
- apps/crn-frontend/src/shared-research/state.ts
https://asaphub.atlassian.net/jira/software/c/projects/CRN/boards/8?modal=detail&selectedIssue=CRN-1375
The pr is related to this ticket.
> Added force refresh of the algolia RO index after publishing

- packages/cms-data-sync/src/run-migrations.ts
- packages/cms-data-sync/test/run-migrations.test.ts
This PR makes sure that when multiple webhooks are attached to the environment that we are migrating data to - all of them gets deactived during the migration and then activated back.
> feat: CT-42 Disable all attached webhooks

- apps/gp2-server/src/data-providers/contentful/output.data-provider.ts
- apps/gp2-server/test/data-providers/contentful/output.data-provider.test.ts
> Revert "fixes output date order"

- apps/gp2-server/src/data-providers/contentful/output.data-provider.ts
- apps/gp2-server/test/data-providers/contentful/output.data-provider.test.ts
> Revert "Revert "fixes output date order""

- apps/crn-frontend/src/__tests__/shared-research.test.ts
- apps/crn-frontend/src/network/teams/TeamOutput.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamOutput.test.tsx
- apps/crn-frontend/src/network/working-groups/WorkingGroupOutput.tsx
- apps/crn-frontend/src/network/working-groups/__tests__/WorkingGroupOutput.test.tsx
- apps/crn-frontend/src/shared-research.ts
- packages/react-components/src/organisms/SharedOutputDropdown.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- packages/react-components/src/templates/WorkingGroupPageHeader.tsx
- packages/routing/src/index.ts
- packages/routing/src/network.ts
Add it to Team menu.
Fix alphabetical order on other menu
> Add report type to routing.

- apps/crn-frontend/src/network/teams/__tests__/TeamOutput.test.tsx
- apps/gp2-server/package.json
- apps/gp2-server/scripts/import-users.ts
- apps/gp2-server/src/controllers/project.controller.ts
- apps/gp2-server/src/data-providers/contentful/project.data-provider.ts
- apps/gp2-server/src/data-providers/contentful/utils/common.ts
- apps/gp2-server/src/data-providers/contentful/utils/index.ts
- apps/gp2-server/src/data-providers/contentful/utils/members.ts
- apps/gp2-server/src/data-providers/contentful/utils/resources.ts
- apps/gp2-server/src/data-providers/contentful/working-group.data-provider.ts
- apps/gp2-server/test/data-providers/contentful/project.data-provider.test.ts
- apps/gp2-server/test/data-providers/contentful/working-group.data-provider.test.ts
- apps/gp2-server/test/data-providers/project.data-provider.test.ts
- apps/gp2-server/test/data-providers/working-group-network.data-provider.test.ts
- apps/gp2-server/test/data-providers/working-group.data-provider.test.ts
- apps/gp2-server/test/fixtures/project.fixtures.ts
- apps/gp2-server/test/fixtures/working-group.fixtures.ts
- packages/model/src/gp2/common.ts
- packages/model/src/gp2/project.ts
- packages/model/src/gp2/working-group.ts
- packages/server-common/src/utils/csv-parse.ts
- yarn.lock
- allows for updates to user members
- refactors update project members
- fixes broken tests
- adds update members to working groups
> GP2 import scripts

- .github/actions/sls-remove/action.yml
Addresses the issue whereby when the stack has not been created yet it would report a failure
> feat: CRN-1410 Prevent SLS Remove failures

- packages/contentful/migrations/crn/users/20230706172310-change-questions-and-jobTitle-types.js
- packages/contentful/src/crn/autogenerated-gql/graphql.ts
- packages/contentful/src/crn/schema/autogenerated-schema.graphql
This PR fixes the issues migrating production user data 
- Number of characters was not supported in `questions` (action https://github.com/yldio/asap-hub/actions/runs/5187380563/jobs/9374300439#step:6:6402):
- Number of characters was not supported in `jobTitle` (action https://github.com/yldio/asap-hub/actions/runs/5187380563/jobs/9374300439#step:6:7083):
---
In order to fix it, I've changed the field questions from Array of short text to JSON and jobTitle from short text to long text.
After the change in this PR I ran the migration with prod data and we can see that all user entries were created without errors (action https://github.com/yldio/asap-hub/actions/runs/5523494198/jobs/10074498567#step:6:6161):
It is still possible to change open questions via UI. …
> CT-63 Change question and jobTitle field types in users

- .github/actions/setup-environment/action.yml
- .github/actions/sls-deployment/action.yml
- .github/actions/sls-package/action.yml
- .github/environment/Branch
- .github/environment/Development
- .github/workflows/on-remove.yml
- .github/workflows/reusable-build.yml
- .github/workflows/reusable-create-environment.yml
- apps/crn-frontend/src/config.ts
- apps/crn-server/serverless.ts
- apps/gp2-frontend/src/config.ts
- apps/gp2-server/serverless.ts
- adds gp2 algolia keys
- sync algolia for gp2
- adds algolia index settings
- fixes set-settings
- removes addition to config
- create gp2 pr index
> GP2HUB 11 create algolia indexes for pr environments

- apps/gp2-frontend/src/events/calendar/Calendars.tsx
- apps/gp2-frontend/src/events/calendar/__tests__/Calendars.test.tsx
- packages/gp2-components/src/organisms/DashboardHeader.tsx
- packages/gp2-components/src/templates/DashboardPageBody.tsx
- packages/gp2-components/src/templates/__tests__/DashboardPageBody.test.tsx
- update Calendar component & test
- update DashboardHeader/DashboardPageBody components & tests
> GP2HUB-60 update dashboard page & tests

- apps/crn-server/serverless.ts
- apps/gp2-server/serverless.ts
- packages/server-common/src/handlers/user/invite.handler.ts
- packages/server-common/test/handlers/user/invite.handler.test.ts
Temp fix to get invitation email sent out today.
> temp fix to delay handler

- apps/storybook/src/gp2-components/WorkingGroupDetailPage.stories.tsx
- packages/gp2-components/src/organisms/WorkingGroupDetailHeader.tsx
- packages/gp2-components/src/organisms/__tests__/WorkingGroupDetailHeader.test.tsx
- remove projects icon & label from WorkingGroupDetailHeader
> GP2HUB-13-remove projects from working groups header

- .github/workflows/on-demand-gp2-algolia-sync.yml
- .github/workflows/reusable-gp2-algolia-sync.yml
- apps/gp2-server/scripts/cli.ts
- apps/gp2-server/scripts/export-entity.ts
- apps/gp2-server/serverless.ts
- apps/gp2-server/src/controllers/event.controller.ts
- apps/gp2-server/src/handlers/event-bus.ts
- apps/gp2-server/src/handlers/event/algolia-index-event-handler.ts
- apps/gp2-server/test/controllers/event.controller.test.ts
- apps/gp2-server/test/controllers/project.controller.test.ts
- apps/gp2-server/test/fixtures/event.fixtures.ts
- apps/gp2-server/test/handlers/event/algolia-index-event-handler.test.ts
- apps/gp2-server/test/mocks/event.controller.mock.ts
- packages/algolia/schema/gp2/algolia-reverse-timestamp-schema.json
- packages/algolia/schema/gp2/algolia-schema.json
- packages/algolia/src/client.ts
- packages/algolia/src/gp2/types.ts
- packages/contentful/src/gp2/types/webhook.ts
- packages/fixtures/src/gp2/events.ts
- packages/model/src/gp2/calendar.ts
- packages/model/src/gp2/event.ts
- packages/model/src/gp2/webhook.ts
- sync events to gp2 algolia
- adds indexing for events
> GP2HUB 18 add search to the events list

- .github/workflows/on-demand-gp2-algolia-sync.yml
- .github/workflows/reusable-gp2-algolia-sync.yml
- apps/gp2-server/scripts/cli.ts
- apps/gp2-server/scripts/export-entity.ts
- apps/gp2-server/serverless.ts
- apps/gp2-server/src/controllers/news.controller.ts
- apps/gp2-server/src/data-providers/news.data-provider.ts
- apps/gp2-server/src/handlers/event-bus.ts
- apps/gp2-server/src/handlers/news/algolia-index-handler.ts
- apps/gp2-server/test/controllers/news.controller.test.ts
- apps/gp2-server/test/data-providers/news.data-provider.test.ts
- apps/gp2-server/test/fixtures/news.fixtures.ts
- apps/gp2-server/test/handlers/news/algolia-index-handler.test.ts
- apps/gp2-server/test/mocks/news.controller.mock.ts
- packages/algolia/src/client.ts
- packages/algolia/src/gp2/types.ts
- packages/model/src/gp2/webhook.ts
- adds index news handler
- sync news in github actions
> GP2HUB 63 add news to algolia backend

- .github/actions/setup-environment/action.yml
- .github/actions/sls-deployment/action.yml
- .github/actions/sls-package/action.yml
- .github/environment/Base
- .github/environment/Branch
- .github/environment/Development
- .github/environment/Production
- .github/workflows/reusable-test.yml
- apps/crn-server/src/config.ts
- apps/crn-server/src/middleware/feature-flag.ts
- apps/crn-server/test/app.test.ts
- packages/flags/src/index.ts
* update the default deployment config to enable feature flag
* set feature flag to be enabled in the frontend
* disregard any headers sent to the server when checking feature flag
* pass incorrect squidex url to deployments so squidex requests from backend fail
> Enable Contentful feature flag by default

- apps/crn-server/scripts/export-entity.ts
- apps/crn-server/src/handlers/research-output/algolia-index-research-output-handler.ts
- apps/crn-server/test/handlers/research-output/algolia-index-research-output-handler.test.ts
- packages/algolia/schema/crn/algolia-schema.json
JIRA: https://asaphub.atlassian.net/browse/CRN-1492
> [CRN-1492] refactor(research-output indexer): populate _tags field

- packages/react-components/src/organisms/Form.tsx
[Issue]
The error toast did not show up on the first submit of the form, only after hitting the save/ publish button the second time.
> Fixed error toast not showing on ro form

- apps/crn-server/serverless.ts
> fix: Cron job ORCID handler timeout

- apps/crn-frontend/src/tags/TagsList.tsx
- apps/storybook/src/Tag.stories.tsx
- apps/storybook/src/TagList.stories.tsx
- packages/react-components/src/atoms/NavigationLink.tsx
- packages/react-components/src/atoms/Tag.tsx
- packages/react-components/src/atoms/__tests__/Tag.test.tsx
- packages/react-components/src/molecules/TagList.tsx
- packages/react-components/src/molecules/__tests__/TagList.test.tsx
- packages/react-components/src/templates/Layout.tsx
- packages/react-components/src/templates/SharedResearchOutput.tsx
- packages/routing/src/tags.ts
https://github.com/yldio/asap-hub/assets/1936253/0358613d-e2dd-42ca-a26e-35567ebc922f
> Layout Search Button & Clickable Tags

- packages/contentful/migrations/crn/researchOutputs/20231003111043-disable-legacy-description-field.js
- packages/contentful/migrations/crn/researchOutputs/20231003112242-add-legacy-label-to-description-field.js
Disable the legacy description field for editing 
Change the name of the field to include `(legacy)`
> [CRN-1580] refactor legacy description field

- .github/environment/Base
- .github/workflows/on-push-app-extensions.yml
- packages/contentful-app-extensions/auto-populate-date-field/package.json
- packages/contentful-app-extensions/auto-populate-date-field/public/index.html
- packages/contentful-app-extensions/auto-populate-date-field/src/App.tsx
- packages/contentful-app-extensions/auto-populate-date-field/src/index.tsx
- packages/contentful-app-extensions/auto-populate-date-field/src/locations/Field.tsx
- packages/contentful-app-extensions/auto-populate-date-field/src/react-app-env.d.ts
- packages/contentful-app-extensions/auto-populate-date-field/src/test/locations/Field.test.tsx
- packages/contentful-app-extensions/auto-populate-date-field/tsconfig.json
- yarn.lock
https://asaphub.atlassian.net/browse/CRN-1518
Creates auto-populating non-editable field extension app
> [CRN-1518] feat: add auto populate app extension

- .github/actions/setup-environment/action.yml
ensure auto populated date field app extension id is set during setup environment job
> [CRN-1518] fix app deployment

- apps/gp2-frontend/src/__tests__/NotificationMessages.test.tsx
- apps/gp2-frontend/src/outputs.ts
- apps/gp2-frontend/src/outputs/OutputDetail.tsx
- apps/gp2-frontend/src/outputs/ShareOutput.tsx
- apps/gp2-frontend/src/outputs/__tests__/ShareOutput.test.tsx
- apps/gp2-frontend/src/outputs/api.ts
- apps/gp2-frontend/src/projects/CreateProjectOutput.tsx
- apps/gp2-frontend/src/projects/ProjectDetail.tsx
- apps/gp2-frontend/src/projects/__tests__/CreateProjectOutput.test.tsx
- apps/gp2-frontend/src/working-groups/CreateWorkingGroupOutput.tsx
- apps/gp2-frontend/src/working-groups/__tests__/CreateWorkingGroupOutput.test.tsx
- packages/contentful/src/gp2/autogenerated-gql/graphql.ts
- packages/contentful/src/gp2/schema/autogenerated-schema.graphql
- packages/gp2-components/src/index.ts
- packages/gp2-components/src/organisms/Form.tsx
- packages/gp2-components/src/organisms/OutputIdentifier.tsx
- packages/gp2-components/src/organisms/__tests__/Form.test.tsx
- packages/gp2-components/src/organisms/__tests__/OutputIdentifier.test.tsx
- packages/gp2-components/src/organisms/index.ts
- packages/gp2-components/src/templates/OutputForm.tsx
- packages/gp2-components/src/templates/OutputFormPage.tsx
- packages/gp2-components/src/templates/PageNotifications.tsx
- packages/gp2-components/src/templates/__tests__/OutputForm.test.tsx
- packages/gp2-components/src/templates/__tests__/OutputFormPage.test.tsx
- packages/gp2-components/src/templates/__tests__/PageNotifications.test.tsx
- packages/gp2-components/src/templates/index.ts
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/Form.tsx
- packages/react-context/src/notification-message.ts
I have added a new form component for GP2 because of how toast/ notifications are handled differently in both apps.
the inner toast from crn Form does not work for GP2 due to the way the layout styling is done in GP2
> GP2HUB-116 - output form error

- packages/contentful-app-extensions/auto-populate-date-field/package.json
bump version to trigger change detection so app is deployed to contentful
> [CRN-1518] chore: bump auto-populate-date app extension version

- packages/contentful/migrations/crn/researchOutputs/20231012113418-change-created-date-to-auto-populate-field.js
https://asaphub.atlassian.net/browse/CRN-1518
> [CRN-1518] refactor: migrate created date field to app extension

- .github/workflows/reusable-test.yml
- apps/gp2-server/scripts/export-entity.ts
- apps/gp2-server/serverless.ts
- apps/gp2-server/src/data-providers/event.data-provider.ts
- apps/gp2-server/src/data-providers/output.data-provider.ts
- apps/gp2-server/src/handlers/output/algolia-index-event-handler.ts
- apps/gp2-server/src/validation/output.validation.ts
- apps/gp2-server/test/data-providers/event.data-provider.test.ts
- apps/gp2-server/test/data-providers/output.data-provider.test.ts
- apps/gp2-server/test/handlers/output/algolia-index-event-handler.test.ts
- packages/contentful/src/gp2/autogenerated-gql/gql.ts
- packages/contentful/src/gp2/autogenerated-gql/graphql.ts
- packages/contentful/src/gp2/queries/output.queries.ts
- packages/model/src/gp2/output.ts
This implements https://asaphub.atlassian.net/browse/GP2HUB-128
Plus fixes a bug where only 10 events were indexed in Algolia.
> [GP2-128] Sync related events on the output detail page

- packages/server-common/src/handlers/webhooks/contentful.handler.ts
- instatiate contentful client earlier
- log fetch-entry errors
- add error logging for polling entry
> fix: Contentful Timeouts 

- packages/contentful/migrations/crn/discover/20231025091922-remove-training-field.js
https://asaphub.atlassian.net/browse/CRN-1529
> [CRN-1529] remove training collection field

- .github/actions/setup-environment/action.yml
https://asaphub.atlassian.net/browse/CRN-1534
When `crn-create-environment` or `gp2-create-environment` label added
algolia index = asap_hub-PR_number
api contenful env = crn-PR_number
When no `crn-create-environment` or `gp2-create-environment` label added
algolia index = asap_hub-dev
api contenful env = development
> [CRN-1534] fix PR environment configuration

- .github/actions/setup-environment/action.yml
revert the changes made in https://github.com/yldio/asap-hub/pull/3862
> revert: api & index setup

- .github/workflows/reusable-deployment.yml
You do not need a PR Auth0 secret on dev or prod builds.
> Remove variable being required

- apps/crn-frontend/src/shared-research/__tests__/api.test.ts
- apps/crn-frontend/src/shared-research/__tests__/export.test.ts
- apps/crn-frontend/src/shared-research/api.ts
- apps/crn-frontend/src/shared-research/export.ts
- apps/crn-server/src/data-providers/contentful/research-output.data-provider.ts
- apps/crn-server/test/data-providers/contentful/research-output.data-provider.test.ts
- apps/crn-server/test/fixtures/research-output.fixtures.ts
- apps/storybook/src/SharedResearchCard.stories.tsx
- packages/algolia/schema/crn/algolia-reverse-timestamp-schema.json
- packages/algolia/schema/crn/algolia-schema.json
- packages/fixtures/src/research-outputs.ts
- packages/model/src/research-output.ts
- packages/react-components/src/organisms/SharedResearchCard.tsx
- packages/react-components/src/templates/ResearchOutputsSearch.tsx
> CRN-1398 Filter research output by source

- .github/workflows/reusable-gp2-algolia-sync.yml
> fix typo in entity-type

- apps/crn-server/serverless.ts
- apps/crn-server/src/config.ts
- apps/crn-server/src/handlers/webhooks/gcal-webhook-events-updated-process.ts
- apps/crn-server/src/handlers/webhooks/gcal-webhook-events-updated.ts
- apps/gp2-server/serverless.ts
- apps/gp2-server/src/config.ts
- apps/gp2-server/src/handlers/webhooks/events-updated-process.ts
- apps/gp2-server/src/handlers/webhooks/events-updated.ts
- packages/contentful/src/utils/poll-content.ts
- packages/server-common/src/handlers/webhooks/events-updated-process.handler.ts
- packages/server-common/src/handlers/webhooks/events-updated.handler.ts
- packages/server-common/src/handlers/webhooks/index.ts
- packages/server-common/test/fixtures/calendar.fixtures.ts
- packages/server-common/test/fixtures/google-events.fixtures.ts
- packages/server-common/test/handlers/calendar/resubscribe-calendars.test.ts
- packages/server-common/test/handlers/webhooks/contentful-poller.handler.test.ts
- packages/server-common/test/handlers/webhooks/events-updated-process.handler.test.ts
- packages/server-common/test/handlers/webhooks/events-updated.handler.test.ts
- divides calendar handlers into 2
- update project handlers for calendar
- adds event handlers to serverless
> GP2HUB 142 reject unexpected sync notifications and reduce concurrency

- .github/workflows/on-demand-crn-algolia-sync.yml
- .github/workflows/reusable-crn-algolia-sync.yml
- apps/crn-frontend/src/network/working-groups/__tests__/WorkingGroupProfile.test.tsx
- apps/crn-frontend/src/tags/Routes.tsx
- apps/crn-frontend/src/tags/__tests__/Routes.test.tsx
- apps/crn-frontend/src/tags/api.ts
- apps/crn-server/scripts/cli.ts
- apps/crn-server/scripts/export-entity.ts
- apps/crn-server/serverless.ts
- apps/crn-server/src/dependencies/team.dependencies.ts
- apps/crn-server/src/handlers/teams/algolia-index-team-handler.ts
- apps/crn-server/src/handlers/teams/algolia-index-team-users-handler.ts
- apps/crn-server/test/dependencies/team.dependencies.test.ts
- apps/crn-server/test/handlers/helper.test.ts
- apps/crn-server/test/handlers/teams/algolia-index-team-users-handler.test.ts
- apps/crn-server/test/integration/reminders.integration-test.ts
- packages/algolia/src/client.ts
- packages/algolia/src/crn/types.ts
- packages/model/src/tag.ts
- packages/react-components/src/templates/TagsPageBody.tsx
- packages/react-components/src/templates/__tests__/TagsPageBody.test.tsx
- packages/server-common/src/handlers/event-bus.ts
> ASAP-39 Add teams to tag search

- packages/contentful/migrations/crn/news/20231115124415-add-tags-field.js
ref: https://asaphub.atlassian.net/browse/ASAP-42
> [ASAP-42] - add tags field to news

- packages/react-components/src/organisms/OutputVersions.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-238
> [ASAP-238] - fix version card alignment

- apps/storybook/src/NetworkWorkingGroups.stories.tsx
- apps/storybook/src/WorkingGroupCard.stories.tsx
- apps/storybook/src/WorkingGroupPage.stories.tsx
- packages/react-components/src/organisms/WorkingGroupCard.tsx
- packages/react-components/src/organisms/__tests__/WorkingGroupCard.test.tsx
- packages/react-components/src/templates/WorkingGroupAbout.tsx
- packages/react-components/src/templates/__tests__/NetworkWorkingGroups.test.tsx
- packages/react-components/src/templates/__tests__/WorkingGroupAbout.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-147
> [ASAP-147] - add tags to working group page

- apps/crn-server/scripts/export-entity.ts
- packages/algolia/src/client.ts
- packages/model/src/tag.ts
- packages/react-components/src/templates/TagsPageBody.tsx
- packages/react-components/src/templates/__tests__/TagsPageBody.test.tsx
https://asaphub.atlassian.net/browse/ASAP-247
The conditional logic we use to determine which card to render will not work as we reduce the fields we index in algolia
https://asaphub.atlassian.net/browse/ASAP-62
> [ASAP-247] refactor(TagsPageBody): card rendering

- apps/crn-frontend/src/AuthenticatedApp.tsx
- packages/frontend-utils/src/index.ts
- packages/frontend-utils/src/structure/Frame.tsx
- packages/frontend-utils/src/structure/__tests__/Frame.test.tsx
- packages/frontend-utils/src/structure/index.ts
- packages/react-components/src/index.ts
- packages/react-components/src/templates/LoadingLayout.tsx
- packages/react-components/src/templates/__tests__/LoadingLayout.test.tsx
- packages/react-components/src/templates/index.ts
ref: https://asaphub.atlassian.net/browse/ASAP-175
> [ASAP-175] - add skeleton loading state (header)

- apps/crn-frontend/src/dashboard/__tests__/api.test.tsx
- apps/crn-frontend/src/dashboard/api.ts
- apps/gp2-frontend/src/dashboard/Body.tsx
- apps/gp2-frontend/src/dashboard/__tests__/Dashboard.test.tsx
- apps/gp2-frontend/src/dashboard/__tests__/api.test.tsx
- apps/gp2-frontend/src/dashboard/api.tsx
- apps/gp2-frontend/src/dashboard/state.ts
- apps/gp2-server/src/app.ts
- apps/gp2-server/src/routes/reminder.route.ts
- apps/gp2-server/src/validation/reminder.validation.ts
- apps/gp2-server/test/routes/reminder.route.test.ts
- apps/storybook/src/gp2-components/DashboardPageBody.stories.tsx
- packages/frontend-utils/src/api-util/__test__/api-util.test.tsx
- packages/frontend-utils/src/api-util/api-util.ts
- packages/gp2-components/src/templates/DashboardPageBody.tsx
- packages/gp2-components/src/templates/__tests__/DashboardPageBody.test.tsx
- packages/react-context/src/__tests__/auth.test.tsx
- packages/react-context/src/auth.ts
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-252
---
Desktop - non-admin           |  Mobile - admin
> ASAP-252|GP2 Add reminders component

- apps/crn-server/test/data-providers/contentful/users.data-provider.test.ts
- apps/crn-server/test/fixtures/users.fixtures.ts
- apps/gp2-server/test/data-providers/user.data-provider.test.ts
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-72
> ASAP-72 Remove graphql mock server tests for user data provider

- packages/flags/src/index.ts
- packages/gp2-components/src/templates/OutputForm.tsx
- packages/gp2-components/src/templates/__tests__/OutputForm.test.tsx
- adds the modal
- updates the notification message after publishing
> feat: ASAP-15 Publish new version modal for GP2

- apps/storybook/src/LabeledDropdown.stories.tsx
- apps/storybook/src/LabeledTextArea.stories.tsx
- apps/storybook/src/LabeledTextField.stories.tsx
- packages/react-components/src/atoms/TextArea.tsx
- packages/react-components/src/atoms/TextField.tsx
- packages/react-components/src/select.ts
Jira Ticket: https://asaphub.atlassian.net/browse/ASAP-179
--- 
Before             |  After
Before             |  After
> ASAP-179 Placeholder text on error form fields light red instead of gray

- .github/workflows/on-push-app-extensions.yml
- .github/workflows/on-remove.yml
- .github/workflows/reusable-crn-algolia-sync.yml
- .github/workflows/reusable-gp2-algolia-sync.yml
This PR tries to fix the issue in algolia-sync jobs https://github.com/yldio/asap-hub/actions/runs/7530236316/job/20496826686#step:19:15
And this one in contentful app action https://github.com/yldio/asap-hub/actions/runs/7530236274/job/20496289667
> fix: prettier missing in ci

- packages/algolia/schema/gp2/algolia-reverse-timestamp-schema.json
- packages/algolia/schema/gp2/algolia-schema.json
- packages/gp2-components/src/organisms/FilterSearchExport.tsx
ref: https://asaphub.atlassian.net/jira/software/c/projects/ASAP/boards/13?selectedIssue=ASAP-313
> [ASAP-313] - update gp2 algolia schema

- packages/gp2-components/src/templates/DashboardPageBody.tsx
- packages/gp2-components/src/templates/__tests__/DashboardPageBody.test.tsx
- packages/react-components/src/templates/DashboardPageBody.tsx
- packages/react-components/src/templates/__tests__/DashboardPageBody.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-320
---
> Update announcements description

- packages/react-components/src/organisms/RelatedTutorialsCard.tsx
- packages/react-components/src/organisms/__tests__/RelatedTutorialsCard.test.tsx
- packages/react-components/src/templates/__tests__/TutorialsDetailsPage.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-136
> ASAP-136 Update related tutorials copy

- .github/workflows/reusable-test.yml
- turbo.json
- adds a topological dependency so that tests are run on each dependant package and app
* using topo in turborepo: https://turbo.build/repo/docs/core-concepts/monorepos/task-dependencies#dependencies-outside-of-a-task
> fix: Turbo dependency issue 

- packages/react-components/src/organisms/RelatedEventsCard.tsx
- packages/react-components/src/organisms/__tests__/RelatedEventsCard.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-137
---
After the changes in this PR
> ASAP-137 Update related events description

- apps/crn-server/serverless.ts
- apps/crn-server/src/handlers/teams/sync-active-campaign-team-member-status.ts
- apps/crn-server/src/handlers/user/sync-active-campaign-contact.ts
- apps/crn-server/test/handlers/teams/sync-active-campaign-team-member-status.test.ts
- apps/crn-server/test/handlers/user/sync-active-campaign-contact.test.ts
- apps/gp2-server/src/handlers/user/sync-active-campaign-contact.ts
- apps/gp2-server/test/handlers/user/sync-active-campaign-contact.test.ts
- packages/server-common/src/handlers/user/sync-active-campaign-contact-factory.ts
- packages/server-common/src/utils/active-campaign.ts
- packages/server-common/test/handlers/user/sync-active-campaign-contact-factory.test.ts
- packages/server-common/test/mocks/active-campaign.mock.ts
- packages/server-common/test/utils/active-campaign.test.ts
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-328
> ASAP-328 Adjustments to ActiveCampaign push data

- .github/workflows/reusable-crn-algolia-sync.yml
- apps/crn-frontend/src/network/__tests__/Network.test.tsx
- apps/crn-frontend/src/network/working-groups/__tests__/WorkingGroupList.test.tsx
- apps/crn-frontend/src/network/working-groups/__tests__/api.test.ts
- apps/crn-frontend/src/network/working-groups/api.ts
- apps/crn-frontend/src/network/working-groups/state.ts
- packages/algolia/schema/crn/algolia-reverse-timestamp-schema.json
- packages/algolia/schema/crn/algolia-schema.json
Jira: https://asaphub.atlassian.net/browse/ASAP-314
---
> ASAP-314 Tags searchable in WG list view

- apps/crn-frontend/package.json
- apps/gp2-frontend/package.json
- yarn.lock
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-203
> ASAP-203 Remove @types/node from frontend

- packages/contentful/src/utils/poll-content.ts
Please read slack thread for context: https://yld.slack.com/archives/C0258KQR64V/p1709553284312169?thread_ts=1709538400.569879&cid=C0258KQR64V
> Adding more information to pool logs

- packages/react-components/src/organisms/ResultList.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-310
---
> ASAP-310 Fix alignment in export CSV button

- packages/react-components/src/molecules/CtaCard.tsx
- packages/react-components/src/templates/UserProfileResearch.tsx
- packages/react-components/src/templates/__tests__/UserProfileResearch.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-291
---
> ASAP-291 Update user profile footer

- packages/react-components/src/organisms/HelpSection.tsx
- packages/react-components/src/templates/__tests__/UserProfileResearch.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-299
---
> ASAP-299 Update ASAP footer

- apps/crn-frontend/src/network/users/__tests__/Research.test.tsx
> increase timeout on expertise & resources

- packages/react-components/src/templates/ContactInfoModal.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-303?focusedCommentId=11583
This is a small update to the 'Social Networks' headline on the ContactInfoModal, following João's comments linked above.
> update socials headline styling

- packages/react-components/src/templates/InterestGroupProfileAbout.tsx
- packages/react-components/src/templates/__tests__/InterestGroupProfileAbout.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-293
---
Before / After
> ASAP-293 Hide CTA footer for inactive interest groups

- apps/crn-frontend/src/events/Event.tsx
- apps/storybook/src/EventPage.stories.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/templates/EventPage.tsx
- packages/react-components/src/templates/__tests__/EventPage.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-296
---
This PR adds the footer designed in figma (https://www.figma.com/file/qM73Om8hMDi8o15nj09ECw/CRN-%2F-Designs-%2F-Other-Pages?type=design&node-id=13303%3A63762&mode=design&t=dKW7hVZDePBYJbDr-1) in upcoming events
> ASAP-296 Add footer to upcoming events

- package.json
- packages/gp2-components/src/organisms/ConfirmAndSaveOutput.tsx
- **add turbo dir to yarn clean**
- **fix the path for gp2 message template**
> fix: GP2 Message template - import path issue

- packages/react-components/src/templates/EventPage.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-133
> ASAP-133 - change card order on EventPage

- packages/react-components/src/organisms/RelatedResearchCard.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-132
> [ASAP-132] - display row dividers on crn

- apps/storybook/src/TagList.stories.tsx
- packages/react-components/src/molecules/EventInfo.tsx
- packages/react-components/src/molecules/EventNumberOfSpeakers.tsx
- packages/react-components/src/molecules/EventOwner.tsx
- packages/react-components/src/molecules/EventTeams.tsx
- packages/react-components/src/molecules/EventTime.tsx
- packages/react-components/src/molecules/TagList.tsx
- packages/react-components/src/molecules/UserProfilePersonalText.tsx
- packages/react-components/src/molecules/__tests__/UserProfilePersonalText.test.tsx
- packages/react-components/src/organisms/EntityCard.tsx
- packages/react-components/src/organisms/InterestGroupCard.tsx
- packages/react-components/src/organisms/SharedResearchCard.tsx
- packages/react-components/src/organisms/TeamCard.tsx
- packages/react-components/src/organisms/WorkingGroupCard.tsx
- packages/react-components/src/organisms/__tests__/EntityCard.test.tsx
- packages/react-components/src/organisms/index.ts
The idea of this PR is fix the margin in the `TagList` component.  I believe it was added a marginBottom of 12 so when there are multiple lines of tags, there are space between them:
But even when there isn't multiple lines of tags, the margin bottom of 12 is still there
I think in general it's bad to add margins to a component since it can be used in several places and in each place it could need a margin or not.
So this PR changes this in the `TagList` so it only adds a margin bottom of 12 when there are multiple lines and also adjusts some spacing in other components due to this change.
> (refactor): adjustments to components margins/paddings

- apps/crn-frontend/src/analytics/__tests__/Routes.test.tsx
- apps/crn-frontend/src/analytics/productivity/Productivity.tsx
- apps/crn-frontend/src/analytics/productivity/TeamProductivity.tsx
- apps/crn-frontend/src/analytics/productivity/UserProductivity.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/Productivity.test.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/TeamProductivity.test.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/UserProductivity.test.tsx
- apps/crn-frontend/src/analytics/productivity/__tests__/api.test.tsx
- apps/crn-frontend/src/analytics/productivity/api.ts
- apps/crn-frontend/src/analytics/productivity/state.ts
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/TeamProductivityTable.tsx
- packages/react-components/src/organisms/UserProductivityTable.tsx
- packages/react-components/src/organisms/__tests__/TeamProductivityTable.test.tsx
- packages/react-components/src/organisms/__tests__/UserProductivityTable.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/AnalyticsProductivityPageBody.tsx
- packages/react-components/src/templates/__tests__/AnalyticsProductivityPageBody.test.tsx
This PR integrate resource and data sharing BE and FE
---
For reference:
- FE PR: https://github.com/yldio/asap-hub/pull/4223
- BE PR: https://github.com/yldio/asap-hub/pull/4228
> ASAP-370 Resource and Data Sharing BE and FE integration

- apps/gp2-frontend/src/projects/__tests__/CreateProjectOutput.test.tsx
- apps/gp2-frontend/src/working-groups/__tests__/CreateWorkingGroupOutput.test.tsx
- apps/gp2-server/src/controllers/output.controller.ts
- apps/gp2-server/src/validation/output.validation.ts
- apps/gp2-server/test/routes/output.route.test.ts
- packages/contentful/migrations/gp2/outputs/20240412131641-add-short-description-field.js
- packages/contentful/migrations/gp2/outputs/20240412131641-add-short-text-field.js
- packages/fixtures/src/gp2/outputs.ts
- packages/gp2-components/src/templates/OutputForm.tsx
- packages/gp2-components/src/templates/__tests__/OutputForm.test.tsx
- packages/model/src/gp2/output.ts
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-407
--- 
**Notes:**
- It's not necessary to add short description to the output detail view
- The link mentioned in the third requirement was removed since we don't have the correct link yet.
(source: https://yld.slack.com/archives/CV4UY4411/p1712937377468709)
> ASAP-407 (GP2) Add short description field

- .github/workflows/on-demand-gp2-algolia-sync.yml
- .github/workflows/reusable-gp2-algolia-sync.yml
- apps/gp2-frontend/src/__fixtures__/algolia.ts
- apps/gp2-frontend/src/tags/ResultList.tsx
- apps/gp2-frontend/src/tags/__tests__/ResultList.test.tsx
- apps/gp2-frontend/src/tags/__tests__/api.test.tsx
- apps/gp2-frontend/src/tags/api.ts
- apps/gp2-server/scripts/cli.ts
- apps/gp2-server/scripts/export-entity.ts
- apps/gp2-server/serverless.ts
- apps/gp2-server/src/handlers/working-group/algolia-index-handler.ts
- apps/gp2-server/test/handlers/working-group/algolia-index-handler.test.ts
- packages/algolia/src/client.ts
- packages/algolia/src/gp2/types.ts
- packages/fixtures/src/gp2/working-groups.ts
- packages/gp2-components/src/templates/TagSearchPageList.tsx
- packages/model/src/gp2/entity.ts
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-389
---
> ASAP-389 (GP2) Add working groups to tag search

- .github/actions/setup-environment/action.yml
- .github/actions/sls-deployment/action.yml
- .github/actions/sls-package/action.yml
- .github/actions/sls-remove/action.yml
- .github/environment/Branch
- .github/environment/Development
- .github/environment/Production
- .github/workflows/on-remove.yml
- .github/workflows/reusable-build.yml
- .github/workflows/reusable-deployment.yml
- apps/gp2-server/serverless.ts
- **add sentry dsn to CI params**
- **add DSN to serverless for gp2**
> feat: ASAP-418 Add Sentry monitoring to Public API

- apps/crn-frontend/src/analytics/collaboration/Collaboration.tsx
- apps/crn-frontend/src/analytics/collaboration/TeamCollaboration.tsx
- apps/crn-frontend/src/analytics/collaboration/UserCollaboration.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/Collaboration.test.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/TeamCollaboration.test.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/UserCollaboration.test.tsx
- apps/crn-frontend/src/analytics/collaboration/state.ts
- apps/crn-server/src/data-providers/contentful/analytics.data-provider.ts
- apps/crn-server/src/utils/analytics/collaboration.ts
- apps/crn-server/test/utils/analytics/collaboration.test.ts
- packages/react-components/src/templates/AnalyticsCollaborationPageBody.tsx
- packages/react-components/src/templates/__tests__/AnalyticsCollaborationPageBody.test.tsx
This PR adds the time selection on Collaboration analytics page.
---
Jira: https://asaphub.atlassian.net/browse/ASAP-425
Hub: https://4291.hub.asap.science/analytics/collaboration/team
Feature Flag: `document.cookie = 'ASAP_DISPLAY_ANALYTICS_COLLABORATION=true'`
Figma: https://www.figma.com/design/qM73Om8hMDi8o15nj09ECw/CRN-%2F-Designs-%2F-Other-Pages?node-id=24032-14985&t=XQ2M3HaH0GlCq0MY-4
---
Last 30 Days          |  Since Hub Launch
Last 30 Days          |  Since Hub Launch
> ASAP-425 Collaboration timeframe selection

- apps/gp2-server/src/controllers/user.controller.ts
- apps/gp2-server/src/data-providers/user.data-provider.ts
- apps/gp2-server/src/routes/public/output.route.ts
- apps/gp2-server/src/routes/public/user.route.ts
- apps/gp2-server/src/routes/public/working-group.route.ts
- apps/gp2-server/test/fixtures/output.fixtures.ts
- apps/gp2-server/test/fixtures/user.fixtures.ts
- apps/gp2-server/test/fixtures/working-group.fixtures.ts
- apps/gp2-server/test/routes/public/output.route.test.ts
- apps/gp2-server/test/routes/public/user.route.test.ts
- packages/fixtures/src/gp2/outputs.ts
- packages/fixtures/src/gp2/users.ts
- packages/model/src/gp2/output.ts
- packages/model/src/gp2/user.ts
- packages/model/src/gp2/working-group.ts
- packages/validation/src/fixtures/gp2/user.fixtures.ts
- **add system publish version to users**
- **add title and institution to users**
- **add last modified date to users**
- **add last modified date to wgs**
- **add last modified date to outputs**
- **add final publish date to outputs**
- **add preprint publish date to outputs**
> feat: ASAP-475 Add missing fields to GP2 Public Api

- apps/crn-frontend/src/network/teams/__tests__/TeamManuscript.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/api.test.ts
- apps/crn-frontend/src/network/teams/state.ts
- apps/crn-server/src/data-providers/contentful/manuscript.data-provider.ts
- packages/contentful/migrations/crn/manuscripts/20240606090622-update-manuscript-version-fields.js
- packages/contentful/src/crn/autogenerated-gql/gql.ts
- packages/contentful/src/crn/autogenerated-gql/graphql.ts
- packages/contentful/src/crn/queries/manuscript.queries.ts
- packages/contentful/src/crn/schema/autogenerated-schema.graphql
- packages/fixtures/src/manuscripts.ts
- packages/model/src/manuscript.ts
- packages/react-components/src/organisms/ManuscriptCard.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptCard.test.tsx
- packages/react-components/src/templates/ManuscriptForm.tsx
- packages/react-components/src/templates/__tests__/ManuscriptForm.test.tsx
- packages/react-components/src/templates/__tests__/TeamProfileWorkspace.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-498
- I've updated the lifecycle options on Manuscript versions to match what we have in the spreadsheet with rules (attached to the ticket)
> [ASAP-498] - update manuscript version fields

- apps/crn-frontend/src/network/teams/EligibilityReasonProvider.tsx
- apps/crn-frontend/src/network/teams/TeamManuscript.tsx
- apps/crn-frontend/src/network/teams/TeamProfile.tsx
- apps/crn-frontend/src/network/teams/Workspace.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamManuscript.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/api.test.ts
- apps/crn-frontend/src/network/teams/useEligibilityReason.tsx
- apps/crn-server/test/data-providers/contentful/manuscript.data-provider.test.ts
- apps/crn-server/test/fixtures/manuscript.fixtures.ts
- apps/storybook/src/TeamProfileWorkspace.stories.tsx
- packages/contentful/migrations/crn/manuscripts/20240711172003-add-eligibility-field.js
- packages/model/src/manuscript.ts
- packages/react-components/src/atoms/Checkbox.tsx
- packages/react-components/src/atoms/Label.tsx
- packages/react-components/src/molecules/LabeledCheckbox.tsx
- packages/react-components/src/molecules/LabeledCheckboxGroup.tsx
- packages/react-components/src/molecules/__tests__/LabeledCheckboxGroup.test.tsx
- packages/react-components/src/molecules/index.ts
- packages/react-components/src/organisms/CheckboxGroup.tsx
- packages/react-components/src/organisms/EligibilityModal.tsx
- packages/react-components/src/organisms/__tests__/EligibilityModal.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/ManuscriptForm.tsx
- packages/react-components/src/templates/TeamProfileWorkspace.tsx
- packages/react-components/src/templates/__tests__/ManuscriptForm.test.tsx
- packages/react-components/src/templates/__tests__/TeamProfileWorkspace.test.tsx
JIRA ticket: https://asaphub.atlassian.net/browse/ASAP-497
> ASAP-497 Manuscript Eligibility

- apps/crn-frontend/src/analytics/collaboration/Collaboration.tsx
- apps/crn-frontend/src/analytics/collaboration/TeamCollaboration.tsx
- apps/crn-frontend/src/analytics/collaboration/UserCollaboration.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/Collaboration.test.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/TeamCollaboration.test.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/UserCollaboration.test.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/api.test.tsx
- apps/crn-server/scripts/export-analytics.ts
- packages/react-components/src/molecules/PageControls.tsx
- packages/react-components/src/molecules/__tests__/AnalyticsControls.test.tsx
- packages/react-components/src/templates/AnalyticsCollaborationPageBody.tsx
- packages/react-components/src/templates/__tests__/AnalyticsCollaborationPageBody.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-517
> [ASAP-517] - collaboration search feature

- apps/crn-frontend/src/analytics/__tests__/Routes.test.tsx
- apps/crn-frontend/src/analytics/collaboration/Collaboration.tsx
- apps/crn-frontend/src/analytics/collaboration/TeamCollaboration.tsx
- apps/crn-frontend/src/analytics/collaboration/UserCollaboration.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/Collaboration.test.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/TeamCollaboration.test.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/UserCollaboration.test.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/api.test.tsx
- apps/crn-frontend/src/analytics/collaboration/__tests__/export.test.ts
- apps/crn-frontend/src/analytics/collaboration/export.ts
- apps/crn-frontend/src/analytics/leadership/Leadership.tsx
- apps/crn-frontend/src/analytics/leadership/__tests__/export.test.ts
- apps/crn-frontend/src/analytics/leadership/export.ts
- apps/crn-frontend/src/analytics/productivity/Productivity.tsx
- apps/crn-frontend/src/analytics/utils/export.ts
- apps/crn-server/src/utils/analytics/collaboration.ts
- apps/crn-server/test/fixtures/analytics.fixtures.ts
- packages/contentful/src/crn/autogenerated-gql/graphql.ts
- packages/contentful/src/crn/schema/autogenerated-schema.graphql
- packages/model/src/analytics.ts
- packages/react-components/src/templates/AnalyticsCollaborationPageBody.tsx
- packages/react-components/src/templates/AnalyticsProductivityPageBody.tsx
- packages/react-components/src/templates/__tests__/AnalyticsCollaborationPageBody.test.tsx
JIRA ticket: https://asaphub.atlassian.net/browse/ASAP-426
---
Note: the function `algoliaResultsToStream` that was inside `/analytics/leadership/export.ts` was moved to `/analytics/export.ts`.
> ASAP-426 (Collaboration) Add CSV export

- .github/actions/algolia-import-metric/action.yml
- .github/workflows/on-demand-crn-analytics-algolia-sync.yml
- apps/crn-frontend/src/analytics/engagement/__tests__/Engagement.test.tsx
- apps/crn-frontend/src/analytics/engagement/__tests__/api.test.tsx
- apps/crn-frontend/src/analytics/engagement/api.ts
- apps/crn-frontend/src/analytics/engagement/state.ts
- apps/crn-server/scripts/cli.ts
- apps/crn-server/scripts/export-analytics.ts
- packages/algolia/src/analytics/types.ts
- packages/algolia/src/client.ts
- packages/model/src/analytics.ts
JIRA: https://asaphub.atlassian.net/browse/ASAP-508
> ASAP-508 Engament data in Algolia

- apps/gp2-server/src/routes/public/output.route.ts
- apps/gp2-server/src/routes/public/user.route.ts
- apps/gp2-server/src/routes/public/working-group.route.ts
- apps/gp2-server/test/fixtures/output.fixtures.ts
- apps/gp2-server/test/fixtures/user.fixtures.ts
- apps/gp2-server/test/fixtures/working-group.fixtures.ts
- packages/model/src/gp2/output.ts
- packages/model/src/gp2/user.ts
- packages/model/src/gp2/working-group.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-617
> add new fields to GP2 public API

- packages/contentful-app-extensions/user-positions/src/locations/Field.tsx
- packages/contentful-app-extensions/user-positions/src/test/locations/Field.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-623
> update field when position is removed

- apps/crn-frontend/src/analytics/productivity/Productivity.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-611
> [ASAP-611] - add outputType filter to team productivity export

- apps/crn-server/src/controllers/research-output.controller.ts
- apps/crn-server/test/controllers/research-output.controller.test.ts
- apps/gp2-server/src/controllers/output.controller.ts
- apps/gp2-server/test/controllers/output.controller.test.ts
- packages/contentful/migrations/crn/researchOutputs/20240808084217-add-identifier-fields-to-versions.js
- packages/contentful/migrations/gp2/outputs/20240808084847-add-identifier-fields-to-versions.js
- packages/model/src/gp2/output.ts
- packages/model/src/research-output.ts
JIRA ticket: https://asaphub.atlassian.net/browse/ASAP-593
> ASAP-593 Adding Identifiers to Output Versions

- apps/crn-server/serverless.ts
- apps/crn-server/src/controllers/research-output.controller.ts
- apps/crn-server/src/data-providers/contentful/research-output.data-provider.ts
- apps/crn-server/src/data-providers/types/research-output.data-provider.types.ts
- apps/crn-server/src/handlers/public-api-handler.ts
- apps/crn-server/src/publicApp.ts
- apps/crn-server/src/routes/public/research-output.route.ts
- apps/crn-server/src/server.ts
- apps/crn-server/test/data-providers/contentful/research-output.data-provider.test.ts
- apps/crn-server/test/fixtures/research-output.fixtures.ts
- apps/crn-server/test/routes/public/public-app.route.test.ts
- apps/crn-server/test/routes/public/research-output.route.test.ts
- packages/model/src/research-output.ts
JIRA ticket: https://asaphub.atlassian.net/browse/ASAP-627
---
It's possible to test it here: https://api-4351.hub.asap.science/public/research-outputs
> ASAP-627 CRN Public API - Research Output

- apps/crn-frontend/src/analytics/engagement/Engagement.tsx
- apps/crn-frontend/src/analytics/engagement/__tests__/Engagement.test.tsx
- apps/crn-frontend/src/analytics/engagement/__tests__/api.test.tsx
- apps/crn-frontend/src/analytics/engagement/api.ts
- apps/crn-server/scripts/export-analytics.ts
- packages/react-components/src/templates/AnalyticsEngagementPageBody.tsx
- packages/react-components/src/templates/__tests__/AnalyticsEngagementPageBody.test.tsx
JIRA ticket: https://asaphub.atlassian.net/browse/ASAP-506
---
Example: https://4352.hub.asap.science/analytics/engagement?tag=Wood&tag=Camel&tag=Alessi
> ASAP-506 Engagement Search Feature

- apps/gp2-server/src/routes/public/working-group.route.ts
- apps/gp2-server/test/fixtures/working-group.fixtures.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-639
> [GP2] add milestone title and link to working group endpoint

- apps/crn-frontend/src/analytics/engagement/Engagement.tsx
- apps/crn-frontend/src/analytics/engagement/__tests__/Engagement.test.tsx
- apps/crn-frontend/src/analytics/engagement/__tests__/export.test.ts
- apps/crn-frontend/src/analytics/engagement/export.ts
- packages/react-components/src/templates/AnalyticsEngagementPageBody.tsx
- packages/react-components/src/templates/__tests__/AnalyticsEngagementPageBody.test.tsx
JIRA ticket: https://asaphub.atlassian.net/browse/ASAP-507
---
> ASAP-507 Engagement CSV Export

- apps/asap-cli/src/cli.ts
- apps/asap-cli/src/scripts/algolia/performance/collaboration.ts
- apps/asap-cli/src/scripts/algolia/performance/productivity.ts
- apps/asap-cli/src/scripts/algolia/process-performance.ts
- apps/asap-cli/src/scripts/algolia/tests/process-performance.test.ts
- packages/react-components/src/molecules/CaptionItem.tsx
- packages/react-components/src/molecules/__tests__/CaptionItem.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-609
I tried a few scenarios on this sheet https://docs.google.com/spreadsheets/d/1Z-zWlTwiJeiftr5HhKqpAmRfX_wAQoCzdLWdj7tTtNk/edit?gid=868813298#gid=868813298 to come up with a 'formula'. 
I set duplicated values to -1 to make it easier on the frontend (i.e if the range is negative then display ---
> update standard deviation to quartiles

- apps/crn-server/src/validation/research-output.validation.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-654
> [CRN] fix short description server validation rules

- apps/asap-cli/src/cli.ts
- apps/crn-frontend/src/analytics/engagement/Engagement.tsx
- apps/crn-frontend/src/analytics/engagement/__tests__/Engagement.test.tsx
- apps/crn-frontend/src/analytics/engagement/__tests__/api.test.tsx
- apps/crn-frontend/src/analytics/engagement/api.ts
- apps/crn-frontend/src/analytics/engagement/state.ts
- apps/crn-server/scripts/export-analytics.ts
- packages/react-components/src/templates/AnalyticsEngagementPageBody.tsx
JIRA: https://asaphub.atlassian.net/browse/ASAP-513
---
> ASAP-513 Engagement Custom Timeframe

- apps/crn-frontend/src/shared-research/export.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-667
> fix description value in team's outputs CSV export

- packages/react-components/src/molecules/CaptionItem.tsx
- packages/react-components/src/organisms/CaptionCard.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-651
> [ASAP-651] - fix alignment on performance card

- packages/react-components/src/molecules/AnalyticsControls.tsx
- packages/react-components/src/molecules/__tests__/AnalyticsControls.test.tsx
- packages/react-components/src/templates/AnalyticsCollaborationPageBody.tsx
- packages/react-components/src/templates/__tests__/AnalyticsCollaborationPageBody.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-530
The ticket says 'The data will be refreshed everyday at 7:00 am EDT (New York time zone)'. I took a look at the workflow file and it's 6am UTC so that's what I used.
> [ASAP-530] - display analytics last updated date

- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- packages/model/src/manuscript.ts
- packages/react-components/src/templates/TeamProfileWorkspace.tsx
- packages/react-components/src/templates/__tests__/TeamProfileWorkspace.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-618
> update copy related to manuscripts

- .github/actions/setup-environment/action.yml
- .github/workflows/on-push-branch.yml
- .github/workflows/on-remove.yml
- .github/workflows/reusable-create-environment.yml
- README.md
Ticket: https://asaphub.atlassian.net/browse/ASAP-681
> Add '*-create-algolia-environment' label to create dedicated Algolia env

- .github/actions/setup-environment/action.yml
- .github/workflows/on-remove.yml
This PR adds the yellow row from the table below:
> (fix): env creation based on github labels

- .github/actions/setup-environment/action.yml
Thread for context: https://yld.slack.com/archives/C07D2F5DGRM/p1728035206721389
> (fix): add a false fallback to create contentful/algolia env variables

- packages/contentful/migrations/crn/manuscripts/20241003122628-add-status.js
Ticket: https://asaphub.atlassian.net/browse/ASAP-543
> add manuscript status migration

- apps/crn-server/test/fixtures/manuscript.fixtures.ts
- apps/crn-server/test/fixtures/teams.fixtures.ts
- apps/crn-server/test/routes/manuscript.route.test.ts
- packages/fixtures/src/manuscripts.ts
- packages/model/src/manuscript.ts
- packages/react-components/src/organisms/__tests__/ManuscriptCard.test.tsx
- packages/react-components/src/templates/ManuscriptForm.tsx
- packages/react-components/src/templates/__tests__/ManuscriptForm.test.tsx
- packages/react-components/src/templates/__tests__/TeamProfileWorkspace.test.tsx
JIRA ticket: https://asaphub.atlassian.net/browse/ASAP-692
---
Frontend only, the CMS part will be done in another PR.
> ASAP-692 Changes in Manuscript Lifecycles (Frontend only)

- apps/crn-frontend/src/network/teams/Workspace.tsx
- apps/crn-frontend/src/network/teams/__tests__/Workspace.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/api.test.ts
- apps/crn-frontend/src/network/teams/api.ts
- apps/crn-frontend/src/network/teams/state.ts
- apps/crn-server/src/controllers/manuscript.controller.ts
- apps/crn-server/src/data-providers/contentful/manuscript.data-provider.ts
- apps/crn-server/src/data-providers/types/manuscript.data-provider.types.ts
- apps/crn-server/src/routes/manuscript.route.ts
- apps/crn-server/src/validation/manuscript.validation.ts
- apps/crn-server/test/controllers/manuscript.controller.test.ts
- apps/crn-server/test/data-providers/contentful/manuscript.data-provider.test.ts
- apps/crn-server/test/fixtures/manuscript.fixtures.ts
- apps/crn-server/test/mocks/manuscript.controller.mock.ts
- apps/crn-server/test/routes/manuscript.route.test.ts
- apps/storybook/src/TeamProfileWorkspace.stories.tsx
- packages/model/src/manuscript.ts
- packages/react-components/src/organisms/ConfirmStatusChangeModal.tsx
- packages/react-components/src/organisms/ManuscriptCard.tsx
- packages/react-components/src/organisms/__tests__/ConfirmStatusChangeModal.test.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptCard.test.tsx
- packages/react-components/src/templates/TeamProfileWorkspace.tsx
- packages/react-components/src/templates/__tests__/TeamProfileWorkspace.test.tsx
JIRA Ticket: https://asaphub.atlassian.net/browse/ASAP-691
---
https://github.com/user-attachments/assets/bb5bf0ef-8c9e-4f59-bf41-4a959e7774e6
> ASAP-691 Enable manuscript status change

- packages/react-components/src/organisms/OnboardingFooter.tsx
- packages/react-components/src/templates/Layout.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-643
https://github.com/user-attachments/assets/f2e1109f-e487-4f01-9041-54b8b728a607
> [ASAP-643] - fix onboarding footer

- packages/gp2-components/src/templates/__tests__/OutputDetailPage.test.tsx
- packages/react-components/package.json
- packages/react-components/src/atoms/TextEditor.tsx
- packages/react-components/src/form.ts
- packages/react-components/src/organisms/SharedResearchDetailsTagsCard.tsx
- packages/react-components/src/organisms/__tests__/SharedResearchDetailsTagsCard.test.tsx
- packages/react-components/src/templates/__tests__/SharedResearchOutput.test.tsx
- yarn.lock
[ASAP-779](https://asaphub.atlassian.net/browse/ASAP-779)
[ASAP-779]: https://asaphub.atlassian.net/browse/ASAP-779?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> (fix) Rtf editor markdown not working properly

- apps/crn-server/src/routes/public/research-output.route.ts
- apps/crn-server/test/fixtures/research-output.fixtures.ts
- packages/model/src/research-output.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-783
> add documentType to CRN's research outputs public api response

- apps/crn-frontend/src/App.tsx
- apps/crn-frontend/src/__tests__/App.test.tsx
- apps/gp2-frontend/src/App.tsx
- apps/gp2-frontend/src/__tests__/App.test.tsx
- packages/frontend-utils/src/cookie-consent/__tests__/index.test.ts
- packages/frontend-utils/src/cookie-consent/index.ts
[ASAP-758](https://asaphub.atlassian.net/browse/ASAP-758)
[ASAP-758]: https://asaphub.atlassian.net/browse/ASAP-758?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [Asap 758] implement rules for cookie preferences

- apps/crn-frontend/src/network/teams/TeamProfile.tsx
- apps/crn-frontend/src/network/teams/Workspace.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/Workspace.test.tsx
- apps/crn-server/src/controllers/team.controller.ts
- apps/storybook/src/TeamProfilePage.stories.tsx
- apps/storybook/src/TeamProfileWorkspace.stories.tsx
- packages/react-components/src/molecules/Discussion.tsx
- packages/react-components/src/molecules/__tests__/Discussion.test.tsx
- packages/react-components/src/organisms/ManuscriptCard.tsx
- packages/react-components/src/organisms/ManuscriptVersionCard.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptCard.test.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptVersionCard.test.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- packages/react-components/src/templates/TeamProfileWorkspace.tsx
- packages/react-components/src/templates/__tests__/TeamProfileHeader.test.tsx
- packages/react-components/src/templates/__tests__/TeamProfilePage.test.tsx
- packages/react-components/src/templates/__tests__/TeamProfileWorkspace.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-745
> add rules to compliance review visibility within team workspace depending on role and team

- apps/crn-server/src/data-providers/contentful/team.data-provider.ts
- apps/crn-server/test/data-providers/contentful/teams.data-provider.test.ts
- apps/crn-server/test/fixtures/teams.fixtures.ts
- packages/model/src/team.ts
- packages/react-components/src/templates/TeamProfileWorkspace.tsx
- packages/react-components/src/templates/__tests__/TeamProfileWorkspace.test.tsx
Ticket: 
No results:
Only own manuscripts:
Both:
> separate manuscripts submitted by a team from manuscripts where the team is a cotributor

- apps/crn-frontend/src/network/ProfileSwitch.tsx
- apps/crn-frontend/src/network/teams/Compliance.tsx
- apps/crn-frontend/src/network/teams/TeamProfile.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- apps/crn-frontend/src/network/teams/state.ts
- packages/model/src/analytics.ts
- packages/model/src/manuscript.ts
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/ComplianceTable.tsx
- packages/react-components/src/organisms/__tests__/ComplianceTable.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/ComplianceDashboard.tsx
- packages/react-components/src/templates/TeamProfileHeader.tsx
- packages/react-components/src/templates/__tests__/ComplianceDashboard.test.tsx
- packages/react-components/src/templates/__tests__/TeamProfileHeader.test.tsx
- packages/react-components/src/templates/index.ts
- packages/routing/src/network.ts
ref: https://asaphub.atlassian.net/browse/ASAP-565
Since the ticket focuses on the page when there are no manuscripts available, the `ComplianceTable` is minimal. 
[
](url)
> [ASAP-565] - add compliance dashboard

- apps/gp2-frontend/src/events/Routes.tsx
- apps/gp2-frontend/src/events/__tests__/Routes.test.tsx
- apps/gp2-frontend/src/outputs/OutputDetail.tsx
- packages/flags/src/index.ts
- packages/gp2-components/src/organisms/ProjectDetailHeader.tsx
- packages/gp2-components/src/organisms/UserDetailHeader.tsx
- packages/gp2-components/src/organisms/WorkingGroupDetailHeader.tsx
- packages/gp2-components/src/templates/DashboardPageBody.tsx
- packages/gp2-components/src/templates/EventsPage.tsx
- packages/gp2-components/src/templates/OutputDetailPage.tsx
- packages/gp2-components/src/templates/__tests__/EventsPage.test.tsx
- packages/gp2-components/src/templates/__tests__/OutputDetailPage.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-808
> ASAP-808 Remove feature flag for research output version and events

- apps/crn-frontend/src/network/teams/__tests__/Workspace.test.tsx
- packages/react-components/src/atoms/TextEditor.tsx
- packages/react-components/src/molecules/UserComment.tsx
- packages/react-components/src/molecules/__tests__/Discussion.test.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptVersionCard.test.tsx
[ASAP-459](https://asaphub.atlassian.net/browse/ASAP-459)
[ASAP-459]: https://asaphub.atlassian.net/browse/ASAP-459?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ASAP-585] Quick replies Manuscripts / Compliance report replies - Text strikethrough not working

- apps/crn-frontend/src/App.tsx
- packages/frontend-utils/src/cookie-consent/__tests__/index.test.ts
- packages/frontend-utils/src/cookie-consent/index.ts
- packages/react-components/src/templates/GoogleTagManager.tsx
- packages/react-components/src/templates/__tests__/GoogleTagManager.test.tsx
[ASAP-817](https://asaphub.atlassian.net/browse/ASAP-817)
[ASAP-817]: https://asaphub.atlassian.net/browse/ASAP-817?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ASAP-817 [CRN][GP2] cookies google analytics collection issue

- apps/crn-server/src/routes/public/research-output.route.ts
- apps/crn-server/test/routes/public/research-output.route.test.ts
- packages/model/src/research-output.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-796
---
It's possible to test in: https://api-4490.hub.asap.science/public/research-outputs
> ASAP-796 Add preprint data to research output public response

- apps/crn-server/src/data-providers/contentful/manuscript.data-provider.ts
- apps/crn-server/test/data-providers/contentful/manuscript.data-provider.test.ts
- packages/contentful/migrations/crn/manuscripts/20250102124427-add-status-changed-fields.js
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-834
> ASAP-834 Add status changed fields to manuscript

- apps/crn-frontend/src/App.tsx
- apps/crn-frontend/src/__tests__/App.test.tsx
- apps/crn-frontend/src/welcome/__tests__/Welcome.test.tsx
- apps/gp2-frontend/src/App.tsx
- apps/gp2-frontend/src/__tests__/App.test.tsx
- apps/gp2-frontend/src/welcome/__tests__/Welcome.test.tsx
- packages/flags/src/index.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-849
> remove cookie preferences feature flag for CRN and GP2

- apps/crn-frontend/src/dashboard/Dashboard.tsx
- apps/crn-frontend/src/dashboard/__tests__/Dashboard.test.tsx
JIRA ticket: https://asaphub.atlassian.net/browse/ASAP-852
> ASAP-852 Display manuscript reminders behind feature flag

- apps/crn-frontend/src/network/ProfileSwitch.tsx
- apps/crn-frontend/src/network/teams/Compliance.tsx
- apps/crn-frontend/src/network/teams/TeamProfile.tsx
- apps/crn-frontend/src/network/teams/__tests__/Compliance.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/api.test.ts
- apps/crn-frontend/src/network/teams/api.ts
- apps/crn-frontend/src/network/teams/state.ts
- packages/algolia/schema/crn/algolia-reverse-timestamp-schema.json
- packages/algolia/schema/crn/algolia-schema.json
- packages/model/src/manuscript.ts
- packages/react-components/src/molecules/ComplianceControls.tsx
- packages/react-components/src/molecules/DropdownButton.tsx
- packages/react-components/src/molecules/__tests__/ComplianceControls.test.tsx
- packages/react-components/src/molecules/__tests__/DropdownButton.test.tsx
- packages/react-components/src/templates/ComplianceDashboard.tsx
- packages/react-components/src/templates/__tests__/ComplianceDashboard.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-768
---
> ASAP-768 Compliance table filters

- apps/crn-frontend/src/network/teams/TeamManuscript.tsx
- packages/model/src/manuscript.ts
- packages/react-components/src/templates/ManuscriptForm.tsx
- packages/react-components/src/templates/__tests__/ManuscriptForm.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-867
> [ASAP-867] - fix quick check discussion details in edit form

- apps/crn-frontend/src/network/teams/Compliance.tsx
- apps/crn-frontend/src/network/teams/TeamProfile.tsx
- apps/crn-frontend/src/network/teams/__tests__/Compliance.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/api.test.ts
- apps/crn-frontend/src/network/teams/__tests__/useComplianceSearch.test.ts
- apps/crn-frontend/src/network/teams/api.ts
- apps/crn-frontend/src/network/teams/useComplianceSearch.ts
- packages/react-components/src/colors.ts
- packages/react-components/src/molecules/ComplianceControls.tsx
- packages/react-components/src/molecules/__tests__/ComplianceControls.test.tsx
- packages/react-components/src/molecules/index.ts
- packages/react-components/src/organisms/ManuscriptByStatus.tsx
- packages/react-components/src/organisms/ManuscriptCard.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptByStatus.test.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptCard.test.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/ComplianceDashboard.tsx
- packages/react-components/src/templates/__tests__/ComplianceDashboard.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-888
--- 
URL: https://4526.hub.asap.science/network/teams/8c88a42b-9fc7-4ec1-8606-204be75d252c/compliance?completedStatus=show&requestedAPCCoverage=all&status=Waiting+for+Report&status=Compliant
> ASAP-888 Manuscript By Status

- packages/react-components/src/icons/endDiscussionIcon.tsx
- packages/react-components/src/molecules/Discussion.tsx
- packages/react-components/src/molecules/__tests__/Discussion.test.tsx
- packages/react-components/src/organisms/ComplianceReportCard.tsx
- packages/react-components/src/organisms/ManuscriptFormModals.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-836
> compliance copy changes

- apps/crn-frontend/src/network/teams/Compliance.tsx
- packages/react-components/src/molecules/ComplianceControls.tsx
- packages/react-components/src/molecules/__tests__/ComplianceControls.test.tsx
- packages/react-components/src/templates/ComplianceDashboard.tsx
- packages/react-components/src/templates/__tests__/ComplianceDashboard.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-902
---
With filter applied: https://4529.hub.asap.science/network/teams/8c88a42b-9fc7-4ec1-8606-204be75d252c/compliance?completedStatus=hide&requestedAPCCoverage=yes
No results: https://4529.hub.asap.science/network/teams/8c88a42b-9fc7-4ec1-8606-204be75d252c/compliance?completedStatus=hide&requestedAPCCoverage=yes&status=Manuscript+Resubmitted
> ASAP-902 Add Manuscript Count

- apps/crn-frontend/src/network/teams/__tests__/TeamComplianceReport.test.tsx
- packages/react-components/src/atoms/TextEditor.tsx
- packages/react-components/src/atoms/__tests__/TextEditor.test.tsx
- packages/react-components/src/molecules/ExpandableText.tsx
- packages/react-components/src/molecules/LabeledTextEditor.tsx
- packages/react-components/src/molecules/LabeledTextField.tsx
- packages/react-components/src/organisms/ComplianceReportCard.tsx
- packages/react-components/src/organisms/__tests__/ComplianceReportCard.test.tsx
- packages/react-components/src/templates/ComplianceReportForm.tsx
- packages/react-components/src/templates/__tests__/ComplianceReportForm.test.tsx
[ASAP-842](https://asaphub.atlassian.net/browse/ASAP-842)
[ASAP-842]: https://asaphub.atlassian.net/browse/ASAP-842?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ASAP-842] - Add RTF capability on the compliance report form

- apps/crn-frontend/src/network/teams/TeamManuscript.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamManuscript.test.tsx
- apps/crn-server/src/controllers/manuscript.controller.ts
- apps/crn-server/src/routes/manuscript.route.ts
- apps/crn-server/test/controllers/manuscript.controller.test.ts
- apps/crn-server/test/routes/manuscript.route.test.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-915
> ASAP-915 Validate title uniqueness without creating draft

- packages/react-components/src/organisms/ComplianceTable.tsx
- packages/react-components/src/organisms/ComplianceTableRow.tsx
- packages/react-components/src/organisms/__tests__/ComplianceTable.test.tsx
- packages/react-components/src/organisms/__tests__/ComplianceTableRow.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-901
> [ASAP-901] - compliance table update

- apps/crn-frontend/src/analytics/collaboration/Collaboration.tsx
- apps/crn-frontend/src/analytics/engagement/Engagement.tsx
- apps/crn-frontend/src/analytics/leadership/Leadership.tsx
- apps/crn-frontend/src/analytics/leadership/__tests__/export.test.ts
- apps/crn-frontend/src/analytics/productivity/Productivity.tsx
- apps/crn-frontend/src/analytics/utils/export.ts
- apps/crn-frontend/src/network/teams/Compliance.tsx
- apps/crn-frontend/src/network/teams/Outputs.tsx
- apps/crn-frontend/src/network/teams/__tests__/Compliance.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/Outputs.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/export.test.ts
- apps/crn-frontend/src/network/teams/export.ts
- apps/crn-frontend/src/network/users/Outputs.tsx
- apps/crn-frontend/src/network/working-groups/Outputs.tsx
- apps/crn-frontend/src/shared-research/ResearchOutputList.tsx
- apps/crn-frontend/src/shared-research/__mocks__/export.ts
- apps/crn-frontend/src/shared-research/__tests__/export.test.ts
- apps/crn-frontend/src/shared-research/export.ts
- packages/frontend-utils/src/csv-export/__tests__/index.test.ts
- packages/frontend-utils/src/csv-export/index.ts
- packages/react-components/src/molecules/ComplianceControls.tsx
- packages/react-components/src/molecules/__tests__/ComplianceControls.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-567
---
A refactor was also made so we don't repeat `algoliaResultsToStream` across different files.
> ASAP-567 Download Compliance Data

- apps/crn-frontend/src/shared-research/export.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-959
Reference:
https://support.algolia.com/hc/en-us/articles/4919170182545-Is-there-a-limit-on-hitsPerPage#:~:text=Hits%20per%20page%20is%20limited%20to%201000.
> update MAX_ALGOLIA_RECORDS value to meet Algolia's limit

- packages/react-components/src/molecules/StatusButton.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptCard.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-906
> replace information icon with warning icon on status button component

- apps/crn-server/src/data-providers/contentful/team.data-provider.ts
- apps/crn-server/test/data-providers/contentful/teams.data-provider.test.ts
- apps/crn-server/test/fixtures/teams.fixtures.ts
[ASAP-903](https://asaphub.atlassian.net/browse/ASAP-903)
[ASAP-903]: https://asaphub.atlassian.net/browse/ASAP-903?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ASAP-903] - Orders Manuscripts in Teams Compliance Workspace

- apps/crn-frontend/src/network/teams/TeamComplianceReport.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamComplianceReport.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/api.test.ts
- apps/crn-frontend/src/network/teams/state.ts
- apps/crn-server/src/app.ts
- apps/crn-server/src/controllers/compliance-report.controller.ts
- apps/crn-server/src/routes/compliance-report.route.ts
- apps/crn-server/src/validation/compliance-report.validation.ts
- apps/crn-server/test/controllers/compliance-report.controller.test.ts
- apps/crn-server/test/data-providers/contentful/compliance-reports.data-provider.test.ts
- apps/crn-server/test/fixtures/compliance-reports.fixtures.ts
- apps/crn-server/test/routes/compliance-report.route.test.ts
- packages/fixtures/src/manuscripts.ts
- packages/model/src/compliance-report.ts
- packages/react-components/src/atoms/Dropdown.tsx
- packages/react-components/src/atoms/__tests__/Dropdown.test.tsx
- packages/react-components/src/index.ts
- packages/react-components/src/molecules/StatusBadge.tsx
- packages/react-components/src/molecules/__tests__/StatusBadge.test.tsx
- packages/react-components/src/molecules/index.ts
- packages/react-components/src/organisms/ComplianceReportCard.tsx
- packages/react-components/src/organisms/__tests__/ComplianceReportCard.test.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptCard.test.tsx
- packages/react-components/src/templates/ComplianceReportForm.tsx
- packages/react-components/src/templates/ManuscriptForm.tsx
- packages/react-components/src/templates/__tests__/ComplianceReportForm.test.tsx
- packages/react-components/src/templates/__tests__/ManuscriptForm.test.tsx
[ASAP-785](https://asaphub.atlassian.net/browse/ASAP-785)
[ASAP-785]: https://asaphub.atlassian.net/browse/ASAP-785?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ASAP-785] - Enable users to set Manuscript Status within Share Compliance Report form

- apps/crn-frontend/src/network/teams/__mocks__/api.ts
- apps/crn-frontend/src/network/teams/__tests__/Compliance.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/export.test.ts
- apps/crn-frontend/src/network/teams/export.ts
- apps/crn-frontend/src/network/teams/state.ts
- apps/crn-server/src/controllers/manuscript.controller.ts
- apps/crn-server/src/data-providers/contentful/manuscript.data-provider.ts
- apps/crn-server/test/controllers/manuscript.controller.test.ts
- apps/crn-server/test/fixtures/manuscript.fixtures.ts
- packages/algolia/schema/crn/algolia-reverse-timestamp-schema.json
- packages/algolia/schema/crn/algolia-schema.json
- packages/fixtures/src/manuscripts.ts
- packages/react-components/src/organisms/ComplianceTable.tsx
- packages/react-components/src/organisms/ComplianceTableRow.tsx
- packages/react-components/src/organisms/__tests__/ComplianceTable.test.tsx
- packages/react-components/src/organisms/__tests__/ComplianceTableRow.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-970
> [ASAP-970] - fix multiple versions in compliance table

- apps/crn-frontend/src/network/teams/__tests__/Compliance.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamComplianceReport.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/Workspace.test.tsx
- apps/storybook/src/StatusButton.stories.tsx
- packages/model/src/manuscript.ts
- packages/postmark/src/templates/waiting-for-report-grantees/content.html
- packages/react-components/src/organisms/ComplianceTableRow.tsx
- packages/react-components/src/organisms/ManuscriptCard.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptCard.test.tsx
- packages/react-components/src/templates/ComplianceReportForm.tsx
- packages/react-components/src/templates/__tests__/ComplianceReportForm.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-947
The client asked to modify the update from the ticket https://asaphub.atlassian.net/browse/ASAP-971. 
I've added that in this ticket as it's a minor change
> [ASAP-947] - remove manuscript statuses

- apps/crn-server/src/data-providers/contentful/manuscript.data-provider.ts
- packages/contentful/migrations/crn/manuscripts/20250417143217-add-apc-fields.js
ref: https://asaphub.atlassian.net/browse/ASAP-981
> [ASAP-981] - update manuscript content model

- apps/gp2-server/src/routes/public/user.route.ts
- apps/gp2-server/test/fixtures/user.fixtures.ts
- packages/model/src/gp2/user.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-1001
> ASAP-1001 Add region and state/province to GP2 public API

- apps/crn-frontend/src/network/teams/Workspace.tsx
- packages/react-components/src/atoms/Pill.tsx
- packages/react-components/src/organisms/ComplianceTableRow.tsx
- packages/react-components/src/organisms/ManuscriptCard.tsx
- packages/react-components/src/organisms/__tests__/ManuscriptCard.test.tsx
- packages/react-components/src/templates/TeamProfileWorkspace.tsx
- packages/react-components/src/templates/__tests__/TeamProfileWorkspace.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-905
Note: The scroll behaviour will have to be updated as it doesn't always work (eg: on slow page loads). Padmini agreed to leave as is and come back to it later.
> [ASAP-905] - add link to manuscript

- packages/postmark/src/templates/compliant/content.html
- packages/postmark/src/templates/submit-final-publication/content.html
ref: https://asaphub.atlassian.net/browse/ASAP-1009
https://asaphub.atlassian.net/browse/ASAP-939
> [ASAP-1009] - update compliant & submit final publication templates

- apps/crn-frontend/src/network/teams/__tests__/api.test.ts
- apps/crn-frontend/src/network/teams/api.ts
- packages/algolia/schema/crn/algolia-reverse-timestamp-schema.json
- packages/algolia/schema/crn/algolia-schema.json
https://asaphub.atlassian.net/browse/ASAP-994
> ASAP-994 Order Compliance Table by last updated desc

- apps/crn-frontend/src/network/teams/__tests__/Compliance.test.tsx
- packages/react-components/src/organisms/ComplianceAssignUsersModal.tsx
- packages/react-components/src/organisms/__tests__/ComplianceAssignUsersModal.test.tsx
- packages/react-components/src/organisms/__tests__/ComplianceTable.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-932
> [ASAP-932] - update assign users modal copy

- packages/postmark/src/templates/compliant/content.html
- packages/postmark/src/templates/submit-final-publication/content.html
ref: https://asaphub.atlassian.net/browse/ASAP-1027
> [ASAP-1027] - update compliant/ submit final email template

- apps/crn-server/src/controllers/user.controller.ts
- apps/crn-server/src/data-providers/contentful/user.data-provider.ts
- apps/crn-server/src/routes/public/user.route.ts
- apps/crn-server/test/data-providers/contentful/users.data-provider.test.ts
- apps/crn-server/test/fixtures/users.fixtures.ts
- apps/crn-server/test/routes/public/user.route.test.ts
- packages/model/src/user.ts
ref: https://asaphub.atlassian.net/browse/ASAP-1028
> [ASAP-1028] - add alumni field to public users api

- apps/crn-frontend/src/network/teams/Compliance.tsx
- apps/crn-frontend/src/network/teams/TeamProfile.tsx
- apps/crn-frontend/src/network/teams/__tests__/Compliance.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamProfile.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/api.test.ts
- apps/crn-frontend/src/network/teams/__tests__/useComplianceSearch.test.ts
- apps/crn-frontend/src/network/teams/api.ts
- apps/crn-frontend/src/network/teams/useComplianceSearch.ts
- packages/algolia/schema/crn/algolia-reverse-timestamp-schema.json
- packages/algolia/schema/crn/algolia-schema.json
- packages/model/src/manuscript.ts
- packages/react-components/src/molecules/ComplianceControls.tsx
- packages/react-components/src/molecules/DropdownButton.tsx
- packages/react-components/src/molecules/__tests__/ComplianceControls.test.tsx
[ASAP-1021](https://asaphub.atlassian.net/browse/ASAP-1021)
[ASAP-1021]: https://asaphub.atlassian.net/browse/ASAP-1021?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ASAP-1021 enable users to filter by apc coverage status

- packages/flags/src/index.ts
- packages/react-components/src/molecules/ComplianceControls.tsx
- packages/react-components/src/organisms/ComplianceTableRow.tsx
- packages/react-components/src/organisms/__tests__/ComplianceTable.test.tsx
- packages/react-components/src/organisms/__tests__/ComplianceTableRow.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-1071
> [ASAP-1071] - remove apc coverage flag

- packages/react-components/src/templates/ManuscriptForm.tsx
- packages/react-components/src/templates/__tests__/ManuscriptForm.quickChecks.test.tsx
ref: https://asaphub.atlassian.net/browse/ASAP-1073
> [ASAP-1073] - add validation to quick check details fields

- apps/crn-frontend/src/network/teams/TeamOutput.tsx
- apps/crn-frontend/src/network/teams/__tests__/TeamOutput.test.tsx
- apps/crn-frontend/src/network/working-groups/WorkingGroupOutput.tsx
- apps/crn-frontend/src/network/working-groups/__tests__/WorkingGroupOutput.test.tsx
- packages/flags/src/index.ts
- packages/react-components/src/index.ts
- packages/react-components/src/molecules/FormCard.tsx
- packages/react-components/src/molecules/LabeledRadioButtonGroup.tsx
- packages/react-components/src/templates/ManuscriptOutputSelection.tsx
- packages/react-components/src/templates/__tests__/ManuscriptOutputSelection.test.tsx
- packages/react-components/src/templates/index.ts
Jira: https://asaphub.atlassian.net/browse/ASAP-987
---
To test it's necessary to active the feature flag:
```
document.cookie = 'ASAP_MANUSCRIPT_OUTPUTS = true'
```
> ASAP-987 Manuscript Outputs Selection Screen

- apps/crn-frontend/src/network/teams/ManuscriptToastProvider.tsx
- apps/crn-frontend/src/network/teams/Workspace.tsx
- apps/crn-frontend/src/network/teams/__tests__/Workspace.test.tsx
- apps/crn-frontend/src/network/teams/__tests__/state.test.tsx
- apps/crn-frontend/src/network/teams/state.ts
- apps/crn-server/src/app.ts
- apps/crn-server/src/routes/discussion.route.ts
- apps/crn-server/test/routes/discussion.route.test.ts
- packages/react-components/src/organisms/DiscussionsTab.tsx
- packages/react-components/src/organisms/ManuscriptCard.tsx
- packages/react-components/src/organisms/Toast.tsx
- packages/react-components/src/templates/TeamProfileWorkspace.tsx
[ASAP-962](https://asaphub.atlassian.net/browse/ASAP-962)
[ASAP-962]: https://asaphub.atlassian.net/browse/ASAP-962?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ASAP-962 Restrict users from submitting discussions replies on a closed or compliant manuscript

- apps/gp2-server/package.json
- apps/gp2-server/scripts/import-users-cohorts-version.ts
- apps/gp2-server/src/controllers/contributing-cohort.controller.ts
- apps/gp2-server/src/data-providers/contributing-cohort.data-provider.ts
- apps/gp2-server/src/data-providers/types/contributing-cohort.data-provider.type.ts
- apps/gp2-server/src/data-providers/user.data-provider.ts
- apps/gp2-server/test/data-providers/contributing-cohort.data-provider.test.ts
- packages/model/src/gp2/user.ts
- packages/server-common/src/validation/validation.ts
This PR adds a script to import users into Contentful given a CSV File with the format https://asapparkinson-roadmap.slack.com/files/U078WPKMLS0/F092GUDQUTA/gp2_banner_authorship_list_-_member_details_final_to_upload__2___1_.xlsx.
To run this script, use the following command from `@asap-hub/gp2-server` folder:
```
CONTENTFUL_ACCESS_TOKEN=*** CONTENTFUL_SPACE_ID=*** CONTENTFUL_ENV_ID=*** CONTENTFUL_MANAGEMENT_ACCESS_TOKEN=*** yarn import:users:cohorts-version [path-to-csv]
```
> ASAP-1025 Import users with cohorts script

- apps/crn-frontend/src/network/teams/TeamManuscript.tsx
- apps/crn-frontend/src/shared-state/__tests__/category.test.ts
- apps/crn-frontend/src/shared-state/__tests__/impact.test.ts
- apps/crn-frontend/src/shared-state/category.ts
- apps/crn-frontend/src/shared-state/impact.ts
Ticket: https://asaphub.atlassian.net/browse/ASAP-1092
> ASAP-1092 Increase max number of category and impact values returned

- packages/contentful/migrations/crn/awards/20250711121119-create-awards-content-type.js
- packages/contentful/migrations/crn/teamMembership/20250711121313-add-awards-field.js
https://asaphub.atlassian.net/browse/ASAP-829
> ASAP-829 Add Awards content model to CMS and to team membership

- packages/gp2-components/src/templates/__tests__/OutputDetailPage.test.tsx
- packages/react-components/src/organisms/SharedResearchDetailsTagsCard.tsx
- packages/react-components/src/organisms/__tests__/SharedResearchDetailsTagsCard.test.tsx
- packages/react-components/src/templates/SharedResearchOutput.tsx
- packages/react-components/src/templates/__tests__/SharedResearchOutput.test.tsx
Jira ticket: https://asaphub.atlassian.net/browse/ASAP-1003
---
> ASAP-1003 Display Short Description and Changelog on Output

- packages/react-components/src/organisms/ResearchOutputFormSharingCard.tsx
- packages/react-components/src/organisms/__tests__/ResearchOutputFormSharingCard.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-1095
> ASAP-1095 Impact as required on Output

- apps/crn-frontend/src/network/users/__tests__/UserProfile.test.tsx
- packages/react-components/src/molecules/TabbedContent.tsx
- packages/react-components/src/molecules/UserProfilePersonalText.tsx
- packages/react-components/src/molecules/__tests__/UserProfilePersonalText.test.tsx
- packages/react-components/src/organisms/UserTeamsTabbedCard.tsx
- packages/react-components/src/organisms/__tests__/UserTeamsTabbedCard.test.tsx
- packages/react-components/src/templates/UserProfileHeader.tsx
- packages/react-components/src/templates/__tests__/UserProfileHeader.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-863
---
> ASAP-863 Display former roles

- apps/crn-frontend/src/analytics/leadership/Leadership.tsx
- apps/crn-frontend/src/analytics/leadership/__tests__/Leadership.test.tsx
- apps/crn-frontend/src/analytics/leadership/api.ts
- apps/crn-frontend/src/analytics/leadership/export.ts
- apps/crn-frontend/src/analytics/leadership/state.ts
- packages/flags/src/index.ts
- packages/model/src/analytics.ts
- packages/react-components/src/index.ts
- packages/react-components/src/organisms/OSChampionTable.tsx
- packages/react-components/src/organisms/index.ts
- packages/react-components/src/templates/AnalyticsLeadershipPageBody.tsx
- packages/react-components/src/templates/__tests__/AnalyticsLeadershipPageBody.test.tsx
- packages/react-components/src/templates/__tests__/LeadershipPageBody.test.tsx
Ticket: https://asaphub.atlassian.net/browse/ASAP-879
> create OS Champion Analytics page

- packages/react-components/src/templates/ManuscriptForm.tsx
- packages/react-components/src/templates/__tests__/ManuscriptForm.errors.test.tsx
[ASAP-1097](https://asaphub.atlassian.net/browse/ASAP-1097)
[ASAP-1097]: https://asaphub.atlassian.net/browse/ASAP-1097?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> ASAP-1097 Selecting Type and Lifecycle fields on Manuscript Form triggers a rerender

- apps/crn-frontend/src/network/teams/TeamOutput.tsx
- apps/crn-frontend/src/shared-research/ResearchOutput.tsx
- apps/crn-frontend/src/shared-research/state.ts
- apps/crn-frontend/src/shared-research/util.ts
- apps/crn-server/src/routes/research-output.route.ts
- apps/crn-server/test/routes/research-output.route.test.ts
- packages/react-components/src/templates/ResearchOutputForm.tsx
- packages/react-components/src/templates/__tests__/ResearchOutputForm/ResearchOutputForm.formButtons.test.tsx
- packages/validation/src/__tests__/permissions/research-output.test.ts
- packages/validation/src/permissions/research-output.ts
ref: https://asaphub.atlassian.net/browse/ASAP-1143
> [ASAP-1143] - update research output permissions

- apps/crn-frontend/src/analytics/collaboration/Collaboration.tsx
- apps/crn-frontend/src/analytics/engagement/Engagement.tsx
- apps/crn-frontend/src/analytics/leadership/Leadership.tsx
- apps/crn-frontend/src/analytics/leadership/__tests__/Leadership.test.tsx
- apps/crn-frontend/src/analytics/leadership/__tests__/export.test.ts
- apps/crn-frontend/src/analytics/leadership/export.ts
- apps/crn-frontend/src/analytics/productivity/Productivity.tsx
- apps/crn-frontend/src/network/teams/Compliance.tsx
- apps/crn-frontend/src/network/teams/Outputs.tsx
- apps/crn-frontend/src/network/users/Outputs.tsx
- apps/crn-frontend/src/network/working-groups/Outputs.tsx
- apps/crn-frontend/src/shared-research/ResearchOutputList.tsx
- packages/frontend-utils/src/csv-export/__tests__/index.test.ts
- packages/frontend-utils/src/csv-export/index.ts
[ASAP-883](https://asaphub.atlassian.net/browse/ASAP-883)
[ASAP-883]: https://asaphub.atlassian.net/browse/ASAP-883?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ASAP-883] - L & M - Enable user to download OS Award Analytics Data

- apps/crn-frontend/src/analytics/collaboration/__tests__/Collaboration.test.tsx
- apps/crn-frontend/src/analytics/engagement/__tests__/Engagement.test.tsx
- apps/crn-frontend/src/analytics/leadership/__tests__/Leadership.test.tsx
- apps/crn-frontend/src/analytics/open-science/OpenScience.tsx
- apps/crn-frontend/src/analytics/open-science/PreprintCompliance.tsx
- apps/crn-frontend/src/analytics/open-science/__tests__/OpenScience.test.tsx
- apps/crn-frontend/src/analytics/open-science/__tests__/PreprintCompliance.test.tsx
- apps/crn-frontend/src/analytics/open-science/__tests__/api.test.ts
- apps/crn-frontend/src/analytics/open-science/api.ts
- apps/crn-frontend/src/analytics/open-science/state.ts
- apps/crn-frontend/src/analytics/productivity/__tests__/Productivity.test.tsx
- packages/model/src/analytics.ts
- packages/react-components/src/index.ts
- packages/react-components/src/molecules/AnalyticsControls.tsx
- packages/react-components/src/molecules/__tests__/AnalyticsControls.test.tsx
- packages/react-components/src/organisms/PreprintComplianceTable.tsx
- packages/react-components/src/organisms/__tests__/PreprintComplianceTable.test.tsx
- packages/react-components/src/templates/AnalyticsLeadershipPageBody.tsx
- packages/react-components/src/templates/AnalyticsOpenSciencePageBody.tsx
- packages/react-components/src/templates/LoadingLayout.tsx
- packages/react-components/src/templates/__tests__/LeadershipPageBody.test.tsx
- packages/react-components/src/templates/__tests__/LoadingLayout.test.tsx
- packages/react-components/src/templates/index.ts
[ASAP-1057](https://asaphub.atlassian.net/browse/ASAP-1057)
[ASAP-1057]: https://asaphub.atlassian.net/browse/ASAP-1057?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> [ASAP-1057] - Open Science: Display Preprint Compliance data
